### ISSUE TITLE
答非所问

### ISSUE THREAD

**Issue by lixianyu** [udacity/DAND-CN-feedback#10]
## 课程导航+地址
课程5：脚本编写 > [23.解决方案：标准库](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/e29dc3ee-b0fc-47dd-af4a-288cf51985bb)

## 截图
![image](https://user-images.githubusercontent.com/1388798/37549818-ff329cfa-29be-11e8-9b17-3db32553fc48.png)

## 具体描述
该解决方案并不是上一节课`22.练习：标准库` 的解决方案

**Comment by Kyliewang** [comment]
英文课程中并没有包含“计算指数”练习题的答案。已经在中文课程中补充。
