### ISSUE TITLE
【共享单车项目】【实战项目概览】【字幕翻译】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#100]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/e32ff3f7-8031-400c-a3d2-0fbb05b061ef

## 截图
![tim 20180322202831](https://user-images.githubusercontent.com/11519486/37770536-b3a3c6a6-2e0f-11e8-96ef-08aee8beac4d.png)
![tim 20180322204042](https://user-images.githubusercontent.com/11519486/37771079-79f61f60-2e11-11e8-831c-a403860497a5.png)

## 具体描述
1. 视频 01:41 滤波器应该改为过滤器
2. 视频 02:08 建议修改为：程序显示最热门的出行时间是 17 点 次数为 723 次

**Comment by Kyliewang** [comment]
@sylviasun916 实习生这部分翻译的问题有点多，麻烦圆圆统一看一下哦~

**Comment by sylviasun916** [comment]
已修改 感谢反馈
