### ISSUE TITLE
【共享单车项目】【实战项目概览】没有英文字幕

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#101]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/e32ff3f7-8031-400c-a3d2-0fbb05b061ef

![tim 20180322215124](https://user-images.githubusercontent.com/11519486/37774454-378d7bfa-2e1b-11e8-975b-e2fdd9cbee5b.png)

## 具体描述
墙内播放器只有中文字幕，没有英文字幕。
在 youtube 播放器打开，中英文字幕都有

**Comment by sylviasun916** [comment]
已修改 部署中 谢谢反馈
