### ISSUE TITLE
【共享单车项目】【选修】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#102]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/333ef09b-64c2-4482-8b51-fdb1280fef82

## 截图
![tim 20180322214855](https://user-images.githubusercontent.com/11519486/37774542-73697890-2e1b-11e8-9e90-fcb6c0377b11.png)

## 具体描述
遗漏的值应该翻译为缺失值

**Comment by sylviasun916** [comment]
已修改 谢谢反馈
