### ISSUE TITLE
【共享单车项目】[选修]练习题 1

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#103]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/880df209-4c85-4151-89c9-02ea6664936f

## 截图
![image](https://user-images.githubusercontent.com/11519486/37774883-5d325da2-2e1c-11e8-8885-f947864751a2.png)

## 具体描述
因为现在打不开英文版，所以看不到原版的文字是什么，不过红框中的描述明显有问题。

根据下方的代码，可以看到需要求的是 hour，也就是 Start Time 最常见的 hour。相应的文字应该是：
- “数据集中并没有 hour 列，但你可以通过提取 “Start Time” 中的 hour 来创建 hour 列”
后面的 `property 文件` 不知道原英文是什么，不过最后一句很费解，建议根据实际需求修改表述方式，而不仅仅是翻译原英文。 @Kyliewang

**Comment by sylviasun916** [comment]
已修改 感谢反馈
