### ISSUE TITLE
【共享单车项目】[选修] 练习题 3

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#104]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d82f015d-fe75-4de1-b76b-0fdebe4cd9d7

## 截图
![image](https://user-images.githubusercontent.com/11519486/37775253-758da5f4-2e1d-11e8-9b52-3db848a1b8b4.png)

## 具体描述
因为没有英文版本不清楚具体原文，根据自己的理解在截图上标注了一下需要修改的内容 @Kyliewang

**Comment by sylviasun916** [comment]
已修改 感谢反馈
