### ISSUE TITLE
【共享单车项目】【代码流程】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#105]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/60d1f821-5e76-4815-8dca-4ff9a5bcf47d

## 截图
![image](https://user-images.githubusercontent.com/11519486/37775395-cc964bf8-2e1d-11e8-83c5-30ca224fae5b.png)

## 具体描述
“上一页”的问题，没看懂……
四个问题建议保留原来的英文文本，因为代码中用的是英文文本。

**Comment by sylviasun916** [comment]
已修改 谢谢反馈
