### ISSUE TITLE
【共享单车项目】【如何完成该实战项目】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#106]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/b8cd0f85-1c2b-4636-bcfd-f4348447f8b2

## 截图
![image](https://user-images.githubusercontent.com/11519486/37775551-379a9238-2e1e-11e8-8e37-56b7a06d2869.png)

## 具体描述
没有找到可以提交作业的“末尾处的链接”

**Comment by Kyliewang** [comment]
目前暂不提供新项目的提交入口，内测结束后将会提供。
