### ISSUE TITLE
页面内容中的符号错误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#107]
入门 > 新Python入门 > 控制流 > [8. For循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/5c057e68-4556-4f47-885b-1c964003df27)

<img width="611" alt="_20180322230403" src="https://user-images.githubusercontent.com/33887956/37778620-5c77eb9e-2e25-11e8-93c0-b683cfc4fe62.png">

上图中第三行的最后面，建议将 上述=0'和 '=1  修改为 上述=0和=1  删除掉单引号

**Comment by Kyliewang** [comment]
已经修改。

@sylviasun916 这里是Markdown错误，并非为单引号'，而是`（数字1左边的按键），请记录。
