### ISSUE TITLE
課程5: 2-6 很難follow

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#108]
## 截图
![Uploading WeChat 圖片_20180323205101.png…]()
## 具体描述
要跳到別的課程去學，而且又是英文，所以我都自己去知乎上面查整個過程還比較詳細。
https://www.zhihu.com/question/58033789

**Comment by Kyliewang** [comment]
已经将你提供的链接补充在教室中，感谢！
