### ISSUE TITLE
在脚本中接受原始输入

### ISSUE THREAD

**Issue by lixianyu** [udacity/DAND-CN-feedback#11]
## 课程导航+地址
课程5：脚本编写  > [8.在脚本中接受原始输入](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/622bcf85-e02b-4ed1-a6b1-bc6629c8fcf7)

## 截图
![image](https://user-images.githubusercontent.com/1388798/37549945-9938adf2-29c0-11e8-88f3-49672cc96d92.png)

## 具体描述
如上图，红色椭圆框处应改为：
```
num = int(input("Enter an integer"))
print("hello" * num)
```

**Comment by Kyliewang** [comment]
已经在coco中修改。
