### ISSUE TITLE
5-13节，视频内的代码与页面里的代码有错误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#110]
入门 > 新Python入门 > 课程5:脚本编写 > [13. 处理错误](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/d99ae312-d4cb-4f5a-9e0c-3e84550c8cc8)

<img width="259" alt="_20180323205359" src="https://user-images.githubusercontent.com/33887956/37830293-eb0a656e-2edc-11e8-9c2b-285e79f4a7e2.png">
<img width="595" alt="_20180323205405" src="https://user-images.githubusercontent.com/33887956/37830336-f4f66f32-2edc-11e8-8213-23494823fa0f.png">

视频01:07s处的代码，以及与之对应页面内容中的代码，需将except ValueError, KeyboardInterrupt:，修改成except (ValueError, KeyboardInterrupt):，加上元组的圆括号，否则会报Syntax Error的错误。

**Comment by Kyliewang** [comment]
文本中已经修改。视频不是很方便修改，所以暂时搁置。感谢建议！
