### ISSUE TITLE
5-16节，代码的输出结果有错误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#111]
入门 > 新Python入门 > 课程5:脚本编写 > 16. 访问错误讯息

<img width="368" alt="_20180324001538" src="https://user-images.githubusercontent.com/33887956/37840705-c33570b2-2ef8-11e8-8583-52662b4a637a.png">

输出结果应是=>division by zero，而非integer division or modulo by zero，请见下图：

<img width="251" alt="_20180324001542" src="https://user-images.githubusercontent.com/33887956/37840886-39315024-2ef9-11e8-8d64-56ebe29df810.png">

**Comment by Kyliewang** [comment]
已经修改。感谢！
