### ISSUE TITLE
5-22练习:标准库 后面5题 在对应的解决方案无答案

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#112]
入门 > 新Python入门 > 课程5:脚本编写 > [22. 练习:标准库](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/206c580e-6364-4f85-8cdc-7ef8c8294ba3)

<img width="300" alt="_20180324151615" src="https://user-images.githubusercontent.com/33887956/37861560-20011a7a-2f77-11e8-9ccc-06bb4dbc0d39.png">

该章节的后面5题，在对应的解决方案无答案

**Comment by Kyliewang** [comment]
已经补充。
