### ISSUE TITLE
翻译问题:建议将"拆封"，翻译成"解包"

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#114]
入门 > 新Python入门 > 课程2:数据类型和运算符 > [21. 元组](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/e043295e-2639-4d17-a8c0-c3824811ad13)

<img width="530" alt="_20180324221945" src="https://user-images.githubusercontent.com/33887956/37865077-382357b8-2fb2-11e8-9fcc-b6859917a60b.png">
<img width="614" alt="_20180324221725" src="https://user-images.githubusercontent.com/33887956/37865079-42069f4c-2fb2-11e8-85d0-eb731088c21c.png">

建议将视频(如01:26s处)，以及页面内容里的所有"拆封"，翻译成"解包"，也是大多数教材所普遍采用的名词

**Comment by sylviasun916** [comment]
已采纳修改，感谢反馈！
