### ISSUE TITLE
【课程内容疑问】练习：COALESCE

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#116]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/03f64082-fa4d-4aff-80be-d48597867e07/concepts/a97aeca2-634e-4dac-a5f1-2a91378797e8#

## 截图
![image](https://user-images.githubusercontent.com/11519486/38187655-2aea8762-368b-11e8-9e73-5dc0f7694994.png)

## 具体描述
1. 这里是说使用 account.id 填充那两列的 NULL 值，而不是将那两列填充为 NULL 值，首先翻译错了。
2. 英文版本上的第二条是 使用 `account.id` 填充 `accounts.id` 一个加了 s 一个没加 s，但是解决方案中是：`COALESCE(a.id, a.id)`，貌似第一个参数与第二个参数一样？

这里是刚刚一对一的同学提出的疑问，麻烦尽快解答一下 @Kyliewang

**Comment by Kyliewang** [comment]
已经修改~ 

数据中似乎没有account这个table，根据解决方案来看，可能是笔误。
