### ISSUE TITLE
数据分析-入门-统计学-课程13:案例研究：AB测试-练习10:注册率

### ISSUE THREAD

**Issue by EasonYau** [udacity/DAND-CN-feedback#117]
## 入门-课程13:案例研究：AB测试- [练习10:注册率](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/f3088061-6562-445e-b1a7-a86c9389c2b5/concepts/71e522cd-d538-417a-bfa3-3c19cbb488eb)
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

### 英文答案
<img width="863" alt="ying" src="https://user-images.githubusercontent.com/26672471/38198653-4d83c7a4-36c0-11e8-8f37-6a05587f148a.png">

### 中文答案
<img width="899" alt="zhognwen" src="https://user-images.githubusercontent.com/26672471/38198675-5af5a614-36c0-11e8-9c97-8ac3ed84e68f.png">

## 具体描述

这里英文和中文界面的答案不同，特别是P值。我看了下这里不同的原因是中英文用的注册率的公式稍有不同。中文这里每个个体（id）只计算一次，但是英文是每个个体（id）可以计算多次。这里应该遵从哪个公式。

**Comment by Kyliewang** [comment]
@EasonYau 

中英文workspace中的代码都是`control_ctr = control_df.query('action == "enroll"').id.nunique() / control_df.query('action == "view"').id.nunique()`，我觉得中文下的答案应该正确？
