### ISSUE TITLE
数据分析入门-统计学-案例研究 A/B test

### ISSUE THREAD

**Issue by EasonYau** [udacity/DAND-CN-feedback#119]
## 截图
<img width="840" alt="default" src="https://user-images.githubusercontent.com/26672471/38284997-aa13914e-37f0-11e8-93d0-4769efe042d0.png">

<img width="561" alt="default" src="https://user-images.githubusercontent.com/26672471/38285003-b035d83e-37f0-11e8-9f93-69cb7fe63bec.png">

## 具体描述
这题正确答案显示的P值是0.0363。但是我计算出来的是0.0845。然后我切换到英文版看了下，发现英文版答案和我计算出来的一样（0.08），所以可能中文版答案错了。

**Comment by ZenRay** [comment]
你发的两个 issue(#117 ) 都和学院正在用的课程不同（已经和学员求证过了）。但是这两个问题中确实存在因为中英文差异下，选项不一致。 @Kyliewang

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！ @EasonYau
