### ISSUE TITLE
数据分析入门-统计学-案例分析 A/B Test- 第7课 指标：点击率-翻译问题

### ISSUE THREAD

**Issue by EasonYau** [udacity/DAND-CN-feedback#120]
## 课程导航+地址
例子：入门 > 统计学 > 案例分析 A/B Test > [1. 指标：点击率](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/f3088061-6562-445e-b1a7-a86c9389c2b5/concepts/0fc48912-c4a4-498a-9217-b44330857e52)

## 截图
<img width="941" alt="p" src="https://user-images.githubusercontent.com/26672471/38285267-ffd0dbae-37f1-11e8-9696-82c37aac5814.png">

<img width="279" alt="0 005" src="https://user-images.githubusercontent.com/26672471/38285270-02bac85c-37f2-11e8-88af-66e598935df2.png">

<img width="279" alt="0 005" src="https://user-images.githubusercontent.com/26672471/38285306-33d4c532-37f2-11e8-953c-ec790ff4ed21.png">

## 具体描述
视频中将 With a p-value of approximately a half of percent. 翻译成立利用P值的一半感觉有点难以理解，这里结合P值的数值（0.0053），把此话改成 得到的P值为百分之一的一半（或百分之0.5）更加合理。

**Comment by Kyliewang** [comment]
@sylviasun916 字幕问题，麻烦圆圆看下~

**Comment by sylviasun916** [comment]
已修改 在部署中 谢谢反馈！
