### ISSUE TITLE
【Python 入门】【课程内容】【代码运行报错】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#121]
## 课程导航+地址
例子：入门 > Python 入门 > 课程5. 脚本编写 > [8. 在脚本中接受原始输入](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/622bcf85-e02b-4ed1-a6b1-bc6629c8fcf7)

## 截图
![tim 20180406214731](https://user-images.githubusercontent.com/11519486/38424606-2de712c6-39e4-11e8-91e3-aa966c979847.png)

## 具体描述
@Kyliewang @ChengGoooo 
这部分代码少了最后的一个闭合括号，导致直接复制代码运行报错。
```
  File "test.py", line 3

                                                 ^
SyntaxError: unexpected EOF while parsing
```
![tim 20180406200854](https://user-images.githubusercontent.com/11519486/38420465-602d229c-39d6-11e8-85ad-7cfb0151d59c.png)

**Comment by Kyliewang** [comment]
已经修改，感谢 @ivylee0919 提供的反馈！
