### ISSUE TITLE
【数据分析入门】【课程内容】【workshop 不对应】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#122]
## 课程导航+地址
例子：入门 > 数据分析入门 > 数据分析过程-案例研究 1 > [19. 使用 Matplotlib 绘图](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/77286f5a-b206-4807-aaa0-7ecfc690268e/concepts/988ab8a2-dd75-4b53-b1a4-628ff331f461#)

## 截图
![tim 20180406203141](https://user-images.githubusercontent.com/11519486/38421536-0b38512c-39da-11e8-9056-fdd3bc11ed41.png)
![tim 20180406203513](https://user-images.githubusercontent.com/11519486/38421540-0e45dc40-39da-11e8-9352-199adf5b24e6.png)

## 具体描述
今天一对一同学反馈，我也在课程页面重置所有 workshop 后实验了一下：
19. 课的 workshop 与前面几个练习不在一起，导致使用不了前面保存的 `winequality_edited.csv` 文件。
@Kyliewang

**Comment by Kyliewang** [comment]
Workspace是不相连接的，如果需要用到之前的数据，需要点击左上角的jupyter将数据下载之后，再upload到另一个workspace。

已经在教室中增加提示。
