### ISSUE TITLE
【Python 入门】【课程内容】

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#123]
## 课程导航+地址
例子：入门 > Python 入门 > 课程5. 脚本编写 > [3. 定义函数](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/d91fa76c-cfb4-40b5-8aec-40d5b25a1e58/concepts/3487f6f7-ff59-40cf-8746-106c6bdca7a5)

## 截图
![tim 20180406212420](https://user-images.githubusercontent.com/11519486/38423608-01849224-39e1-11e8-8dbd-65625d93f544.png)

## 具体描述
练习：readable_timedelta
直接复制答案，提交也提示错误，实际运行结果与提示的预期答案一致。
@Kyliewang @ChengGoooo

**Comment by ivylee0919** [comment]
@Kyliewang 抱歉写错了课程名。。
这里是因为要加一个句号？那么练习问题描述里面的示例也应该加上句号：
![image](https://user-images.githubusercontent.com/11519486/38450899-7be2d8b0-3a58-11e8-85f5-e78d5d021cd1.png)

**Comment by Kyliewang** [comment]
@ivylee0919 已经修改，感谢！
