### ISSUE TITLE
[数据分析入门]欢迎加入数据分析-数据分析师的生活

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#124]
### 2.Facebook 的数据科学家
[课程小节链接](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/4c399c8e-6d19-48c1-88c8-af3ee3f6d541/lessons/09be69fe-ce7f-43ee-ac3a-d1780eb16bc6/concepts/8de80327-cd35-4132-b2cb-77ec75c42ce1)
2 分 32 秒，“ these were done in ggplot"——这些是在 ggplot 中做出

**建议翻译**：这些是使用 ggplot 做出

2 分 38 秒，” and grouping by the particular meme variant and then rescaling the ax, the y-axis to log  in one of the versions"——并按特定的模因变体分组，然后在其中一个版本中将 y 轴标尺改成对数

**建议翻译**：并按特定的模因变量分组，之后在其中一个版本中对 y 轴标尺进行对数方式缩放。
**英文字幕错误**："the ax" ，应为 "the axis"

### 4.萨米特学校的数据分析经理
[课程小节链接](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/4c399c8e-6d19-48c1-88c8-af3ee3f6d541/lessons/09be69fe-ce7f-43ee-ac3a-d1780eb16bc6/concepts/8d1f75c7-f3c1-4563-af90-fd6a15573e52)
58 秒 "actually building tools for school leaders and teachers in tableau"——在 tableau 里为学校领导和老师开发工具

**建议翻译**：使用 tableau 作为学校领导和老师的开发工具

1 分 46 秒 "so, I think dealing with ambiguity is going to be a key part of any data analyst role"——所以我觉得这种不确定性是任何数据分析人员工作的关键所在

**建议翻译**：所以，我认为处理不确定性是任何数据分析人员的工作关键

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
