### ISSUE TITLE
[数据分析入门] 课程3  你的第一个项目-翻译

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#125]
## 课程导航+地址
入门>课程3:项目准备：SQL 和移动平均值>字幕翻译> [1.你的第一个项目](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/c9308080-537f-45e8-bc40-8d6dbc10ed5c)

## 截图

![](https://user-images.githubusercontent.com/24636410/38464262-1b61b80e-3b3d-11e8-9398-d3532a108675.png)

## 具体描述
视频32s处字幕——“compare the temperature trends where you live to overall gloabal temperature trends”——并将你居住的温度趋势与全球总体温度趋势进行对比
**建议改为**：并将你居住地的温度趋势和全球总体温度趋势进行对比

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
