### ISSUE TITLE
[数据分析入门] 课程4 .视频 + 文本：Parch & Posey 数据库-翻译

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#126]
## 课程导航+地址
入门>课程3:项目准备：SQL 和移动平均值>字幕翻译> [4 .视频 + 文本：Parch & Posey 数据库](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/63924491-9491-4fb8-b39b-611a613c25fd)

## 截图
![_20180411200425](https://user-images.githubusercontent.com/24636410/38615537-9acf0dde-3dc3-11e8-810a-16f407ff6189.png)

## 具体描述
视频 41s 处字幕 “or it can query across multiple tables”——也可以查询若干表

**建议修改** 为：也可以通过多表查询

**Comment by nicoleliu42** [comment]
感谢反馈！经过评估 我们觉得这里的翻译是没有问题的哦！
