### ISSUE TITLE
[数据分析入门] 课程4 .视频 + 文本：Parch & Posey 数据库-instruct note

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#127]
## 课程导航+地址
入门>课程3:项目准备：SQL 和移动平均值>字幕翻译> [4 .视频 + 文本：Parch & Posey 数据库](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/63924491-9491-4fb8-b39b-611a613c25fd)

## 截图
![_20180411195007](https://user-images.githubusercontent.com/24636410/38615697-2a2e7622-3dc4-11e8-9a27-a4808e12540e.png)

## 具体描述
课程 note 中：将这些表格连接在一起的 "crow's foot" 表示法显示了一个表中的列与另一个表中的列之间的关联。在第一课中，你将学习使用 SQL 与单个表进行交互的基础知识。在下一节课中，你将进一步了解这些连接对于使用 SQL 和关系数据库的重要性。

**建议：** 方便对 `ERD` 关系的理解，建议增加对 'crow's foot' 的解释链接

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
