### ISSUE TITLE
【入门新 AB 项目】 ipynb 文件翻译改进

### ISSUE THREAD

**Issue by andy1li** [udacity/DAND-CN-feedback#128]
定位：

第 II 部分 k. 用文字解释一下你刚才在 j.中计算出来的结果。在科学研究中，这个值是什么？ 这个值在新旧页面中是否有区别呢？

---

这个值在新旧页面中是否有区别呢？

建议修改成：

根据这个数值，新旧页面的转化率是否有区别呢？

**Comment by ZenRay** [comment]
hi，没找到课程地址 @andy1li

**Comment by andy1li** [comment]
@ZenRay 

哦哦，是新 AB 课程的项目文件。

页面链接：https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/741b37dc-a071-4b47-b925-314943dcb3c2/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/project

页面其中：
`中文版Notebook可以通过“这里”下载。（右键->另存为）`

“这里” 的 ipynb 文件链接：https://s3.amazonaws.com/video.udacity-data.com/topher/2018/March/5abcb668_analyze-ab-test-results-notebook-zh-0/analyze-ab-test-results-notebook-zh-0.ipynb

另外一个 “缺失内容” 的 issue 也是同一个 ipynb 文件。

**Comment by ZenRay** [comment]
嗯，找到了

**Comment by nicoleliu42** [comment]
@sylviasun916

**Comment by Kyliewang** [comment]
已经修改，感谢大家！
