### ISSUE TITLE
数据分析(入门) - Numpy & Pandas - 第一部分 - Intro 没有翻译

### ISSUE THREAD

**Issue by hugo626** [udacity/DAND-CN-feedback#13]
## 数据分析(入门) > Numpy & Pandas - 第一部分 > [Intro](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/781830f7-1f81-4855-baca-2cf8c943ae85)
这里的Intro(介绍没有翻译)

## 截图
![intro](https://user-images.githubusercontent.com/1345356/37553508-6b13dbbe-2a19-11e8-92ea-c9d78a98a28a.PNG)

## 具体描述
介绍页完全没有被翻译.

**Comment by Kyliewang** [comment]
@sylviasun916 

https://coco.udacity.com/nanodegrees/nd002-cn-basic/locale/zh-cn/versions/4.0.0/parts/561091/modules/561644/lessons/561639/concepts/561492

内容比较少，麻烦圆圆帮忙翻译一下。
