### ISSUE TITLE
数据分析（进阶）纳米学位汉化校正 - 探索性数据分析 - 课程2，课程5

### ISSUE THREAD

**Issue by kexinlin** [udacity/DAND-CN-feedback#130]
**课程2：R基础**
10 获得帮助
视频1:20秒，原文refresh your memory的字幕被翻译为“刷新内存”，实际为“唤醒你的记忆”。

12 练习：R Markdown 文档
视频下方代码块的后一行，“文本头”的原文为headers of text，指的是文本标题。

24 练习：频率多边形
视频下方文本第二段，“在个别直方图中，线条的高度与条形的高度相同……”，其中“个别直方图”存在歧义，原文为“individual histograms”，应当翻译为“在独立的直方图汇中”。
另外这一段翻译了两遍，再次出现在了倒数第二段。

**课程5：探索两个变量**
9 练习：条件均值
视频字幕1:02处，“deplier”应为“dplyr”。

22 练习：了解噪声：年龄到月龄
第二段的“数据框 pf 中的变量 age_with_months 应为一个十进制值”，其中“十进制值”的原文为“decimal value”，此处指的是小数值，非十进制值。

23 练习：带有月均值的年龄
视频第02:19处，“so I’m just writing it over”翻译成了“所以我把它写下来”，实际为“所以我直接把它覆盖”。

25 平滑化条件均值
视频02:59处，字幕的“这凸显了使用低S……”其中中文和英文字幕中的“低S”/“low S”应为“LOESS”。

**Comment by ZenRay** [comment]
“header of text” ，应该用文本头是可以的——因为 `#` 的一个重要作用是用作主题句 ，不仅仅是作为最开始的一个文本标题。

其他是翻译问题， @sylviasun916

**Comment by kexinlin** [comment]
个人觉得由于“文本头”这个词不是属于普遍认知上的专业用语，而#对应一级标题，######对应六级标题，因此header of text翻译为文本标题更易于理解。

**Comment by ZenRay** [comment]
@kexinlin ，从中文长久以来的翻译习惯来看，确实如你所说—— `header` 被翻译为了 `标题`（参考[块级元素 - Markdown 中文文档](https://markdown-zh.readthedocs.io/en/latest/blockelements/#header)），这点来说还是可以接受。

英文下面没有找到可以对应可以理解为 `title` 的意思（另一个翻译还比较有意思——翻译为 `页眉`，但有又感觉不符合实际情况了）——参考[Daring Fireball: Markdown Syntax Documentation](https://daringfireball.net/projects/markdown/syntax#header)

**Comment by kexinlin** [comment]
@ZenRay 多谢回复，因为我一直以来只将#应用于markdown的标题部分，所以仅从个人角度来看将“header”被翻译为“标题”不存在太大问题。想请问下将#用作主题句具体指的是哪种运用？

**Comment by ZenRay** [comment]
@kexinlin ，这个有个人想法之嫌。思路是：在写文章的时候，每个做的一个提纲，在提纲下面展开表述。而这个提纲就类似你要表达的主要点。类似的就是议论文下的论点了吧！

实际使用 `markdown` 情况中，在使用 `#` 的时候不仅仅是在做在开始作为 “标题” 使用，还有可能会在说明接下来的小节是针对什么主题内容在讨论——这理的主题就是一个总结。可能和个人使用习惯有关了。

**Comment by kexinlin** [comment]
@ZenRay 多谢回复。在个人的markdown使用经历中，对于提纲或总结一般会直接使用`**`或`*`进行粗体/斜体的突出显示，不太会去使用`#`符号进行强调，主要是由于在先前学习markdown的过程中一直将`#`视为对应“X级标题”的符号。
也正因如此，个人角度看来将“header”翻译为“标题”不存在准确性问题，且相对于“文本头”这样一个没有经过普遍运用的非专业性词汇要容易理解得多。

**Comment by ZenRay** [comment]
使用 `#` 来做小节主题（包括使用 `##`、`###`等），有个好处就是在文本开头加一个 `[toc]` 标签，可以自动生成一个目录列表。

![result](https://user-images.githubusercontent.com/24636410/38775863-713a601e-40bf-11e8-81c7-0c15e33a8584.png)

**Comment by ZenRay** [comment]
嗯，可以的

**Comment by nicoleliu42** [comment]
感谢反馈！翻译错误已核实修改
