### ISSUE TITLE
数据分析入门-课程13 案例分析A/B Test-13.指标完成率

### ISSUE THREAD

**Issue by EasonYau** [udacity/DAND-CN-feedback#132]
## 截图
<img width="952" alt="p" src="https://user-images.githubusercontent.com/26672471/38774773-6f19a65e-40a2-11e8-8dd2-50ba67ddc64b.png">

## 具体描述

这里中文答案为 能，但是根据上面练习出来的结果(0.08)，应该把答案改为不能更加合适。

**Comment by ZenRay** [comment]
中文环境下确实是错误的，但是英文环境下是正确的。@Kyliewang

**Comment by Kyliewang** [comment]
感谢！修改完毕~
