### ISSUE TITLE
数据分析进阶-欢迎加入数据分析(进阶求职)-统计学和编程练习-管理风格对员工速度的影响

### ISSUE THREAD

**Issue by EasonYau** [udacity/DAND-CN-feedback#133]
## 截图

<img width="883" alt="wx20180415-115903 2x" src="https://user-images.githubusercontent.com/26672471/38774877-6adfc72e-40a4-11e8-8814-d9e99bb19ebb.png">

<img width="870" alt="default" src="https://user-images.githubusercontent.com/26672471/38774830-aabd9598-40a3-11e8-8819-1d84b6f3e408.png">

## 具体描述

练习上方要求我们计算双尾不等方差 t-test，但是到了问题却问的是双尾等方差 t-test的 p 值是多少。

但其实正确答案0.0231仍然计算的是不等方差。所以应该把问题描述从双尾等方差 t-test改成双尾不等方差 t-test

**Comment by Kyliewang** [comment]
@EasonYau 这个题目的正确答案应该是-2.5570，题目中给出的提示是：
![screen shot 2018-04-23 at 3 58 03 pm](https://user-images.githubusercontent.com/35555101/39113728-2e6e0816-470f-11e8-84c6-530f16a8eb92.png)
是否应该修改为“等方差”？
