### ISSUE TITLE
【入门新 AB 项目】 ipynb 文件翻译改进（二）

### ISSUE THREAD

**Issue by andy1li** [udacity/DAND-CN-feedback#134]
定位：

第 II 部分 n. 在上一个问题中计算出的z-分和p-值是否意味着新旧页面的转化率？它们与 j. 与 k. 中的结果一致吗？

---

在上一个问题中计算出的z-分和p-值是否意味着新旧页面的转化率？

建议修改成：

根据上题算出的 z-score 和 p-value，我们认为新旧页面的转化率是否有区别？

**Comment by Kyliewang** [comment]
已经修改，感谢安总！
