### ISSUE TITLE
数据分析（入门）字幕报错

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#135]
## 课程导航+地址

数据分析（入门）课程4>函数>5变量作用域
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/d91fa76c-cfb4-40b5-8aec-40d5b25a1e58/concepts/98b7dee3-4ce8-4d6b-8950-55d23a3e3241
## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频0：22处字幕“数出文档中的字数”，需改为“输出文档中的字数”

**Comment by ZenRay** [comment]
<img width="600" alt="course" src="https://user-images.githubusercontent.com/24636410/38919206-87f33ab4-4322-11e8-9f95-1f06870b2d8e.png">
这里用 `数出文档中的字数` 是正确的，这里的意思是在第一个函数中利用循环以及 `answer` 累加计数。
