### ISSUE TITLE
[数据分析进阶]机器学习 文本学习中练习 19 指导文件和代码匹配

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#136]
## 课程导航+地址
进阶 > 机器学习 > 课程 11 文本学习 > [19. 清除“签名文字”](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/d995b830-1e87-48a4-9676-91750acb503e/modules/bac5aff1-8cf8-4419-82ed-55915eaae14d/lessons/2892378590/concepts/30112386710923)

## 截图
<img width="700" alt="course" src="https://user-images.githubusercontent.com/24636410/39044045-9e70be6a-44c1-11e8-8181-3531079a6966.png">

## 具体描述
同学反馈——题目中说是先提取前 200 封邮件，但是这部分循环代码中，只读取了前 199 封邮件。另外在 `vectorize_text.py` 代码中也有相同的问题，代码如下：

```
for name, from_person in [("sara", from_sara), ("chris", from_chris)]:
    for path in from_person:
        ### only look at first 200 emails when developing
        ### once everything is working, remove this line to run over full dataset
        temp_counter += 1
        if temp_counter < 200:
            path = os.path.join('..', path[:-1])
            print path
            email = open(path, "r")
```

**问题：** 代码 44 -45 行中， `temp_counter` 是先进行了加 `1`，再进行判断。所以导致了该错误。

**Comment by Kyliewang** [comment]
老版习题，无法进行修改，暂时搁置。
