### ISSUE TITLE
[数据分析入门] 课程3 中 16.视频：ORDER BY [课程内容]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#137]
## 课程导航+地址
入门>课程3:项目准备：SQL 和移动平均值>课程内容> [16.视频：ORDER BY](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/ef98495e-88e9-4938-8f60-14be1b099e3c)

## 截图

![order_by](https://user-images.githubusercontent.com/24636410/39109146-2c506ef4-46fe-11e8-9986-a5585252a4bd.png)

## 具体描述
课程字幕和导师讲解都是使用的是——显示最新的 10 个订单。但是查询语句是使用的 `LIMIT 1000`
所以应该是——显示最新的 1000 个订单。

**Comment by Kyliewang** [comment]
感谢反馈~ 已经修改
