### ISSUE TITLE
[数据分析入门] 课程3 中 29练习：算术运算符-第二个问题使用 where 排除分母为 0

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#138]
## 课程导航+地址
入门>课程3:项目准备：SQL 和移动平均值>练习内容> [29练习：算术运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/07dc6709-953d-41c2-98d2-f630044c0767)

## 具体描述
在 30 节提供的参考方式为:
```
SELECT id, account_id,
poster_amt_usd/(standard_amt_usd + gloss_amt_usd + poster_amt_usd) AS post_per
FROM orders;
```
通过计算发现求和项 `(standard_amt_usd + gloss_amt_usd + poster_amt_usd) ` 和 `total_amt_usd` 是完全相同的，所以可以直接使用 `total_amt_usd` 来做分母项。另外对于分母有 0，是否可以直接使用 where 来排除呢，因为实际上订单没有实际贡献。

**Comment by Kyliewang** [comment]
解决问题的思路通常不是只有一种，使用其他的方式没有问题。
