### ISSUE TITLE
[ 提交答案返回的信息没有翻译] 数据分析(入门) - Numpy & Pandas - 第一部分 - 练习Gapminder数据,

### ISSUE THREAD

**Issue by hugo626** [udacity/DAND-CN-feedback#14]
数据分析(入门) - Numpy & Pandas - 第一部分 - [练习Gapminder数据](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490040923), 提交答案返回的信息没有翻译.
### 当选择已经提交了答案选项后,点击提交答案按钮
![gapminder](https://user-images.githubusercontent.com/1345356/37553555-71275804-2a1a-11e8-9c4d-e25ff585e62a.PNG)
### 当没有选择已经提交了答案选项后,点击提交答案按钮
![gapminder 2](https://user-images.githubusercontent.com/1345356/37553568-c89bcf7a-2a1a-11e8-9de7-b126bc897750.PNG)

## 具体描述
点击提交答案后, 返回的对话框中信息没有翻译.

## 同样的问题存在于一下章节中:
1. [6.练习 向量化运算]
2. [7.练习 乘以标量]
3. [15. 练习 向量化运算和 Series 索引]
4. [18.练习 在 Pandas 中绘图]

**Comment by Kyliewang** [comment]
@sylviasun916 

有几个concept都有这样的问题，麻烦圆圆关注一下。

这是练习gapminder数据集的coco链接：
https://coco.udacity.com/nanodegrees/nd002-cn-basic/locale/zh-cn/versions/4.0.0/parts/561091/modules/561644/lessons/561639/concepts/176501

**Comment by sylviasun916** [comment]
@Kyliewang  我排查来一下这几个页面 没地方找到这些内容 技术上不能提供汉化啊
@ChengGoooo  谷诚 你有什么看法？
