### ISSUE TITLE
概念解释不清晰

### ISSUE THREAD

**Issue by AAAlvin** [udacity/DAND-CN-feedback#141]
## 截图
![image](https://user-images.githubusercontent.com/36393256/39507621-59263430-4e11-11e8-9aee-a4d6410f6d4e.png)

## 具体描述
这个0.1+0.1+0.1！=0.3解释的稍微有点不清晰，担心小白可能有点混淆，我找到一个解释比较清晰的网站：https://www.cnblogs.com/mooncher/p/5145571.html
大致解释是这样：对于十进制数值系统（就是我们现实中使用的），它只能表示以进制数的质因子为分母的分数。10 的质因子有 2 和 5。因此 1/2、1/4、1/5、1/8和 1/10 都可以精确表示，因为这些分母只使用了10的质因子。相反，1/3、1/6 和 1/7 都是循环小数，因为它们的分母使用了质因子 3 或者 7。二进制下（进制数为2），只有一个质因子，即2。因此你只能精确表示分母质因子是2的分数。二进制中，1/2、1/4 和 1/8 都可以被精确表示。但是，1/5 或者 1/10 就变成了循环小数。所以，在十进制中能够精确表示的 0.1 与 0.2（1/10 与 1/5），到了计算机所使用的二进制数值系统中，就变成了循环小数。当你对这些循环小数进行数学运算时，并将二进制数据转换成人类可读的十进制数据时，会 对小数尾部进行截断处理。
稍微有点长，但是可能清晰一点，可以参考参考

**Comment by Kyliewang** [comment]
下面已经给出了英文参考资料了，我把这个中文博客链接也放进去了。
