### ISSUE TITLE
翻译不恰当

### ISSUE THREAD

**Issue by AAAlvin** [udacity/DAND-CN-feedback#142]
## 截图
![image](https://user-images.githubusercontent.com/36393256/39507757-11633a52-4e12-11e8-889f-76814d36a552.png)
![image](https://user-images.githubusercontent.com/36393256/39507776-247373dc-4e12-11e8-9c71-27a3768e4438.png)

## 具体描述
1.新的字符串方法？是想说连接字符串的方法么
2.追加到列表？是想说往列表里添加元素么

**Comment by Kyliewang** [comment]
1. 新的字符串方法：这个翻译我认为没有问题，字符串方法是用于字符串的Method。这里介绍了一种新的字符串方法，也就是Join。
2. 追加到列表：修改为“给列表添加元素”。
