### ISSUE TITLE
概念有点奇怪

### ISSUE THREAD

**Issue by AAAlvin** [udacity/DAND-CN-feedback#143]
## 截图
![image](https://user-images.githubusercontent.com/36393256/39507877-9afb0344-4e12-11e8-8688-affa2e372e88.png)

## 具体描述
（3）中货号内的文字应该移到（2）中‘函数名称‘之后会好点。

## 截图
![image](https://user-images.githubusercontent.com/36393256/39507922-df98df58-4e12-11e8-80de-31e8f110b825.png)
## 具体描述
之前好像并没有提到starbox函数，链接也失效了

**Comment by Kyliewang** [comment]
已经修改~ 感谢反馈！
