### ISSUE TITLE
【五王之战】【项目文件】二进制变量应该是二元变量

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#144]
## 课程导航+地址
[五王之战分析 - 冰与火之歌 Workshop](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/8ee64939-8c6b-408c-8acb-fe41208e57a0/modules/a64fe97f-d6e3-4368-b73d-d99b7413b38e/lessons/5456cb08-7913-4e78-9dff-614f239bfe13/concepts/955dc484-8aab-4f0f-8ff4-d9b76c8b8d36)

## 截图
![image](https://user-images.githubusercontent.com/11519486/39510926-180a2d46-4e1e-11e8-8d47-fa6090df7e56.png)

## 具体描述
二进制变量应该改为二元变量 @Kyliewang

**Comment by Kyliewang** [comment]
已经修改~
