### ISSUE TITLE
翻译不恰当

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#145]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1fqxz6ru1mzj227e0yetib.jpg">

## 具体描述
正文第一行“整型变量 ```month```”，需改为"整数型变量 ```month```"

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错误已经修正啦！

**Comment by ZenRay** [comment]
如果要更改的话，后面的 `num_days` 之前的“整型变量”也应该更改为“整数型变量”。目前为止后面未更改。

对这个更改有些疑问，很多时表述上还是在用整型数据来表述整数型数据。@nicoleliu42

**Comment by nicoleliu42** [comment]
已经和CM确认过 这里是是“整型变量” 不必修改 感谢反馈！ @ZenRay
