### ISSUE TITLE
探索数据集项目文件翻译

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#146]
## 课程导航+地址
例子：入门 >数据分析入门 > 探索数据集 > [3. 实战项目](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/bce8d241-89f4-422e-abda-c5a4e5ceb8fe/lessons/e6fe760d-c9ef-437d-9b97-b313458821e6/concepts/642ab657-197e-4beb-afd6-4494e6da490b)

## 截图
![8da01c9c65126ce54f679e69a8d666d](https://user-images.githubusercontent.com/11519486/39563599-72e3d1d4-4ee3-11e8-89f2-0d30819c93c4.png)

## 具体描述
注释的换行不用一定与英文一致，比如第一句话，没必要换行
第二句话里面的 Remember to include a 'magic word' so that your visualizations are plotted inline with the notebook. 翻译有误，inline with the notebook 并不是保持一致的意思，是将 matplotlib 画出的图直接显示在 Notebook 之中。 @Kyliewang 

这个模板文件貌似没有校对过，建议进行一下仔细的校对。
比如标题应该是 探索数据集 而不是 调查数据集。

**Comment by Kyliewang** [comment]
上面提到的两个问题已经修改。

**Comment by nicoleliu42** [comment]
感谢 Kylie @Kyliewang ！
