### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#147]
进阶7天试学班 > 课程1 > 数据分析过程 > [6. 数据分析过程练习](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/8ee64939-8c6b-408c-8acb-fe41208e57a0/modules/174383f9-5d05-4372-9a8d-6ae25c683fe7/lessons/de8cddfa-691b-4cc5-bcdc-e7a5d943d81c/concepts/8997910f-5a0b-4416-bfdc-0b01a3d92d5a)

<img width="473" alt="_20180503161022" src="https://user-images.githubusercontent.com/33887956/39565981-93488538-4eec-11e8-8be0-b40bb58fdd7e.png">

第3和第4行挤在了一起，建议调整排版

**Comment by Kyliewang** [comment]
已经修改，感谢！
