### ISSUE TITLE
笔误问题

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#148]
进阶7天试学班 > 课程1 > 数据分析过程 > [13. 阅读csv文件](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/8ee64939-8c6b-408c-8acb-fe41208e57a0/modules/174383f9-5d05-4372-9a8d-6ae25c683fe7/lessons/de8cddfa-691b-4cc5-bcdc-e7a5d943d81c/concepts/de10746b-91f3-4449-995e-91532160eb1c#)

![_20180503161930](https://user-images.githubusercontent.com/33887956/39566329-ccd9faec-4eed-11e8-9d2e-3e65bdf4496c.jpg)

笔误，建议将cvs改为csv文件

**Comment by nicoleliu42** [comment]
感谢反馈~！这里的错误已经修正啦 请你重置 workspace 哦
