### ISSUE TITLE
[数据分析入门] Python 入门 课程2 中 17.列表和成员运算符  演示代码错误

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#151]
## 课程导航+地址
入门> Python 入门>课程2:数据类型和运算符>代码错误> [17.列表和成员运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/ef98495e-88e9-4938-8f60-14be1b099e3c)

## 具体描述
主题 **在列表里还是不在列表里？** 中演示代码存在错误，在测试 `in` 中第二条代码中 `in` 之后使用了反引号，导致测试失败：

原代码为：
```
'in` in 'this is a string'
```
实际应该为:

```
'in' in 'this is a string'
```

**Comment by Kyliewang** [comment]
非常细心，感谢反馈！
