### ISSUE TITLE
【翻译问题】【缺少材料】数据分析入门-案例研究2

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#152]
## 课程导航+地址
例子：入门 > 数据分析入门 > 案例研究2 > [13. 结论和可视展示](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/f81a3576-0665-4721-a8bb-ba50c80c04ac/concepts/e5e683c5-33c5-4fb8-b4f6-55e525a4b9cf)

## 截图
![image](https://user-images.githubusercontent.com/11519486/39610505-65986562-4f83-11e8-95fc-b27158504d57.png)
![image](https://user-images.githubusercontent.com/11519486/39610507-6cb7340e-4f83-11e8-82ff-d8fce0f701cd.png)

英文版：
![image](https://user-images.githubusercontent.com/11519486/39610512-7b25e5bc-4f83-11e8-9780-73f8c280e433.png)
![image](https://user-images.githubusercontent.com/11519486/39610537-a9f51796-4f83-11e8-991c-c9d7af5ac9eb.png)

## 具体描述
@Kyliewang 
翻译有一些问题，同学理解起来很困难。
英文版提供了解决方案的材料，中文版没有。

具体翻译建议：
Q1: Are more unique models using alternative fuels in 2018 compared to 2008? By how much?
问题 1：与2008年相比，2018年是否有更多的车型（去重后）使用替代能源？比例增长了多少？
Q2: How much have vehicle classes improved in fuel economy (increased in mpg)?
问题 2：各车辆类别（veh_class）在燃料经济性方面的改进（mpg 的增长）是多少？
Q3: What are the characteristics of SmartWay vehicles? Have they changed over time? (mpg, greenhouse gas)
问题 3：SmartWay 车辆的特点是什么？它们是否随时间推移发生了改变？（mpg，greenhouse gas 等方面）
Q4: What features are associated with better fuel economy (mpg)?
问题 4：哪些特征与更好的燃料经济性 (mpg) 相关联？
Q5: For all of the models that were produced in 2008 that are still being produced in 2018, how much has the mpg improved and which vehicle improved the most?
问题 5：对于 2008 年生产且 2018 年仍在生产中的车型，mpg 有多少改进，哪些车辆的改进最多？
This is a question regarding models that were updated since 2008 and still being produced in 2018. In order to do this, we need a way to compare models that exist in both datasets. To do this, let's first learn about merges.
这个问题是关于 2008 年以来不断更新换代且 2018 年仍在生产的车型。要回答此问题，我们需要找到两个数据集中都存在的车型，那么先让我们来了解如何将两个数据集合并。

**Comment by nicoleliu42** [comment]
翻译问题已经解决啦 辅助材料的问题麻烦 @Kyliewang 看一下哦！感谢反馈！

**Comment by Kyliewang** [comment]
辅助材料已经补充，谢谢反馈！
