### ISSUE TITLE
【翻译问题】数据分析入门 workshop notebook 中的翻译

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#153]
## 课程导航+地址
例子：入门 > 数据分析入门 > 数据分析过程-案例研究1 > [15. 使用 Query 得出结论](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/77286f5a-b206-4807-aaa0-7ecfc690268e/concepts/ee1c016e-b972-4a67-8706-964bc35b4a5e)

## 截图
![image](https://user-images.githubusercontent.com/11519486/39620904-6d950086-4fbf-11e8-98fa-291c5152db91.png)
![image](https://user-images.githubusercontent.com/11519486/39620936-87e194ea-4fbf-11e8-88a8-31f91e663015.png)

## 具体描述
后面两个 median 翻译成了平均值，应该是中位数 @nicoleliu42

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
