### ISSUE TITLE
[数据分析入门][解释不准确] Python 入门 课程4 函数 7.解决方案：变量作用域

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#154]
## 课程导航+地址
入门> Python 入门>课程4 函数>解释不准确> [7.解决方案：变量作用域](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/d91fa76c-cfb4-40b5-8aec-40d5b25a1e58/concepts/92cc15be-1b0d-4266-9b26-4cec6aa91f93)

## 具体描述
答案解释最后一段中：`在上个视频中，你发现在函数内，我们可以成功地输出外部变量的值。因为我们只是访问该变量的值。当我们尝试将此变量的值更改或重新赋值为另一个值时，我们将遇到错误。Python 不允许函数修改不在函数作用域内的变量。`

英文下面也是同样问题：`In the last video, you saw that within a function, we can print a global variable's value successfully without an error. This worked because we were simply accessing the value of the variable. When we try to change or reassign this global variable, however, we will get an error. Python doesn't allow functions to modify variables that aren't in the function's scope.`

关于`Python 不允许函数修改不在函数作用域内的变量`——这里存在一个问题，对于某些数据类型是可以进行变量值更改的。例子如下：

```{Python}
# python 3.x
test = []

def change_test():
      test.append(1)

change_test()
print(test)
# output
[1]

# 同样可以更改列表中的数值

test = [1, 2, 3]

def change_test2():
      test[0] = 4

change_test2()
print(test)
# output
[4, 2, 3]
```

**Comment by Kyliewang** [comment]
已经修改~ 谢谢反馈！
