### ISSUE TITLE
【已经修改可以关闭】中英文内容不对应

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#155]
## 课程导航+地址
例子：入门 > Python 入门 > 探索美国共享单车数据 > [3. 实战项目概览](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/a96f4a68-d77d-425d-b69f-93aa1c355b57/lessons/e5bef1dd-5031-45c3-aaf7-8536f6f3cf8a/concepts/e32ff3f7-8031-400c-a3d2-0fbb05b061ef)

## 截图
![tim 20180508092546](https://user-images.githubusercontent.com/11519486/39732893-7c8060d2-52a2-11e8-95d7-4c5232dc6526.png)

## 具体描述
中文与英文不对应，中文是现在项目要求的内容，英文是视频中演示的内容，貌似是上一个版本的项目 @Kyliewang

**Comment by nicoleliu42** [comment]
感谢你的反馈！已核实修改！
