### ISSUE TITLE
【翻译问题】数据清洗数据集介绍

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#156]
## 课程导航+地址
例子：进阶 > 数据清洗 > 清洗与分析数据项目 > [2. 项目动机](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/6029470c-61d2-465a-a252-ce5d11b21932/lessons/a8085857-3e28-4fc7-aeb8-da64ccbc2e20/concepts/28d4643b-3785-4700-bdee-4e5fc9963576)

## 截图
![image](https://user-images.githubusercontent.com/11519486/39816226-3b86fe70-53cd-11e8-9a23-4cd56d66daa9.png)
![image](https://user-images.githubusercontent.com/11519486/39816290-623bee7c-53cd-11e8-8c10-e73155493393.png)

## 具体描述
有一些同学对这几列的真实含义产生了误解，以为这是几种不同算法的预测，还去计算那种算法预测的可信度更高。

@Kyliewang @nicoleliu42  建议翻译：

所以对于该表格中的最后一行数据来说：

- tweet_id 是推特链接的最后一部分，位于 "status/" 后面 → https://twitter.com/dog_rates/status/889531135344209921
- p1 是算法对推特中图片的一号预测 → 金毛犬
- p1_conf 是算法的一号预测的可信度 → 95%
- p1_dog 是一号预测该图片是否属于”狗“（有可能是其他物种，比如熊、马等） → 真
- p2 是算法对推特中图片预测的第二种可能性 → 拉布拉多犬
- p2_conf 是算法的二号预测的可信度 → 1%
- p2_dog 是二号预测该图片是否属于”狗“ → 真
- 依次类推……

**Comment by nicoleliu42** [comment]
感谢Ivy的反馈！这里原来的翻译的确有些让人摸不着头脑，麻烦 @Kyliewang 看一下Ivy提供的翻译是否准确，然后我去修改掉哦！

**Comment by nicoleliu42** [comment]
非常感谢Ivy的反馈！这里的翻译已经优化了哦~！
