### ISSUE TITLE
数据分析入门7天内测--实战项目小bug

### ISSUE THREAD

**Issue by wushu6336** [udacity/DAND-CN-feedback#157]
## 课程导航+地址
数据分析师（入门试学）>项目详情>项目工作区 jupyter book  “数据筛选”部分
## 截图
![1525955803 1](https://user-images.githubusercontent.com/35553899/39870468-0eae9206-5494-11e8-8b10-d1180eabbe8b.png)
![_20180510204612](https://user-images.githubusercontent.com/35553899/39870482-280e2202-5494-11e8-9bf0-7bc790b4ff51.png)

## 具体描述
第一张图中的PM_US Post，应该改成PM_US­_Post，不然后面第二张图中代码运行会出现KeyError，没办法显示箱线图

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
