### ISSUE TITLE
[数据分析入门] Python 入门 课程5 脚本编写 20.导入本地脚本

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#158]
## 课程导航+地址
入门> Python 入门>课程5 脚本编写>文本错误> [20.导入本地脚本](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/a3dc7153-8f26-4ac9-b5b5-8631600c3563)

## 截图
![report](https://user-images.githubusercontent.com/24636410/39968368-4afdc6f2-56fe-11e8-8eaf-337237f07dfd.png)

## 具体描述
文本错误，应该是使用半角的引号

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
