### ISSUE TITLE
数据分析入门强化 > 统计学 > 贝叶斯法则 > [30. 练习]翻译有误

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#159]
## 课程导航+地址
数据分析入门强化 > 统计学 > 贝叶斯法则 > [30. 练习]https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/4e7e2f82-e05e-4fbe-b29c-fe3169c6dd77/modules/0596b9e8-4a3a-41c3-a929-6c72c0c93925/lessons/9a02a699-1edb-42cf-9df4-10ec39895262/concepts/482999920923
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/37874304/40060304-dd5a3504-5888-11e8-9e90-11ca91a9dd8b.png)

## 具体描述
视频22s处字幕0。3，需改为0.3

**Comment by nicoleliu42** [comment]
感谢反馈！已修正~！
