### ISSUE TITLE
【共享单车项目】项目详情-数据集的介绍

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#16]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

## 截图
![tim 20180317172141](https://user-images.githubusercontent.com/11519486/37553680-bdd36cbe-2a07-11e8-8ccf-3df9e15a2539.png)

## 具体描述
关于数据集的介绍，应该完整保留数据集中的列名以及列中的内容示例。
建议在保留现在中文的基础上，补充原来的英文简介。

**Comment by Kyliewang** [comment]
已经修改。
