### ISSUE TITLE
练习题目错误

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#160]
##数据分析入门课程+https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/e6765bac-8bf9-428d-82e2-f3904aa67f48
例子：入门 > 第三个项目 >课程1：数据分析过程 > [14. 评估和理解](教室地址链接)

## 具体描述
联系题：’‘’
# 用索引号重复以上步骤
df_means = df.iloc[:,:11]
df_means.head()‘’‘

“[:,:11]”中的“11”应为“12”，因为”：“是包含下限，不包含上限的，而”11“位置为“mean”值。

**Comment by ZenRay** [comment]
确实是存在问题，因为包括 `mean` 的列名索引值是 `11`，使用冒号的情况下应该是使用 `12`

**Comment by Kyliewang** [comment]
已经改好了，感谢~
