### ISSUE TITLE
练习题目文字错误

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#161]
## 课程导航+地址
例子：DAND入门 > 统计学 > 2. 描述统计学-第二部分 > [5. 练习:五数概括法练习](https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/4e7e2f82-e05e-4fbe-b29c-fe3169c6dd77/modules/0596b9e8-4a3a-41c3-a929-6c72c0c93925/lessons/c5b785aa-a0e9-45ac-8c4f-6e192829babe/concepts/a1fa86ae-ada5-4f42-8828-51e4165ccb73)

## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1fregr4veshj21eq0oyad5.jpg">

## 具体描述
题干“提供以下值，第 3 四分位数的值是多少？”，需改为“提供以下值，第三四分位数的值是多少？”

**Comment by nicoleliu42** [comment]
感谢你的反馈！已经修改啦！
