### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#162]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07gy1frf2qa5ll9j21eg16ewos.jpg">

## 具体描述
下节预告 之前的 ”我们经常看到树形结构的内容，如下：“ 应删去

**Comment by nicoleliu42** [comment]
感谢你的反馈！这里的错误已经核实修改~！
