### ISSUE TITLE
[数据分析入门] 课程2 数据类型和运算符  17.  列表和成员运算符 [课程内容]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#163]
## 课程导航+地址
入门>课程2 数据类型和运算符>课程内容> [17.  列表和成员运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/15635d7c-ee7f-43c7-a91c-b35ad8066a6c)

## 截图

<img width="929" alt="report" src="https://user-images.githubusercontent.com/24636410/40275985-2487696e-5c31-11e8-9b24-ecba70948e89.png">

## 具体描述
课程内容中使用 `列表切片和切丁`，这里很容易让学员疑惑。在后续中并没有使用 `切丁` 的描述。学员对此也在提出疑问。另外英文页面也是使用 `Slice and Dice with Lists`。

**Comment by Kyliewang** [comment]
将切丁删除，感谢反馈！
