### ISSUE TITLE
字幕错误

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#164]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1fri625jprwj21g00y64iz.jpg">

## 具体描述
1:36处字幕enrollment拼写错误（少了一个 l）

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！enrolment 和 enrollment 都是没错的哦，这个词有两种写法，在字典中都可以查到！
