### ISSUE TITLE
习题文字错误

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#165]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1fribe4m8poj21fm18itgi.jpg">

## 具体描述
最后一个选项，应改为 “两次掷骰子得到相同值”

**Comment by nicoleliu42** [comment]
感谢你的反馈！这里的错误已经修正啦！
