### ISSUE TITLE
[数据分析入门] 课程2 数据类型和运算符 18. 练习：列表和成员运算符

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#167]
## 课程导航+地址
例子：入门 > Python 入门 > 数据类型和运算符 > [18. 练习：列表和成员运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/2aa94895-d620-4d00-9d91-43771844cdcf)

## 截图
![image](https://user-images.githubusercontent.com/11519486/40425794-f8ded16a-5ecb-11e8-9682-2ce141cb47d6.png)

## 具体描述
练习：列表切片，这里的中文描述写的是选择三个最近的日期，而不是选择列表中的最后三个元素。
今天有同学预约一对一表示在这里被卡住了，因为不知道如何判断日期。这位同学以为是需要写代码来判断哪个日期是最近的。
建议将题目中的中文修改为选择列表中的最后三个元素。 @Kyliewang

**Comment by Kyliewang** [comment]
感谢反馈，已经修改！
