### ISSUE TITLE
markdown 语法问题

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#169]
## 课程导航+地址
例子：入门 > 数据分析入门 > 课程3：数据分析过程 - 案例研究 2 > [4. 提问](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/f81a3576-0665-4721-a8bb-ba50c80c04ac/concepts/27792912-17a7-48b0-a87d-151509df7402)

## 截图
![_20180524205255](https://user-images.githubusercontent.com/11519486/40486620-65d5f690-5f94-11e8-9f69-20d7769025ca.png)

## 具体描述
1. 网页链接的 markdown 语法，把链接文本的 `[]` 与存放 url 的 `()` 分开了
2. 表格的语法，应该是多了个分隔符，导致内容写到了下一列中。 @Kyliewang

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
