### ISSUE TITLE
[代码中的注释没有翻译] 数据分析(入门) - Numpy & Pandas - 第一部分 -5.练习NumPy数组

### ISSUE THREAD

**Issue by hugo626** [udacity/DAND-CN-feedback#17]
## 课程导航+地址
数据分析(入门) - Numpy & Pandas - 第一部分 -[5.练习NumPy数组](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490080923), 代码中的注释没有翻译

## 截图
![numpy](https://user-images.githubusercontent.com/1345356/37553694-f1544b7a-2a1c-11e8-9b5d-c7d720978f01.PNG)

## 具体描述
代码中的注释没有翻译成中文.

## 同样有该问题的章节
1. [7.练习 计算整体完成率]
2. [9.练习 归一化数据
3. [10.练习 NumPy 索引数组]
4. [13. 练习 Pandas Series]
5. [14.练习 Series 索引]
6. [17. 练习 Pandas Series apply()]
7. [18.练习 在 Pandas 中绘图]

**Comment by Kyliewang** [comment]
@hugo626 

课堂中的quiz中的注释是基于一定的考虑没有给出中文翻译。已经补充理由。

提示：我们并没有对课堂中的quiz中的英文注释给出中文翻译。因为：

一般来说代码中的注释最好全部用英文，中国开发者也是如此。
英文是开发者必须要掌握的技能。
quiz中的注释不是很长，如果确实不能理解的话可以使用翻译软件进行查询。
