### ISSUE TITLE
文本翻译问题

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#170]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1froixnwsykj21ew0wen5f.jpg">

## 具体描述
第二段，「堆栈溢出页」需改为「Stackoverflow 帖子」

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！这里的错误已经修正啦~
