### ISSUE TITLE
文本翻译问题

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#171]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1from7tiz4qj21f20kywkn.jpg">
<img src="http://ww1.sinaimg.cn/large/6e2f3b07ly1fromdgpipyj21eo12kwm8.jpg"/>

## 具体描述
第一段文字，及最后一个习题选项中，「酒精准确性」，需改为「酒精度」

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！这里的错误已经修正啦
