### ISSUE TITLE
Jupyter NoteBook 文本翻译问题

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#172]
## 截图
<img src="http://ww1.sinaimg.cn/large/6e2f3b07ly1frot3qupl6j21f40zqn46.jpg"/>
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1froszwiauvj21f60t2q8e.jpg">

## 具体描述
图中标出的「平均值」，均需改为「 中位数」

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！这里的错误已经修正！
