### ISSUE TITLE
表格格式错误"Hwy MPG" 一行“估计的高速公路 mpg（英里/加仑）”位置错误

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#173]
## 课程导航+地址
例子：数据分析入门 > 数据分析 > 课程3：数据分析过程-案例研究2 > [4. 提问]https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/f81a3576-0665-4721-a8bb-ba50c80c04ac/concepts/27792912-17a7-48b0-a87d-151509df7402

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/40581266-0081683a-6186-11e8-877f-d74a4228efb2.png)

## 具体描述
表格格式错误"Hwy MPG" 一行“估计的高速公路 mpg（英里/加仑）”位置错误

**Comment by Kyliewang** [comment]
已经修改~ 感谢反馈！
