### ISSUE TITLE
习题文本翻译问题

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#175]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07gy1frrk43e7p1j2280182tlx.jpg">

## 具体描述
最后两个“特征”描述，应保持原文 「Sales Area」和「Cert Region」。

建议其他备选“含义”选项，给出英文原文，括号里可以跟随翻译。

**Comment by nicoleliu42** [comment]
感谢你的反馈~已修改成原文+翻译的模式！
