### ISSUE TITLE
习题文本翻译问题

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#176]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07gy1frrl15swoxj227o162gw0.jpg">

## 具体描述
练习中两个中文“特征”描述，应该为英文原文「Sales Area (2008)」和「Cert Region (2018)」

## 截图
<img src="http://ww1.sinaimg.cn/large/6e2f3b07gy1frrl66o40wj227w18c4a0.jpg"/>

## 具体描述
建议「燃料类型」的所有描述选项，都改为英文原文

**Comment by nicoleliu42** [comment]
感谢你的反馈~已修改成原文+翻译的模式！
