### ISSUE TITLE
红色标记的错别字“友联”，需改为“右联” 

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#177]
## 课程导航+地址
例子：入门 > 项目3> 课程3：数据分析过程，案例研究2 > [14.合并类型]
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/f81a3576-0665-4721-a8bb-ba50c80c04ac/concepts/ed54f015-311a-483e-9df8-89751cdece2b

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/38323732/40661539-af3b9dc6-6386-11e8-8c83-3b9d4b5bad96.png">
![image](https://user-images.githubusercontent.com/38323732/40661539-af3b9dc6-6386-11e8-8c83-3b9d4b5bad96.png)

## 具体描述
红色标记的错别字“友联”，需改为“右联”

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错别字已经修正啦！
