### ISSUE TITLE
文本翻译问题

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#179]
## 课程导航+地址
例子：入门》项目三》课程6：SQL join》11.练习 join问题https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/83da273e-73e7-48b6-a743-219de50b788f

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/38323732/40723271-16fe4d8a-6451-11e8-8bb7-204e9f2341ef.png">
![image](https://user-images.githubusercontent.com/38323732/40723271-16fe4d8a-6451-11e8-8bb7-204e9f2341ef.png)

## 具体描述
加粗的汉字翻译后，这样反而会增加不必要的难度。所以保留英文的名称较好。

**Comment by nicoleliu42** [comment]
感谢反馈！已修改为英文+翻译解释的模式！
