### ISSUE TITLE
【缺少图片】【共享单车项目】项目详情

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#18]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37553746-f4978bb2-2a08-11e8-983d-f1b9438eee43.png)

## 具体描述
英文版本有一个数据集的截图，中文版本没有

**Comment by Kyliewang** [comment]
已补充。

**Comment by ivylee0919** [comment]
@Kyliewang 目前看到[2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)是没有图片的。
