### ISSUE TITLE
[数据分析入门] 课程1 数据分析过程 2. 课程概述[缺少课程内链接]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#180]
## 课程导航+地址
入门>课程1 数据分析过程>课程链接> [ 2. 课程概述](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/af5a2298-880b-409c-bf0b-57a27158a99a)

## 截图

![report](https://user-images.githubusercontent.com/24636410/40726908-4f16bdf8-6459-11e8-8daf-2830d313f557.png)

## 具体描述
导师指出下面有 `Python` 基础相关部分的链接，这里是否需要根据需要添加相关链接呢？

**Comment by ZenRay** [comment]
[数据分析（入门） - 课程1 数据分析过程 2. 课程概述](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/14dc2deb-45a2-49a7-baa0-82203738e14a)， 在 3 分 59 秒提到的相关课程，机器学习和推论统计学课程，也没有链接

**Comment by Kyliewang** [comment]
Python基础的相关部分已经补充。

但是课程1 数据分析过程 2. 课程概述并没有提到机器学习和推论统计学课程，建议确认一下位置。

**Comment by ZenRay** [comment]
[数据分析（入门） - 课程1 数据分析过程 5.数据分析过程概述](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/14dc2deb-45a2-49a7-baa0-82203738e14a)， 在 3 分 59 秒提到的相关课程，机器学习和推论统计学课程，也没有链接。
**犯了一个错误，上面的描述忘记更改了，是在另一个小节。可以参考下面的图**

<img width="1245" alt="report" src="https://user-images.githubusercontent.com/24636410/40950652-3e152b06-68a6-11e8-9167-05918ab69bd9.png">
