### ISSUE TITLE
练习缺少 Workspace

### ISSUE THREAD

**Issue by LynnLululu** [udacity/DAND-CN-feedback#181]
## 截图
<img width="1212" alt="demo" src="http://ww1.sinaimg.cn/large/6e2f3b07ly1frtrjua1wbj227y16ee05.jpg">

## 具体描述
 练习页面缺少对应的workspace模块，英文版是有的

**Comment by nicoleliu42** [comment]
感谢反馈！引号问题已经修复，workspace的问题麻烦 @Kyliewang 看一下哦！
