### ISSUE TITLE
[数据分析入门] 课程3  控制流 9. 练习：for 循环

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#183]
## 课程导航+地址
入门>课程3  控制流>课程内容> [9. 练习：for 循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/90abdb2f-ca75-4290-a5db-8942822f9d48)

## 截图

<img width="929" alt="report" src="https://user-images.githubusercontent.com/24636410/40886126-5ed53120-6765-11e8-9932-dc5a0be01b06.png">

## 具体描述
练习提示内容非英文，需要核查一下。

**Comment by Kyliewang** [comment]
已经修改，感谢反馈~
