### ISSUE TITLE
[数据分析入门] 项目探索美国共享单车数据 12.如何完成该实战项目[缺少资源]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#184]
## 课程导航+地址
入门>项目探索美国共享单车数据>课程内容> [12.如何完成该实战项目](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/27776c8d-7dfa-4995-adac-e837d03eee77/lessons/b253dfc8-45ab-4196-a4f1-cd0668789d98/concepts/b8cd0f85-1c2b-4636-bcfd-f4348447f8b2)

## 截图
<img width="929" alt="report" src="https://user-images.githubusercontent.com/24636410/40886693-647ab2c6-676f-11e8-9701-b35fc7d229cf.png">

## 具体描述
1）演示图片错误，该图片应该是老课程图片，课程序号已经变更
2）根据演示的，资源选项卡 `resources tab` 中 没有相关下载资源。
**在英文版本下也同样存在缺少资源的问题**

其中一种方法是在课程中右键下载：
![report](https://user-images.githubusercontent.com/24636410/40886723-f3bbea36-676f-11e8-8c1f-37b109fee091.jpeg)

**Comment by Kyliewang** [comment]
资源已上传，谢谢反馈~
