### ISSUE TITLE
[数据分析进阶] 课程1 数据整理简介 16.练习：评估（编程）[缺少链接]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#187]
## 课程导航+地址
进阶> 课程1 数据整理简介>课程链接> 16[练习：评估（编程）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/1ab8bd1a-fc0c-41e8-b5f9-14b6bf637cd5)

## 截图

![report](https://user-images.githubusercontent.com/24636410/40988651-36e3700e-691e-11e8-82e9-67b9f778e9e0.png)

## 具体描述
1）文档不通顺：`链接了下面的文档页面`。应该是 `链接在下面的文档页面`
2）中文和英文课程都缺少相关方法的链接

**Comment by Kyliewang** [comment]
Hi Ray, 

head\tail\info\value_counts四个方法均有超链接，请确认。

**Comment by ZenRay** [comment]
看出来了，这里就是四个子项目就是链接。如果是这样的话，建议可以调整一下格式——将链接独立处理，或者改一下 `markdown` 语法。
