### ISSUE TITLE
[数据分析进阶] 课程1 数据整理简介23. 练习：清洗（练习）

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#189]
## 课程导航+地址
进阶> 课程1 数据整理简介>课程链接> [23. 练习：清洗（练习）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/5ff3a6ff-57dd-4d8c-ad87-7e05ce7b280f)

## 截图

![report](https://user-images.githubusercontent.com/24636410/40990603-f249fdc2-6923-11e8-8daf-59a745b6d3ae.png)

## 具体描述
`markdown` 语法错误

**Comment by nicoleliu42** [comment]
感谢反馈！这里的语法错误已经修复~
