### ISSUE TITLE
【翻译问题】【共享单车项目】项目详情

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#19]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37553824-0578a0c8-2a0a-11e8-97f5-bb8071a38e1d.png)

## 具体描述
我们执行了一些数据整理操作，以将这些文件压缩成上述核心六大列，使分析需求和 Python 技能评估更直接。在数据分析师纳米学位课程中，此课程后面有一门数据整理课程，这门课程会讲解如何整理最杂乱无章的数据集，因此不用担心不了解这方面的知识。

建议修改为：

我们执行了一些数据整理操作，使这些文件压缩成上述核心六大列，以便于更直接地使用 Python 技能进行评估和分析。在后续的数据分析师纳米学位（进阶）课程中，有一门课程专门讲解如何整理最杂乱无章的数据集。因此不用担心不了解这方面的知识。

**Comment by Kyliewang** [comment]
@sylviasun916 

"使分析需求和 Python 技能评估更直接。"   这一句的翻译不好理解，已经在coco修改。
