### ISSUE TITLE
[数据分析进阶] 课程1 数据整理简介 26.整理与 EDA 与 ETL[链接失效]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#190]
## 课程导航+地址
进阶> 课程1 数据整理简介>课程链接> [26.整理与 EDA 与 ETL](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/9fb988fb-7426-4804-9158-bbb19c08f7ee)

## 截图

<img width="1253" alt="report" src="https://user-images.githubusercontent.com/24636410/40991368-2ac697ee-6926-11e8-93ad-0d6e41a18ba8.png">

## 具体描述
1）`EDA` 的定义这个链接失效
2）课程中 `它们*非常相似`，应该是多了一个星号

**Comment by nicoleliu42** [comment]
感谢反馈！markdown语法已经修复！链接失效的问题还请 @Kyliewang 看一下哦！

**Comment by Kyliewang** [comment]
感谢~ 已解决。
