### ISSUE TITLE
[数据分析进阶] 课程2 收集数据 4.浏览工作目录和文件 I/O

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#191]
## 课程导航+地址
进阶> 课程2 收集数据>课程链接> [4. 浏览工作目录和文件 I/O](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/b674f69b-d097-4144-aa35-9e67597a175b)

## 截图

<img width="1259" alt="report" src="https://user-images.githubusercontent.com/24636410/41016510-5d55aa0e-6982-11e8-9155-c71c9bc0c41c.png">

## 具体描述
这里的 “#” 是否是`markdown` 中更改 `header` 类型的呢？

**Comment by nicoleliu42** [comment]
感谢反馈！这里少了空格，已经修复啦！
