### ISSUE TITLE
[数据分析进阶] 课程2 收集数据 15 资料来源：API(应用程序编程接口)

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#195]
## 课程导航+地址
进阶> 课程2 收集数据 >课程链接> [14.Python 中的文本文件](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/dd0877f5-f3e7-4fab-869a-126e89ce944b)

## 截图
<img width="1256" alt="report" src="https://user-images.githubusercontent.com/24636410/41030384-cc43f438-69b0-11e8-91c8-877c8abd46d0.png">

## 具体描述
划红线部分应该是没有调整好 `markdown`，另外其中有一个 `Lesson` 应该是指的 `教室`。

**Comment by nicoleliu42** [comment]
感谢反馈！已修复！
