### ISSUE TITLE
[数据分析进阶] 课程2 收集数据 18.混搭：API、以编程方式下载文件、JSON

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#197]
## 课程导航+地址
进阶> 课程2 收集数据 >翻译> [18.混搭：API、以编程方式下载文件、JSON](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/e1e1648f-b80b-4d5a-a986-97474ebcb089)

## 截图
<img width="1238" alt="report" src="https://user-images.githubusercontent.com/24636410/41032588-75fb0408-69b6-11e8-923d-6eb38a6f3553.png">

## 具体描述
红线部分存在翻译问题：
原始文件是：`This type of error is why the requests library maintainers recommend using the PIL library (short for Pillow) and BytesIO from the io library for non-text requests, like images. `
建议翻译为：这种错误是因为  [`requests` 库](http://docs.python-requests.org/en/latest/user/quickstart/#binary-response-content)的维护人员推荐使用 [`PIL` 库](https://pillow.readthedocs.io/)(Pillow 的缩写)和 `BytesIO`， 它来自于处理非文本文件（例如：图像）请求的 `io` 库

**Comment by nicoleliu42** [comment]
感谢反馈~！这里的翻译已经优化，非常感谢你提供的建议！
