### ISSUE TITLE
对magic word的注释

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#199]
## 课程导航+地址
例子：入门 > 项目三:数据分析集 > 4.项目：数据分析集
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/bce8d241-89f4-422e-abda-c5a4e5ceb8fe/lessons/e6fe760d-c9ef-437d-9b97-b313458821e6/concepts/642ab657-197e-4beb-afd6-4494e6da490b
## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/38323732/41076923-8cef68d0-6a46-11e8-8aa8-6caa368b1585.png)

## 具体描述
项目3的群里不少人对“务必包含一个magic word，以便将你的视图与notebook保持一致”中的“magic word”不理解，希望对此进行注释，如“务必包含一个magic word（带有“%”的***），以便将你的视图与”

**Comment by nicoleliu42** [comment]
感谢你的反馈~！已经添加注释，方便学员理解！另外下方链接其实是有提供解释的哦！
