### ISSUE TITLE
数据分析(入门) - Numpy & Pandas - 第一部分 -5.练习NumPy数组, 最后函数的最优实现被直接接给出了

### ISSUE THREAD

**Issue by hugo626** [udacity/DAND-CN-feedback#20]
## 课程导航+地址
数据分析(入门) - Numpy & Pandas - 第一部分 - [5.练习NumPy数组](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490080923), 最后函数的最优实现被直接接给出了

## 截图
![numpy -2](https://user-images.githubusercontent.com/1345356/37553812-da814c84-2a1e-11e8-8d7a-c3d02e86f86b.PNG)

## 具体描述
不确定是因为给我们测试, 所以直接给出了最优解,还是本身的bug导致错误给出了最优解.

## 更多的建议
 建议把代码不要直接全部给出, 而且每个种类型的问题都给出1个有代表性的例子, 然后附加多个练习. 这样可以帮助没有基础的同学多做练习,达到帮助他们提高对python 使用熟练度的目的, 为后面的打下基础.
最后的max_employment 函数中的实现方法已一定不要提前给出.

**Comment by WheatJH** [comment]
这个是因为同一账号提交过一次答案后，会保留那道题目的代码，所以在实际课程中，学员第一次操作时是没有给定已实现的结果。

**Comment by ivylee0919** [comment]
@hugo626 测试时可以先重设练习或者 Reset Data
