### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#200]
## 课程导航+地址
例子：入门 > 项目4：统计学>课程2：描述统计学>14.练习：应用平均差和方差
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/c5b785aa-a0e9-45ac-8c4f-6e192829babe/concepts/a0d15032-7518-473d-84a3-617a062a19b1

## 具体描述
第一个提交答案后显示得内容未翻译。

**Comment by nicoleliu42** [comment]
感谢你的反馈！不过这里的内容因为系统问题，暂时无法进行翻译。我们会反馈给相关部门同事，以尽快支持翻译，给学员带来更好的体验！
