### ISSUE TITLE
[数据分析进阶] 课程3 评估数据 6 评估：类型与步骤

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#201]
## 课程导航+地址
进阶> 课程3 评估数据>课程翻译> [ 6 评估：类型与步骤](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/6c90f297-a296-4590-83e9-fc4a78248402)

## 截图
<img width="1272" alt="report" src="https://user-images.githubusercontent.com/24636410/41102854-6e3d0a7e-6a9a-11e8-95f6-12074230c34b.png">

## 具体描述
原文：`Note: Visualizing your data (i.e., creating plots) is part of Programmatic rather than Visual Assessment. Tricky! This is because plotting data requires coding, or programming.`

建议翻译：`注：将数据可视化（例如：绘制图形）是编程评估而非目测评估。虽然表面上看起来难以理解。这是因为对数据绘图需要编写代码。`

**Comment by nicoleliu42** [comment]
感谢你的建议！这里的翻译已修正！
