### ISSUE TITLE
练习题答案未翻译

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#202]
## 课程导航+地址
例子：入门 > 项目四：统计学>7.贝叶斯规格 > [36. 学习目标]练习5/5答案
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/9a02a699-1edb-42cf-9df4-10ec39895262/concepts/d0e067b6-9913-4ac2-9e33-4e927fb99034
## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/38323732/41158662-5b6ea80e-6b5c-11e8-8ec1-306358989021.png)

## 具体描述
练习5/5的答案未翻译

**Comment by nicoleliu42** [comment]
感谢你的反馈！已补充翻译~！
