### ISSUE TITLE
练习题答案翻译错误

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#205]
## 课程导航+地址
例子：入门》项目四：统计学》课程10：抽样分布和中心极限定理》6.视频+练习 
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/4757541f-77eb-4df6-9ebf-9485a3383dd3/concepts/4fa22655-1514-4c45-8a87-e53b5b6cb0d0
## 截图

![image](https://user-images.githubusercontent.com/38323732/41186350-797ef5b8-6bc7-11e8-92ef-aaacfdfd488e.png)

## 具体描述
提交答案后显示的结果“错”，应改为“对”

**Comment by nicoleliu42** [comment]
感谢你的反馈！这里的错别字已经修正啦
