### ISSUE TITLE
[数据分析进阶] 课程3 评估数据 10 评估与探索

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#208]
## 课程导航+地址
进阶> 课程3 评估数据  >课程翻译> [10 评估与探索](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/1165caef-24c9-4a2f-8030-4d6420c0c30a/lessons/243eeaed-5cd8-4e3c-91fa-9131d430138e/concepts/6bb4a8d6-c72f-4696-9193-22fe39396e03)

## 截图
![report](https://user-images.githubusercontent.com/24636410/41201814-eb8a9d12-6cf1-11e8-8d8d-f660ff5e5856.png)

## 具体描述
最下面 `note` 部分翻译比较难以理解，建议更改一下：

原文是：`Exploring, in the context of a clinical trial, is less likely to happen given that clinical trials are expensive and consist of extreme pre-planning. So exploring on this dataset would likely exclusively happen before the treatments and adverse_reactions tables were created, i.e., before the clinical trial was conducted.`

建议翻译为：“鉴于临床试验的背景，考虑到临床试验的高昂费用，及其各种极端预案（⚠️这里的 extreme pre_planning 可能需要 domain knowledge 才能更好翻译，这只是一个方案），探索是不太适用的。所以在 `treatments` 和 `adverse_reactions` 数据表建立之前，例如在临床试验开始之前可能需要专门来探索这一类数据集。”

**Comment by nicoleliu42** [comment]
非常感谢你的帮助！这里的翻译已优化~！
