### ISSUE TITLE
【翻译问题】【共享单车项目】项目详情-关于问题

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#21]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37553866-f444c1dc-2a0a-11e8-9636-e4d4679c279b.png)

## 具体描述
1. 帮助理解的括号内信息，没有翻译；
2. 目前的翻译没有以数据集的角度来进行描述，不好理解。

建议，直接使用了 Markdown 语法
```
- 起始时间（Start Time 列）中哪个月份最常见？
- 起始时间中，一周的哪一天（比如 Monday, Tuesday）最常见？
提示：可以使用 `datetime.weekday()` （点击[查看文档](https://docs.python.org/3/library/datetime.html#datetime.date.weekday)）
- 起始时间中，一天当中哪个小时最常见？
- 总骑行时长（Trip Duration）是多久，平均骑行时长是多久？
- 哪个起始车站（Start Station）最热门，哪个结束车站（End Station）最热门？
- 哪一趟行程最热门（即，哪一个起始站点与结束站点的组合最热门）？
- 每种用户类型有多少人？
- 每种性别有多少人？
- 出生年份最早的是哪一年、最晚的是哪一年，最常见的是哪一年？
```

**Comment by Kyliewang** [comment]
coco中已经修改。

翻译后的文本中缺少了部分提示。 @sylviasun916
