### ISSUE TITLE
[数据分析入门] 共享单车-如何测试你的代码文本位置

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#210]
## 课程导航+地址
例子：入门 > Python 入门 > 项目：探索美国共享单车数据 > [14. 如何测试你的代码](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/27776c8d-7dfa-4995-adac-e837d03eee77/lessons/b253dfc8-45ab-4196-a4f1-cd0668789d98/concepts/0f6c8e5e-53d8-45e8-b961-82619b1e0f51)

## 截图
![_20180614210935](https://user-images.githubusercontent.com/11519486/41413972-58e2d50a-7017-11e8-9c08-5f61d1cb9a95.png)

## 具体描述
截图中的这部分提示，应该放在上一条问题的后面 @Kyliewang

**Comment by Kyliewang** [comment]
Sorry 上次反馈忘记了，已经修改好了！
