### ISSUE TITLE
[数据分析入门] 课程12 假设检验 12.假设检验的一般类型

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#212]
## 课程导航+地址
进阶> 课程12 假设检验 >课程内容> [12.假设检验的一般类型](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/ad8aca80-f444-4479-8848-5b07bafaf66c/concepts/08902160-e457-446b-9c50-f972926cd284)

## 截图
<img width="1264" alt="report" src="https://user-images.githubusercontent.com/24636410/41478526-912e4c58-70fa-11e8-95a3-acef64601b48.png">

## 具体描述
翻译错误，这里的原文是 `bootstrap`，应该是“自助法”

**Comment by sylviasun916** [comment]
文本翻译已修改为 ”自助法“，非常感谢你的建议！

**Comment by sylviasun916** [comment]
麻烦@Kyliewang 可不可以看一下另一个外链/ 链接问题哦……

**Comment by Kyliewang** [comment]
已经修改，谢谢！
