### ISSUE TITLE
[数据分析入门] 课程1 数据分析过程 14 评估和理解

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#214]
## 课程导航+地址
入门> 课程1 数据分析过程 >课程内容> [12. 数据收集](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/1465740f-52d8-44b6-879d-6d2ac23d84ab#)

## 具体描述
辅助材料中的文件 [Reading-Csv-Solutions](https://s3.amazonaws.com/video.udacity-data.com/topher/2018/May/5af94dda_reading-csv-solutions/reading-csv-solutions.ipynb) 和课程中 13节的辅助材料中的文件相同，应该是文件上传错误了。

**Comment by ZenRay** [comment]
[第 18 小节清理练习](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/cfb63a6e-56a3-4022-9d61-514f2f4759a8/lessons/e18a5529-84f8-4e5c-a431-3b74d98df969/concepts/7388b4a2-84fb-4753-b1e7-89e8618afbb0#) 也是存在同样的问题

**Comment by Kyliewang** [comment]
清理练习中已经修改，但是“数据收集”部分并没有看到辅助材料。

**Comment by Kyliewang** [comment]
找到了，是评估与理解。
