### ISSUE TITLE
[数据分析入门] 课程 2 描述统计学 20.形状和异常值

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#218]
## 课程导航+地址
入门> 课程 2 描述统计学 >课程内容> [ 20.形状和异常值](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/c5b785aa-a0e9-45ac-8c4f-6e192829babe/concepts/d6fc5218-8ffb-42ef-bab6-4741d1d13608)

## 截图
![report](https://user-images.githubusercontent.com/24636410/43246747-32bbe508-90e5-11e8-8387-eb11c18f2526.png)

## 具体描述
这里的描述不完全准确，当异常值是极值的时候那么对五数概括中的极值是肯定有影响的，这个时候影响还是比较大的。对于其他四分位数影响肯定是相对小很多

**Comment by ZenRay** [comment]
![image](https://user-images.githubusercontent.com/24636410/43246890-ab59f5b8-90e5-11e8-8444-8d841c96c134.png)
另外课程中存在导师名错误的情况，存在了好几处。这里的位置是 [10. 标准差和方差简介](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/c5b785aa-a0e9-45ac-8c4f-6e192829babe/concepts/5f2d9388-2cdc-46d5-81f8-8293edaafdb4)

**Comment by Kyliewang** [comment]
能把存在的好几处都找出来吗？ @ZenRay

**Comment by Kyliewang** [comment]
五数概括法的问题已经修改~

**Comment by ZenRay** [comment]
嗯，好的。后面看见了再添加 `commit` 。 @Kyliewang

**Comment by ZenRay** [comment]
![image](https://user-images.githubusercontent.com/24636410/43332210-4199edca-91fa-11e8-893f-7d0ef422c11a.png)
这里也存在问题。

**Comment by Kyliewang** [comment]
已经修改。
