### ISSUE TITLE
数据分析入门> 课程 8 Python 概率练习  [5. 二项分布测试]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#219]
## 课程导航+地址
入门> 课程 8 Python 概率练习 >练习内容> [5. 二项分布测试](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/33860189-96c0-40cf-8f12-5772c8b8c790/concepts/2c87518c-73ec-4b5f-bf1d-4f7af4e73b97)

## 截图
![image](https://user-images.githubusercontent.com/24636410/43363603-00a71ec2-933b-11e8-9097-f7f05d512d5d.png)

## 具体描述
按照课程的要求，这里练习应该是至少三个，红框内表示的是三个

**Comment by Kyliewang** [comment]
已经修改。
