### ISSUE TITLE
【资源缺失】【共享单车项目】如何完成该实战项目

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#22]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [4. 如何完成该实战项目](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37553980-da442992-2a0c-11e8-8eba-3ddf0f64863a.png)

## 具体描述
资源选项卡中没有对应的可下载文件 @Kyliewang

**Comment by EasonYau** [comment]
![image](https://user-images.githubusercontent.com/26672471/37555035-4e52ed00-2a1c-11e8-998e-7b824c2b42fc.png)
我也好奇～～是放在项目详情这里了吗？

**Comment by Kyliewang** [comment]
已经添加。
