### ISSUE TITLE
数据分析入门> 课程 1 欢迎来到纳米学位 [1. 欢迎学习数据分析] 

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#220]
## 课程导航+地址
数据分析入门> 课程 1 欢迎来到纳米学位 [1. 欢迎学习数据分析] (https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/4c399c8e-6d19-48c1-88c8-af3ee3f6d541/lessons/0e3408d5-b6dc-466e-af1f-c4349935d1cb/concepts/00540bc7-f0bf-46d2-909d-f8c2082fe28c)

## 截图

![d1](https://user-images.githubusercontent.com/7417557/43521368-8713d808-95c8-11e8-8fc3-12b2b86e540f.png)

## 具体描述
视频中英文字幕间隔太大，建议缩小间隔

**Comment by ZenRay** [comment]
字幕格式问题，对于视频课程查看有影响 @Kyliewang
