### ISSUE TITLE
数据分析入门> 课程 1 欢迎来到纳米学位 [5. 诚信和决心]

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#221]
## 课程导航+地址
数据分析入门> 课程 1 欢迎来到纳米学位 [5. 诚信和决心](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/4c399c8e-6d19-48c1-88c8-af3ee3f6d541/lessons/0e3408d5-b6dc-466e-af1f-c4349935d1cb/concepts/592f478e-11db-41e9-9925-e68edfd270b6)

## 截图
![d2](https://user-images.githubusercontent.com/7417557/43521907-2e2e121a-95ca-11e8-9bd6-7ebab376aa7c.png)

## 具体描述
此处多余，建议删除

**Comment by LeeSkyX** [comment]
已解决
