### ISSUE TITLE
数据分析入门>课程5 二项分布>练习1-7，9-15

### ISSUE THREAD

**Issue by zhangshuqinshanghai** [udacity/DAND-CN-feedback#222]
## 课程导航+地址
例子：数据分析入门>课程5 二项分布>练习1-7,9-15
[1.练习 二项式](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/dbd37b8d-f8e0-4708-a919-4b5cebe5ccaf/concepts/486966560923)

## 截图
![1](https://user-images.githubusercontent.com/33413366/43525617-e830812a-95d4-11e8-957e-75ae48924b69.jpg)

## 具体描述
练习1-7&9-15每页播放到最后，练习中初始值设置是 0，不要初始值是否更好？

**Comment by ZenRay** [comment]
@zhangshuqinshanghai ，链接因为语法错误不可用。链接推荐使用 `markdown` 模式，语法是 `[课程小节名称](URL地址)`，修改后效果：[练习1-7,9-15](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/dbd37b8d-f8e0-4708-a919-4b5cebe5ccaf/concepts/487283760923)
