### ISSUE TITLE
数据分析进阶 > 数据清洗 > 数据整理简介 > 1. 介绍

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#224]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [1. 介绍](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/3400db6c-cb8d-4043-933a-16eeda6725ac)

## 截图
<img width="992" alt="image" src="https://user-images.githubusercontent.com/1688209/43527001-1b8c1554-95d8-11e8-9e15-fadf29b9846d.png">

## 具体描述
视频17s处字幕“以及数据清理的过程”，应改为“以及数据清洗的过程” ，为保持一致性，data cleaning翻译成数据清洗较妥

**Comment by ZenRay** [comment]
这里是一个倒置的语句，这里的 `cleaning` 说的是 `data wrangling` 中的一个方面，这里翻译为清理或清洗应该是没有问题的 @Kyliewang

**Comment by sylviasun916** [comment]
@Kyliewang @ZenRay  这里需要修改吗？ 如需要修改，可以再艾特我哈。

**Comment by ZenRay** [comment]
我认为是不用调整都可以，需要 @Kyliewang 确认一下

**Comment by sylviasun916** [comment]
好的 谢谢
