### ISSUE TITLE
数据分析进阶 > 课程 1：什么是 EDA？ > [8. Aude 探索协调迁移]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#226]
## 课程导航+地址
数据分析进阶 > 课程 1：什么是 EDA？ > 什么是EDA > [8. Aude 探索协调迁移](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/9030385470923)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/19308564/43529259-7f6736a8-95dd-11e8-8190-48cc39540498.png">

## 具体描述
"Coordinated Migration"个人认为译为“共同迁徙”为好。首先，Aude Hoﬂeitner的文章里，定义Coordinated Migration时表示这是一个群体性行为，所以“共同”比“协调”准确些。另外，“Migration”在此指的是具体的“人口迁徙”，可能更符合我们的语言习惯。

总的来说，整个标题若改为“与Aude一起探索人口共同迁徙现象”，可能较为准确些。

**Comment by ZenRay** [comment]
从单词意思来看，比较难以确认使用共同这个意思；同时这里 `Facebook` 探索的是在给定条件下的具有的迁徙行为，需要确认一下具体的 `domain` 信息

**Comment by wszhan** [comment]
从Aude Hoﬂeitner的文章来看，不可能是 **“协调”** 之意；同样根据文章，可以知道这里强调的是**多人共同迁徙的行为**，[原文](https://www.facebook.com/notes/facebook-data-science/coordinated-migration/10151930946453859)中强调该条件的部分为

**"We formally define a coordinated migration as the movement of population from a hometown h to its most likely current city c(h) such that: At least 100 users have listed city h as their hometown."**

"Coordinated"一词之意在今日也不只是“协调”之意，具体可参考[Merriam-Webster上自动摘录关于coordinated的最近用法及上下文](https://www.merriam-webster.com/dictionary/coordinated)。

**Comment by ZenRay** [comment]
@wszhan 从你提到的网页定义来看，“共同”的意思更符合定义——最终向“movements to a single end”。在 `Facebook` 的应用场景下却不符合的，移动的目的地不是单一方向了，而只是向同样的规则方式移动。请确认一下呢 @Kyliewang 
![image](https://user-images.githubusercontent.com/24636410/43629876-23f9d280-9731-11e8-875e-1d950a1b465d.png)

**Comment by sylviasun916** [comment]
@Kyliewang  可能需要 Kylie 的专业知识看一下 这里需不需要修改哦？ 感谢！

**Comment by Kyliewang** [comment]
暂不需要修改哦~
