### ISSUE TITLE
数据分析进阶 > 课程 1：什么是 EDA？ > 什么是EDA > [7. 本课程的方法]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#227]
## 课程导航+地址
数据分析进阶 > 课程 1：什么是 EDA？ > 什么是EDA > [7. 本课程的方法](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785580923)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/19308564/43530197-90ad3172-95df-11e8-9281-718751663051.png">

## 具体描述
课程下方说明第一句话

“在 0:40 处，Dean 论述了有关数据集的测试直觉”，

结合视频，意思应该为

“在 0:40 处，Dean讲到我们有时会希望检测自己对于数据的直觉（，并且培养新的直觉）”。

另外，原文中“Dean”后面的空格属于英文习惯，应删去。

**Comment by ZenRay** [comment]
这个是正常表达，**英文前后有空格**

**Comment by wszhan** [comment]
空格问题可忽略。

重点是Instructor Notes里 **“Dean 论述了有关数据集的测试直觉”** 这句无法让人理解。我更正了这句话的意思。

**Comment by ZenRay** [comment]
这句话是一个综述性描述，确实可以如 @wszhan 所说把内容放全比较好
![image](https://user-images.githubusercontent.com/24636410/43630172-1da6fd44-9732-11e8-9202-0be3ed87db2e.png)

**Comment by LeeSkyX** [comment]
已解决
