### ISSUE TITLE
数据分析入门>可选课程 1 配置Anaconda[4.管理包] 文字描述和体验

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#230]
## 课程导航+地址
入门 > 可选课程 1 配置Anaconda> 课程内容描述 > [4.管理包](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/91b5b867-4a7f-49c5-b658-57521a8de12d/modules/e95ca0b1-2716-4f45-bf4b-781653e885e5/lessons/c6a12f2e-63f2-4007-a2c3-dd3e5f06f3cb/concepts/9310a67f-9b23-449e-8949-4312dc718ef9)

## 截图
![41](https://user-images.githubusercontent.com/31531236/43531595-b21ebb3e-95e2-11e8-97ae-771991a680b7.png)

## 具体描述
1.   在终端键入，这个在windows下需要补充：在所有程序中，找到Anaconda，打开Anaconda Prompt终端，反正安装的时候我没选择添加环境变量，不能从cmd中直接打开anaconda  

## 截图
![42](https://user-images.githubusercontent.com/31531236/43531977-96c0f360-95e3-11e8-9cb7-1d7bdd260406.png)

## 具体描述
1.   要不还是改为“Good Job”吧，翻译了反而不好，别扭；有些常用的英文短语不用翻译的，都已经英文课程，中文字幕的，学习的people多少也是会点英文的。

**Comment by ZenRay** [comment]
😄，这个不算是问题吧
