### ISSUE TITLE
数据分析进阶>练习和数据集>最后两段

### ISSUE THREAD

**Issue by sccds** [udacity/DAND-CN-feedback#231]
## 课程导航+地址
数据分析进阶>练习和数据集>最后两段

## 具体描述
原文：
我们将在介绍每个步骤的间隙整理一个真实的数据集，将在之前介绍中学到的概念转换为 Python 代码。不用担心，我会为你提供指导。记住我们的最终目标是 —— 在整个过程中实现强大的分析和可视化。最后我们将以数据整理的实际应用来结束这一课。
建议：
我们将以真实数据为例，对数据整理中每一个步骤进行介绍，并将概念转换为python代码。最终目标是--实现强大的分析和可视化。最后我们将以数据整理的实际应用来结束这一课。

原文：
我们将要整理的数据集由一个亚美尼亚人力资源门户网站发布 从 2004 年到 2015 年的 19000 个在线职位数据集。它托管在 Kaggle 上，这是一个非常受欢迎的网站，主要探索数据分析和机器学习竞争。这些数据集杂乱无章，所以你需要做很多工作，但清洗就行了，也不会太让人头疼。
建议：
我们将整理的数据集是由一个亚美尼亚人力资源门户网站发布的 2004 年到 2015 年19000 个在线职位数据集，托管在Kaggle上。Kaggle是一个著名的网站，上面有各种数据分析和学习竞赛。
这些数据杂乱无上，你需要做的工作，就是进行整理，清洗数据。

**Comment by ZenRay** [comment]
@sccds 麻烦给一下链接或者截图呢

**Comment by sccds** [comment]
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/e863f047-3eb3-4b10-9deb-aa668275d60b

@ZenRay

**Comment by ZenRay** [comment]
1. 第一段翻译是根据导师的介绍，没有必要进行调整
2. 这里可以按照中文表达方式进行调整 @Kyliewang 

另外文本中存在语法错误，建议一起调整一下 @Kyliewang 
![image](https://user-images.githubusercontent.com/24636410/43561779-308772b4-964b-11e8-89fd-5d093fd1979e.png)

**Comment by LeeSkyX** [comment]
已解决
