### ISSUE TITLE
数据分析进阶 > 课程 2：R 基础 > [2. R 的能力]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#233]
## 课程导航+地址
数据分析进阶 > 课程 2：R 基础 > [2. R 的能力](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293050923)

## 截图

![image](https://user-images.githubusercontent.com/19308564/43534220-6ab90c48-95e9-11e8-8529-c9f48b4af498.png)

## 具体描述
两个介绍链接导向维基百科，但是部分用户可能无法访问，因为维基百科已经被blocked，建议在下面增加两个百度百科的备用链接。

**Comment by ZenRay** [comment]
维基百科，不能直接访问 @Kyliewang

**Comment by Kyliewang** [comment]
英文维基百科无 GFW 问题。
