### ISSUE TITLE
数据分析入门>可选课程 2 配置jupyter notebook [1.jupyter notebook 是什么] 外链

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#236]
## 课程导航+地址
入门 > 可选课程 2 配置jupyter notebook> 外部链接 > [1.jupyter notebook 是什么](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/91b5b867-4a7f-49c5-b658-57521a8de12d/modules/e95ca0b1-2716-4f45-bf4b-781653e885e5/lessons/b15ba0a2-015d-4c5a-87ae-9efba2cabb43/concepts/75e1eee0-5f81-4d5b-a1ca-eaebe3c91759)

## 截图
![11](https://user-images.githubusercontent.com/31531236/43556789-285d0a34-9634-11e8-9624-6f57d0906bf7.png)

## 具体描述
1.   不知道是我电脑屏幕太小，13.5寸，还是怎么的，直接点击这个"jupyter 文档"链接，只是图片放大，没有打开链接，鼠标右键新窗口可以打开链接  

2.   “可用内核列表”点击后，github显示：Moved to Jupyter kernels.，要不要换个链接啊，比如：https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

**Comment by ZenRay** [comment]
1. 第一个问题需要调整一下文字和图片，应该是图片被放到了链接的文档中。需要调整一下文档
2. 这个问题是英文 `GitHub` 调整了，需要将链接调整一下

两个都需要调整一下链接 @Kyliewang

**Comment by Kyliewang** [comment]
已经修改。

**Comment by Kyliewang** [comment]
第一个没有问题，图片放大之后仍然可以点击链接。
