### ISSUE TITLE
数据分析入门>可选课程 2 配置jupyter notebook [3. 启动 notebook服务器] 体验

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#237]
## 课程导航+地址
入门 > 可选课程 2 配置jupyter notebook > 内容体验 > [3. 启动 notebook服务器](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/91b5b867-4a7f-49c5-b658-57521a8de12d/modules/e95ca0b1-2716-4f45-bf4b-781653e885e5/lessons/b15ba0a2-015d-4c5a-87ae-9efba2cabb43/concepts/7832d9b4-e925-4d5f-848e-c9289cac4f33)

## 截图
![31](https://user-images.githubusercontent.com/31531236/43557132-d43a0a0e-9635-11e8-8f2e-4fad2ba2b4b1.png)

## 具体描述
1.  启动notebook的时候，要不要补充在window电脑下，最好使用google浏览器打开啊，或者说，打不开的时候尝试换个默认浏览器打开，我当初默认猎豹浏览器，结果就打开空白。刚用IE试了试，也不行，不知道Edge行不行。  

2.   “从conda环境中运行notebook服务器”，指的是什么啊，我从Anaconda Prompt中运行的jupyter notebook 怎么没看到，这个conda选项卡，管理环境呢？只是显示了：files、running、clusters

**Comment by ZenRay** [comment]
1. 关于兼容性问题，这个是网页端肯定会涉及到这个问题。目前从文档了解到到是你上面提到的几个浏览器都没有问题，另外可能就是需要更新到最新版本 [The Jupyter Notebook — Jupyter Notebook 5.6.0 documentation](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#browser-compatibility)

2. 这里直接翻译英文，确实难以理解。建议更改一下，另外就是这里因果关系没有这样的关系——任何环境进入 notebook 页面都可以访问 conda 选项卡的。另外这里管理环境，不仅仅针对 Jupyter 中的环境。 @Kyliewang
