### ISSUE TITLE
数据分析入门>可选课程 2 配置jupyter notebook [8. 转换 notebook] 体验

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#239]
## 课程导航+地址
入门 > 可选课程 2 配置jupyter notebook > 课程内容不全 > [8. 转换 notebook](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/91b5b867-4a7f-49c5-b658-57521a8de12d/modules/e95ca0b1-2716-4f45-bf4b-781653e885e5/lessons/b15ba0a2-015d-4c5a-87ae-9efba2cabb43/concepts/2b324ee9-d6ec-4af4-b105-c4996b53d162)

## 截图
无

## 具体描述
1.   文中介绍的转换notebook方法是代码转换，
> jupyter nbconvert --to html notebook.ipynb   

其实可以直接点击文件，download as，转换成其它文件进行分享的，但是这里却没有介绍  

![71](https://user-images.githubusercontent.com/31531236/43558682-49ab30b8-963d-11e8-993b-2a14396f820f.png)

**Comment by ZenRay** [comment]
建议添加直接 `download` 方式

**Comment by LeeSkyX** [comment]
已解决
