### ISSUE TITLE
数据分析入门>核心课程 4 统计学 >16. 逻辑回归 [4. 视频：在python中拟合逻辑回归]

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#241]
## 课程导航+地址
入门 > 核心课程 4 统计学 > 16. 逻辑回归 > [4. 视频：在python中拟合逻辑回归](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/b7ae43e6-204a-4816-a177-6c75115cae5f/concepts/28777848-e025-4ffe-aea6-9c08d814512a)

## 截图
![41](https://user-images.githubusercontent.com/31531236/43560487-48afbdb6-9645-11e8-8ea0-b87d2baf05be.png)

## 具体描述
视频01：43s处字幕  
"所以我将要传递这个诈骗 应当创造截距"  
需改为:  
"所以我将要传递这组fraud数据， 且应创造截距" 
或者改为：  
"所以我将要传递这个fraud， 且应创造截距" 

## 截图
![41](https://user-images.githubusercontent.com/31531236/43582510-4a75b9f8-968f-11e8-857f-eee6d2727e87.png)

## 具体描述
视频01：33s处字幕  
"我们需要传递的第一个参数值是反应"  
需改为:  
"我们需要传递的第一个参数值是反应变量"  

## 其实
其实如果中、英双字幕看视频的话，英文字幕会遮挡视频内容，如上2个图，写代码的内容被遮住了。  

觉得如果翻译成中文的话，那些fraud、interception，这些写代码的变量，特定名词，就不要翻译了，保留中文还利于理解；这样只看中文都可以的。  

不然看到中文不知道对应的英文是什么，不知道讲师用的什么变量，又要去双字幕观看，然后视频内容还被遮住了

**Comment by ZenRay** [comment]
这类字幕中变量名称是否可以同意添加括号里面备注例如“fraud(变量名)“，这类问题都比较相同 @Kyliewang
