### ISSUE TITLE
入门 > 课程13案例研究AB测试 > 6.练习实验1

### ISSUE THREAD

**Issue by yao14611** [udacity/DAND-CN-feedback#242]
地址：https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/f3088061-6562-445e-b1a7-a86c9389c2b5/concepts/b17575e2-b06c-418f-89f2-3f601a72e820#

问题：
该小节内容中的workplace中，问题notebook与答案notebook无法一一对应。建议修改答案。

不是下面的练习，是上面的workplace里面的jupyternotebook。

页面刚打开时，截图如下，截图里可以看到题目：
<img width="1254" alt="2018-08-03 10 24 49" src="https://user-images.githubusercontent.com/33114837/43648331-ad4a8350-976c-11e8-9457-7931e965b71a.png">

然后看截图，看solution的名称，有些不一致，不确定是不是截图里的homepage_actions_solution.ipynb文件：

![2018-08-03 10 29 37](https://user-images.githubusercontent.com/33114837/43648723-d0eb12ec-976d-11e8-8912-4229841c72b7.png)

然后打开该文件，发现其中的内容与上面第一章截图里面显示的题目无法对应一致。

![2018-08-03 10 33 32](https://user-images.githubusercontent.com/33114837/43648741-dd777172-976d-11e8-94a2-d6126df3caa0.png)

**Comment by ZenRay** [comment]
@yao14611 你提到的问题 notebook 是指下面的联系吗？另外你提到的不一致是哪个问题上面不一致呢，最好截图说明呢

**Comment by ZenRay** [comment]
修改一些 `solution` 名称以及调整一下其中的内容布置。`homepage_actions_solution` 是该练习的文件

**Comment by Kyliewang** [comment]
没有发现问题哦~ homepage_actions_solution.ipynb是该联系的答案文件。
