### ISSUE TITLE
数据分析进阶>数据整理简介

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#243]
## 课程导航+地址
数据分析进阶>数据整理简介> [17. 练习：评估（整洁度）]https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/90436053-4492-46f7-89ea-7fef32de4bae

## 截图

![image](https://user-images.githubusercontent.com/37874304/43568083-4a0e532c-9666-11e8-97cc-59367970f622.png)

![image](https://user-images.githubusercontent.com/37874304/43568193-88783a60-9666-11e8-9df9-1e56265c0248.png)

## 具体描述
该练习已在16小结中出现，在17小结中重复出现，建议将代码default。

**Comment by ZenRay** [comment]
这里存在一个多余的星号 @Kyliewang 
![image](https://user-images.githubusercontent.com/24636410/43592271-c45bb7a0-96a7-11e8-8788-15a35fdd8b79.png)

**Comment by ZenRay** [comment]
练习内容上是一样的，如果删除建议你将下方的解决方案移动到 16 小节中
