### ISSUE TITLE
数据分析入门>核心课程 4 统计学 >项目：分析A/B测试结果  [1. 项目详情]

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#247]
## 课程导航+地址
入门 > 核心课程 4 统计学 > 项目：分析A/B测试结果 > [1. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/741b37dc-a071-4b47-b925-314943dcb3c2/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/concepts/342cafa6-73f1-4226-b4ed-0171ff5bf81d)

## 截图
![101](https://user-images.githubusercontent.com/31531236/43572412-093e195c-9672-11e8-968b-b9fb48868889.png)

## 具体描述
1.   项目详情介绍里面辅助材料并不在下面，而是在[7. 分析A/B测试结果](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/undefined/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/project)，这个页面里。 但是接下来就是一些测试题，让人摸不着头脑。要不要在提示： 数据在项目提交页面里？ 

2.  “审阅规范”，打开是英文的介绍，有没有中文的审阅规范啊

[7. 分析A/B测试结果](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/undefined/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/project)
## 截图

![102](https://user-images.githubusercontent.com/31531236/43573278-f055c956-9673-11e8-83bc-0e6f66048ff9.png)

## 具体描述

1.   辅助材料，没有梯子，下载不了    

2.  此页面中的“审阅规范”、“审阅标准”也是英文的，不知道有没有影响

**Comment by ZenRay** [comment]
1. 确实缺少辅助材料
2. 所有页面提供的审阅标准都是英文的，需翻译一下 @Kyliewang

**Comment by LeeSkyX** [comment]
@Kyliewang

**Comment by Kyliewang** [comment]
项目审阅标准已经替换。

已经将上方的中文notebook替换成为Notebook+数据文件。
