### ISSUE TITLE
数据分析入门>核心课程 4 统计学 >项目：分析A/B测试结果 [3.练习 测试 2：数据混乱]

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#248]
## 课程导航+地址
入门 > 核心课程 4 统计学 > 项目：分析A/B测试结果 > [3.练习 测试 2：数据混乱](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/741b37dc-a071-4b47-b925-314943dcb3c2/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/concepts/3535df99-d7d1-4c24-816c-4b5586ed9d7a)

## 截图

![131](https://user-images.githubusercontent.com/31531236/43575252-fa2aa898-9678-11e8-8c80-28e5bcd4d1b6.png)

## 具体描述
1.    上面那个框框里的，是不是markdown语法错了

**Comment by LeeSkyX** [comment]
已解决
