### ISSUE TITLE
数据分析入门>核心课程 4 统计学 >项目：分析A/B测试结果 [7.分析 A/B 测试结果]

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#249]
## 课程导航+地址
入门 > 核心课程 4 统计学  > 项目：分析A/B测试结果 > [7.分析 A/B 测试结果](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/741b37dc-a071-4b47-b925-314943dcb3c2/lessons/7b40dff8-3bcd-4145-8dca-d706ae48bd56/project)

## 截图
![171](https://user-images.githubusercontent.com/31531236/43576244-75f82340-967b-11e8-8093-8bf9c5ad7ba0.png)

## 具体描述
1.  这个\**， 语法错误

**Comment by LeeSkyX** [comment]
已解决
