### ISSUE TITLE
数据分析进阶>课程1：什么是EDA>6.电视的增长>标点符号和断句有问题

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#250]
## 截图
![image](https://user-images.githubusercontent.com/41669267/43578202-a261e2f4-9680-11e8-9038-080936c97d69.png)
<img width="1212" alt="demo" src="图片地址"

## 具体描述
“2006 年的电视尺寸中值是多少？ 英寸 电视尺寸的最大增长发生在 年到 年”，前半句问号位置不对，后半句也可优化，建议改成“2006 年的电视尺寸中值是多少英寸？ 电视尺寸的最大增长发生在哪一年到哪一年？”

**Comment by ZenRay** [comment]
课程链接 [练习：电视增长](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785550923)

**Comment by LeeSkyX** [comment]
已解决
