### ISSUE TITLE
数据进阶 > 课程2：R基础> 8练习：RStudio 布局> 错别字

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#251]
## 课程导航+地址
例子：数据进阶 > 课程2：R基础> 8练习：RStudio 布局> 错别字

## 截图
![image](https://user-images.githubusercontent.com/41669267/43580447-130659d4-9688-11e8-9ff3-8d41f1e6aa53.png)

<img width="1212" alt="demo" src="图片地址">

## 具体描述
这个联系假定你使用默认布局，错别字，“联系”应为“练习”

**Comment by LeeSkyX** [comment]
已解决
