### ISSUE TITLE
Safari浏览器兼容性问题

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#252]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43580706-f5b88d1a-9688-11e8-84d7-881cab2fdc6e.png)

## 具体描述
所有workspace在Safari 10.0浏览器中都会变为很窄的一条，无法操作。

**Comment by ZenRay** [comment]
可以直接用手势操作，不用强制使用下拉滚动条。

**Comment by juxingzhutou** [comment]
@ZenRay workspace在Safari下完全无法使用，之前的截图可能容易误解，完整截图如下。

![image](https://user-images.githubusercontent.com/7297350/43585522-ea300978-9697-11e8-8b7c-f7fc70768c65.png)

**Comment by ZenRay** [comment]
你试一下刷新呢，这个不是兼容性问题。我这里没有这个错误

![image](https://user-images.githubusercontent.com/24636410/43585918-dc9777fa-9698-11e8-9ce6-99d89e5905dd.png)

**Comment by juxingzhutou** [comment]
Safari 10.0在Mac 10.12系统下稳定重现，所有workspace都是这样。Chrome下是正常的。

![image](https://user-images.githubusercontent.com/7297350/43586039-25a8a662-9699-11e8-9f7e-e8dc5ea34493.png)

**Comment by ZenRay** [comment]
@juxingzhutou 你升级一下版本。在 11.1.1 下没有这个问题。

**Comment by juxingzhutou** [comment]
我只是提issue，我用Chrome可以正常访问

**Comment by ZenRay** [comment]
😁，jupyter notebook 的文档中也是建议升级到最新版本，它也是兼容 safari 的。这只是一个建议，
