### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 13.阅读CSV文件 【类名不应该翻译】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#253]
## 截图
￼￼
![image](https://user-images.githubusercontent.com/7297350/43585856-b5385670-9698-11e8-9365-649fa6daae8e.png)

## 具体描述

此处的数据框不应该翻译，应该保留Pandas的专门词汇DataFrame

**Comment by ZenRay** [comment]
建议不翻译 @Kyliewang

**Comment by Kyliewang** [comment]
done
