### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 13.阅读CSV文件 【代码与描述不符】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#255]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43586910-77a6c19a-969b-11e8-935f-9769b8f8b061.png)

## 具体描述

此处`header=2`为从0开始的下标，实际应该是使用第3行作为标题

**Comment by ZenRay** [comment]
`header` 确实在读取数据中的第二行作为了标题，但是方便理解还是需要使用“第三行”以免有悖常识

**Comment by LeeSkyX** [comment]
已解决
