### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 14.评估和理解 【技术点描述错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#257]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43588800-dde395ba-969f-11e8-862b-a28287f3fb53.png)

## 具体描述

此处的准确翻译应该是“Pandas实际上将DataFrame中的字符串存储为指针”，notebook中的翻译把关系搞反了。

**Comment by Kyliewang** [comment]
Done
