### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 14.评估和理解   【类名不应该翻译】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#258]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43589193-cadf6362-96a0-11e8-9dab-f43c143bd00b.png)

## 具体描述
此处的DataFrame是Pandas中的类名，不应该翻译。

**Comment by Kyliewang** [comment]
该notebook中已经修改。如果有其他问题欢迎反馈~
