### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 9. 练习：收集（打开 Jupyter Notebook）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#259]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > 9. [练习：收集（打开 Jupyter Notebook）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/a48eb84b-cfe4-4029-8046-bccc8885000f)

## 截图
<img width="561" alt="image" src="https://user-images.githubusercontent.com/1688209/43589253-e35a1ac2-96a0-11e8-8110-18012fa36ea4.png">

## 具体描述
视频1min16s处字幕"可供你下载"，建议改为"你可以在这里看到"

**Comment by ZenRay** [comment]
这里是翻译语句倒装，并没有错误
