### ISSUE TITLE
[youtube 链接错误] [数据分析(入门) - 课程2: 数据类型和云算法 - 7.整数和浮点数,]

### ISSUE THREAD

**Issue by hugo626** [udacity/DAND-CN-feedback#26]
## 课程导航+地址
数据分析(入门) - 课程2: 数据类型和云算法 -[7.整数和浮点数](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/0056decd-35dc-41d0-9d58-22b3752fb20f)

## 截图
![default](https://user-images.githubusercontent.com/1345356/37555377-508e4ad2-2a36-11e8-9698-7b42b73f588f.PNG)
![2](https://user-images.githubusercontent.com/1345356/37555418-b638e9b4-2a36-11e8-9d3d-998259d69227.PNG)

## 具体描述
youtube的视频连接无法播放.

**Comment by Kyliewang** [comment]
已经修改。
