### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 9. 练习：收集（打开 Jupyter Notebook）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#260]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [9. 练习：收集（打开 Jupyter Notebook）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/a48eb84b-cfe4-4029-8046-bccc8885000f)

## 截图
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1688209/43589753-f98f4d20-96a1-11e8-9e4d-7e584a9273a9.png">

## 具体描述
视频1min23s处字幕"PYTHON"，需改为"IPYTHON"

**Comment by ZenRay** [comment]
需要直接把这里的 `python notebook` 删除，因为前面的旁注已经说明了了，这个是多余的 @Kyliewang

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
