### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 10.练习：收集（解压压缩文件）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#261]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [10.练习：收集（解压压缩文件）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/f8b2eabf-42b3-4696-826c-03d2e658c9a7)

## 截图
<img width="585" alt="image" src="https://user-images.githubusercontent.com/1688209/43590058-af6be9e6-96a2-11e8-9895-a2e51d026a70.png">

## 具体描述
视频1min处字幕 创建者，建议改为 构造方法

**Comment by ZenRay** [comment]
这里不是构造方法的意思，而是说使用了是该方法并且传入相应参数这样像“创建”了新的对象。

此外构造方法，是类中的一种特殊方式，负责为该类创建和初始化对象。是两个概念
