### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 12. 练习：收集（导入）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#262]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [12. 练习：收集（导入）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/98e62f46-d741-4f13-9a45-30e3732674b0)

## 截图
<img width="566" alt="image" src="https://user-images.githubusercontent.com/1688209/43590783-67354792-96a4-11e8-965f-12e0cb0a3590.png">

## 具体描述
视频1min41s处字幕 滚动那个按钮，需改为 滚动到页面底部

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
