### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 14.评估和理解 【可读性更高的代码写法】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#263]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43591229-6d4a806a-96a5-11e8-9249-1181e57addcb.png)

## 具体描述

此处给出的写法比stackoverflow中的写法可读性更高

**Comment by Kyliewang** [comment]
赞~
