### ISSUE TITLE
入门 > 数据分析入门 > 播放器音量按钮的体验问题

### ISSUE THREAD

**Issue by sweetorange123** [udacity/DAND-CN-feedback#264]
## 截图
![default](https://user-images.githubusercontent.com/28428954/43593054-80d628f6-96a9-11e8-951c-baa03d13e598.png)
![default](https://user-images.githubusercontent.com/28428954/43593160-b4f8ff6e-96a9-11e8-9f06-a58d55831a48.png)

## 具体描述
火狐浏览器中打开课程，音量按钮只能打开或关闭，无法进行声音大小的调节，也许有个音量调节条会更加方便。

**Comment by ZenRay** [comment]
这个设计就是只能开关音量，而不能调整音量大小。
