### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 15. 练习：评估（可视）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#265]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [15. 练习：评估（可视）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/2483b8b2-0bb0-4e46-b4bc-e243f6325da6)

## 截图
<img width="746" alt="wx20180802-232254 2x" src="https://user-images.githubusercontent.com/1688209/43593777-3ad56464-96ab-11e8-9c8a-e0187ebe72d0.png">

## 具体描述
视频1min21s处字幕 原始招聘的结构，需改为 原始发布的结构

**Comment by ZenRay** [comment]
更改为“原始发布信息的结构”可能更好一些

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
