### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 21.练习：用可视化探索数据 【名称不匹配】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#266]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43595520-771f4f80-96af-11e8-99bb-f16931b439be.png)

## 具体描述

名词解释与数据集的列名很难对上。

**Comment by Kyliewang** [comment]
Done
