### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 > 27.练习：传达结果 【文字描述不够准确】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#269]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43597584-1466d858-96b5-11e8-9194-c3ff028de0a7.png)

## 具体描述

此处的“上个月”应该翻译为“最后一个月”，因为上个月是以当前时间计算的，最后一个月是以数据时间计算的

**Comment by ZenRay** [comment]
确实按实际情况分析，应该使用“上一个月”
