### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 - 案例研究1 > 3.提问 【翻译错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#270]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43599011-c96ded1a-96b8-11e8-8151-7fd3a55d40cd.png)

![image](https://user-images.githubusercontent.com/7297350/43599024-d34e89a2-96b8-11e8-88a6-9bfa185274a9.png)

## 具体描述

第11项特征应该被翻译为“酒精度”

**Comment by LeeSkyX** [comment]
已解决
