### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 7. 模板和软件

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#271]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/b874bab4-a889-441e-bb0b-466370987cf2

## 截图
<img width="1374" alt="udacity_1" src="https://user-images.githubusercontent.com/85287/43621093-499fbbd6-9708-11e8-9ef4-e70b3f96fc3a.png">

## 具体描述
视频44s处字幕XXXX，需改为XXXX 
红框出的翻译，语意不太通顺，可改为：
**这意味着在你离开教室然后回来，你所编写的代码都会被保留（无论是自动还是通过命令或control-S，在你离开前代码都会被保存）**

**Comment by LeeSkyX** [comment]
已解决
