### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 8. 练习：收集(下载）

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#272]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/a1d76a51-4f36-4b60-bb34-d584aed94cc7

## 截图
<img width="1360" alt="udacity_2" src="https://user-images.githubusercontent.com/85287/43621932-470e4280-970c-11e8-8769-86b54d135475.png">

## 具体描述
Scalability的翻译在两处红框处不一致，两处意思虽然差不多，但前后属于说明关系，请保持一致

**Comment by ZenRay** [comment]
按实际情况，建议翻译“可扩展性”

**Comment by Kyliewang** [comment]
@sylviasun916 前后翻译不一致。已修改完成~
