### ISSUE TITLE
数据分析（进阶） > 课程2: R基础 > 12. 练习：R Markdown 文档 [链接不可用]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#273]
## 课程导航+地址
数据分析（进阶） > 课程2: R基础 > [12. 练习：R Markdown 文档](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293190923)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/19308564/43623198-95f91afe-9712-11e8-9a5a-48b326fd99e0.png">

## 具体描述
红框处为YouTube链接，可能需要增加国内可访问链接。

**Comment by ZenRay** [comment]
链接没有错 @Kyliewang

**Comment by Kyliewang** [comment]
修改为国内可访问链接。
