### ISSUE TITLE
数据分析（进阶） > 课程2: R基础 > 12. 练习：R Markdown 文档 [译名错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#274]
## 课程导航+地址
数据分析（进阶） > 课程2: R基础 > [12. 练习：R Markdown 文档](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293190923)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/19308564/43624114-e5d35b0c-9717-11e8-8742-4174c31d740d.png">

## 具体描述
```#``` 即“pound sign/key”、"hash sign/key"或"number sign"，中文一般直接称“井号”。英镑符号应为```£```。

**Comment by ZenRay** [comment]
对于这类难以翻译的专称名次，建议保留原来的英文名称 @Kyliewang 

# 汉语中因形似“井”，通常读作井号，真正的含义是数字符号(Number sign)，如在一些国家‘#1’代表No.1的意思。在美式英语中一般称作pound sign，电话上的“#”叫做pound key，而加拿大英语则称之为number sign key；北美以外的其他英语国家一般称“#”为hash，相应的电话键叫做hash key。 这个是从其他爬下来的，@wszhan

**Comment by LeeSkyX** [comment]
已解决
