### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 14. 评估（简介）

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#275]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/eac0a9d6-a420-4010-a37b-288001d39727

## 截图

<img width="1047" alt="udacity_3" src="https://user-images.githubusercontent.com/85287/43626297-d7be0290-9723-11e8-94ff-9c59c14950cc.png">

## 具体描述
视频44s处字幕『滚动』开始有点没明白，最好能改成：『另外 在Jupter Notebook的单元格中上下滚屏并不是很好用』

**Comment by ZenRay** [comment]
`scrolling` 是网页端是使用网页滚动，可以保留
