### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 14. 评估（简介）

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#276]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/eac0a9d6-a420-4010-a37b-288001d39727

## 截图
<img width="1075" alt="udacity_4" src="https://user-images.githubusercontent.com/85287/43627350-898133ae-9728-11e8-8847-ea9267fb25c7.png">

## 具体描述
译文感觉有些不太准确。
原文为：
Data quality is a perception or an assessment of data's fitness to serve its purpose in a given context. 
建议翻译为：
『数据质量是指在特定的环境下，数据对它所服务的目标是不是合适的一种认知能力或者评估。』

**Comment by Kyliewang** [comment]
感觉翻译没有问题哦~
