### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 16. 练习: 评估（编程）

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#277]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/1ab8bd1a-fc0c-41e8-b5f9-14b6bf637cd5

## 截图
<img width="1212" alt="demo" src="图片地址">
<img width="974" alt="udacity_5" src="https://user-images.githubusercontent.com/85287/43628288-46e87332-972c-11e8-932e-9a8492270a78.png">

## 具体描述
这段描述在我看了英文版后才理解：是指讲师写TODO清单时候的问题。

我建议
1.  加上原英文的内容：
注：在上方视频结束前，评估记录错误地包含进了一个动词：“**修改**非描述性的列标题 （**Fix** nondescriptive column headers.）”。

2.  使用和英文一样的Markdown样式，假如粗体强调和斜体
<img width="943" alt="udacity_6" src="https://user-images.githubusercontent.com/85287/43628521-1a0a8c28-972d-11e8-8122-a6a3c835ae3a.png">

**Comment by ZenRay** [comment]
这里把前后一起看一下就能明白了，重点在记录中需要的是信息描述

**Comment by LeeSkyX** [comment]
已解决
