### ISSUE TITLE
数据分析进阶 > 探索性数据分析>课程2：R基础 > 12.R Markdown文档 > 建议调整文字说明的顺序

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#279]
## 课程导航+地址
例子：数据分析进阶 > 探索性数据分析>课程2：R基础 > 12.R Markdown文档 > 建议调整顺序
## 截图
![image](https://user-images.githubusercontent.com/41669267/43641349-e75428e2-9755-11e8-86b4-b43cfe024340.png)

<img width="1212" alt="demo" src="图片地址">

## 具体描述
“”安装 knitr 包“”建议放在“使用 RMD 文件 What_is_a_RMD_file，跟着 Chris 一起做“后面，因为跟着练习做的时候由于没有安装这个包报错了，应该提示学员先安装这个包，现在的位置不是特别友好。

**Comment by ZenRay** [comment]
建议不错，👍

**Comment by Kyliewang** [comment]
done
