### ISSUE TITLE
【文件不一致】【共享单车项目】bikeshare.py 文件

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#28]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [5. 工作区](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/3a3e0e23-c5b3-4f54-84f9-1eacaaca0dc0)

## 截图
1. Reset 后的工作区：
![image](https://user-images.githubusercontent.com/11519486/37555858-2ab70df6-2a29-11e8-8540-32f80c390a8e.png)

2. 项目详情中下载的 bikeshare.py
![image](https://user-images.githubusercontent.com/11519486/37555863-3bb8024a-2a29-11e8-81d1-39ba0ca604ab.png)

## 具体描述
工作区内的 bikeshare.py 文件与项目详情中下载的 bikeshare.py 文件内容不同，并且工作区的
 bikeshare.py 文件没有 TODO 标识 

@Kyliewang

**Comment by Kyliewang** [comment]
已经修改。

**Comment by ivylee0919** [comment]
@Kyliewang 
工作区内 Reset Data 之后，bikeshare.py 文件还是没有 TODO 标识
