### ISSUE TITLE
数据分析进阶> 收集数据 >10.python中的HTML文件>练习表达有歧义

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#281]
## 课程导航+地址
数据分析进阶> 收集数据 >10.python中的HTML文件>练习表达有歧义https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/390131d9-42ab-48ca-880e-d3f33523c20d

## 截图
<img width="1212" alt="demo" sr
c="图片地址">
![image](https://user-images.githubusercontent.com/37874304/43650585-c0162e52-9772-11e8-84e9-c60becffe43f.png)

## 具体描述
观众得分和观众评分得数，在练习中实际指的是“观众评分”&“参与评分观众人数”；
另外，获取“HTML文件标题”稍微有点歧义，应该是“电影标题”，因为html文件的名字实际上与电影名字不一样，且获取方式也不一样。

**Comment by LeeSkyX** [comment]
已解决
