### ISSUE TITLE
入门或者进阶>课程2 朴素贝叶斯>GaussianNB使用示例  文本翻译

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#283]
## 课程导航+地址
这个2个地方都相同的 ，回顾学过的视频发现的，让我也提交在这里了
机器学习入门 单项课程> 课程2 朴素贝叶斯  > [18. GaussianNB使用示例](https://classroom.udacity.com/courses/ud120/lessons/2254358555/concepts/24307885370923)
机器学习进阶> 2 机器学习基础> 课程5 朴素贝叶斯上手>[13. GaussianNB使用示例](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/4463c984-c2f2-43d6-a618-e6267bcbb4ed/modules/2ecac810-0e17-42ed-8bf7-8c01554b8b11/lessons/5443450881/concepts/24307885370923)
## 截图

![qq 20180804001724](https://user-images.githubusercontent.com/31531236/43653824-d54d7aec-977b-11e8-9b74-06a233a44682.png)

## 具体描述
视频01:06s处字幕：代码中国，需改为代码中间

**Comment by sylviasun916** [comment]
错别字已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
