### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 25. 重新评估和迭代

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#284]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > [25. 重新评估和迭代](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/7ab62eb7-ea12-4181-ae5c-50032a0ae4c3)

## 截图
<img width="903" alt="image" src="https://user-images.githubusercontent.com/1688209/43654169-f98ebd5c-977c-11e8-8c0d-3edea66b01cd.png">

## 具体描述
视频59s处字幕 从从，需改为 从

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
