### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 数据整理简介 > 23. 练习：清洗（练习）

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#285]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 数据整理简介 > 23. [练习：清洗（练习）](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/0bb58475-31aa-4f8d-ad2e-952f137d7fad/lessons/537d8a56-65eb-454b-87a5-5c6ba5fb4ccd/concepts/5ff3a6ff-57dd-4d8c-ad87-7e05ce7b280f)

## 截图
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1688209/43654322-6fa490c0-977d-11e8-9422-5e86ad6b30f7.png">

## 具体描述
第二个视频1min33s处字幕this，需改为这个

**Comment by Kyliewang** [comment]
@sylviasun916 字幕问题，辛苦圆圆修改一下~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
