### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 - 案例研究1 > 14. Pandas Query 【类名不应该翻译】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#286]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43670769-89ad91e8-97c2-11e8-99ee-fc321c59c689.png)

## 具体描述

此处的类名DataFrame不应该翻译为“数据帧”，且即使翻译也与上一课“数据分析过程”中使用的翻译“数据框”不同。

**Comment by LeeSkyX** [comment]
已解决
