### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 - 案例研究1 > 18. Matplotlib示例 【翻译错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#287]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43671185-041051dc-97c8-11e8-97ff-57618c22bb03.png)

## 具体描述

此处的“bar功能”应该翻译为“bar函数”

**Comment by juxingzhutou** [comment]
“xtricks功能”也应该翻译为“xtricks函数”

**Comment by Kyliewang** [comment]
@sylviasun916 function 应当翻译为“函数”，而非“功能”。

**Comment by Kyliewang** [comment]
已经修改。
