### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 - 案例研究1 > 19. 使用Matplotlib绘图 【翻译不容易理解】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#288]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43671464-3474b7a0-97cd-11e8-8ded-9a064586546b.png)

## 具体描述

此处的“pyplot的绘图功能”应该翻译为“pyplot的plot函数”

**Comment by ZenRay** [comment]
翻译问题，可以使用 `plot` 方法来翻译吧——有必要在英文下面更改为 `method`，毕竟这个是类下面的“函数”

**Comment by Kyliewang** [comment]
已经修改。
