### ISSUE TITLE
入门 > 数据分析入门 > 数据分析过程 - 案例研究1 > 5. 评估数据 课程内容和翻译

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#289]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43672602-3373e044-97e4-11e8-95cf-58e1e092ab8d.png)

## 具体描述

本题中有两个“整型”选项，但是一个会提示错误，另一个提示正确。应该是程序设置有问题

**Comment by ZenRay** [comment]
![image](https://user-images.githubusercontent.com/24636410/43683441-4a37c680-98be-11e8-8cfc-f9021f4b5216.png)
同样位置存在语句错误 @Kyliewang

**Comment by LeeSkyX** [comment]
已解决

**Comment by Kyliewang** [comment]
其中一个整型前面多了一个空格，导致正确答案无法匹配。
