### ISSUE TITLE
課程1 2.課程概述 沒有中文字幕

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#29]
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/410ddff6-0f40-4d69-a63d-22094c21350a/concepts/2662994e-0546-48c3-aed5-58f731a1358b

## 截图
![1](https://user-images.githubusercontent.com/27717979/37557109-b1b3c6b2-2a3a-11e8-8781-f7eaa5892c76.PNG)

## 具体描述
無中文字幕

**Comment by Kyliewang** [comment]
字幕已添加
