### ISSUE TITLE
Python入门Numpy&Pandas-第一部分翻译修改

### ISSUE THREAD

**Issue by zknloveu** [udacity/DAND-CN-feedback#293]
## 课程导航+地址
入门课程 > Python入门 > 课程6：Numpy&Pandas-第一部分 >  3.练习：Gapminder数据
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490040923#

## 截图
![image](https://user-images.githubusercontent.com/29766533/43673602-8a893690-97f8-11e8-862b-da1396b09a09.png)

## 具体描述
视频1s处字幕a new dataset，需改为some new datasets。因为它虽然使用的是一个网站的数据，但是是不同数据集。

**Comment by ZenRay** [comment]
这里结合导师发音的，不建议修改。另外这里已经强调了 `new`

**Comment by LeeSkyX** [comment]
已解决
