### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > 课程2：R基础 >13因子变量>“搅拌命令”那缺少步骤、难理解

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#299]
## 课程导航+地址
例子：数据分析（进阶） > 探索性数据分析 > 课程2：R基础 >13因子变量>“搅拌命令”那缺少步骤、难理解

## 截图
![image](https://user-images.githubusercontent.com/41669267/43676078-a81fa300-981c-11e8-9127-565734586b9d.png)

<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频52s处字幕‘运行搅拌命令，我们可以看到这里有很多数据’，但是结合上下文和操作，没看到“在哪里运行了搅拌命令”，作为没接触过R语言的人，这一步会有疑惑。

**Comment by ZenRay** [comment]
这里应该不用翻译，是直接调用改方法命令 `str`

**Comment by Kyliewang** [comment]
@sylviasun916  str并非“搅拌”命令，建议直接保留str。

函数 str(x) 可以查看对象x的结构

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
