### ISSUE TITLE
課程2:5.練習 : 變量和賦值運算符

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#30]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/0edf3cc8-5c35-43a9-bd6e-d410f0ad2978
## 截图
![2](https://user-images.githubusercontent.com/27717979/37557174-a1615454-2a3b-11e8-9933-80d52b4b1e21.PNG)

## 具体描述
不知道是否需要翻譯成中文?!

**Comment by Kyliewang** [comment]
编程者需要有一定的英语技能，这些注释比较简短，词汇不复杂，不需要翻译。
