### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 5. 资料来源：手头文件

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#300]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/beb179b7-41e5-4e93-8bb5-24cf3800bb62

## 截图
![udacity_1](https://user-images.githubusercontent.com/85287/43676849-55041c96-982b-11e8-8b17-60e3432a588e.png)

## 具体描述
热门电影TSV文件下载链接：
https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ca594d_bestofrt/bestofrt.tsv
经测试**如果不翻墙无法下载**

**Comment by Kyliewang** [comment]
已经修改~
