### ISSUE TITLE
Python 入门 > 控制流 > 条件语句 字幕错误

### ISSUE THREAD

**Issue by dedlous** [udacity/DAND-CN-feedback#301]
## 课程导航+地址
Python 入门 > 控制流 > 条件语句 > https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/c2a30770-e445-40c8-bce6-45bb55140544

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/10630180/43677361-574dc2ba-9833-11e8-9018-56bd3375d463.png">

## 具体描述
视频01:36 / 02:03 字幕为If phone balance is five 应该为If phone balance is three

**Comment by Kyliewang** [comment]
@sylviasun916 英文字幕错误，辛苦修改~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
