### ISSUE TITLE
数据分析进阶> 收集数据 >14.python中的文本文件

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#302]
## 课程导航+地址
数据分析进阶> 收集数据 >14.python中的文本文件https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/2f5ac1b6-4a8b-4f39-a0de-769f21837f13

## 截图

![image](https://user-images.githubusercontent.com/37874304/43677973-a5651156-983d-11e8-9928-62966eb11075.png)

![image](https://user-images.githubusercontent.com/37874304/43677974-aef60432-983d-11e8-9c10-6a5ee2694c9c.png)

## 具体描述
在输入与答案相同的代码的时候，实际检验结果报错了。

**Comment by ZenRay** [comment]
文件收集方式是正确的，错误的是两个文件的索引值不一致。建议将`df_solution.pkl` 文件内容修改一下

**Comment by Kyliewang** [comment]
在课程中加入数据错误的提示，需要继续跟进此问题。

**Comment by Kyliewang** [comment]
收到美国同事回复，已经修复，感谢反馈！
