### ISSUE TITLE
数据分析（进阶） >  数据清洗 >  收集数据 > 8.资料来源：Web 数据抓取

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#303]
## 课程导航+地址
数据分析（进阶） >  数据清洗 >  收集数据 > 8.[资料来源：Web 数据抓取](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/c6b16c06-1e05-46c9-b4d2-c36c480e42f4)

## 截图
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1688209/43678018-89394884-983e-11e8-8a49-75b338b05177.png">

## 具体描述
视频19s处字幕 敲击命令或ctrl+s，需改为 敲击command+s或ctrl+s 
因为mac上浏览器保存网页的快捷键是command+s

**Comment by Kyliewang** [comment]
@sylviasun916 command此处为按键名称，不应当翻译为“命令”。

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
