### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 10. Python 中的 HTML 文件

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#304]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 收集数据 > [10. Python 中的 HTML 文件](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/390131d9-42ab-48ca-880e-d3f33523c20d)

## 截图
<img width="571" alt="image" src="https://user-images.githubusercontent.com/1688209/43678189-1ff0b79c-9841-11e8-85fa-31a3cff949ca.png">

## 具体描述
视频3min23s以及3min23s处字幕contents，需改为 .contents

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
