### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 11. Flashforward 1

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#307]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 收集数据 > [11. Flashforward 1](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/97af08a3-5fd1-40cf-be3e-64d801b811b8)

## 截图
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1688209/43678265-e87d693e-9842-11e8-9be6-21c1f2d4b179.png">

## 具体描述
视频2min24s处字幕 较低，需改为 较高

**Comment by ZenRay** [comment]
这里的翻译没有问题，反而是导师提的内容有问题——这里是第三象限的数据，两者都低。这里需要添加注释
