### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 11. Flashforward 1

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#309]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

## 截图
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1688209/43678482-90fa1af0-9846-11e8-8935-62b18af5dd81.png">

## 具体描述
视频1min47s以及1min51s处字幕 百部，需改为 百佳

**Comment by xfzhu2003** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1688209/43678495-d929a37c-9846-11e8-985b-d3368f6ab53e.png">

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
