### ISSUE TITLE
課程2:6.解決方案

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#31]
## 截图
![3](https://user-images.githubusercontent.com/27717979/37557193-f6e3bcd2-2a3b-11e8-87bc-96564e0b937b.PNG)

## 具体描述
(這個翻譯會不會很怪，我一開始都不知道這是答案。) 直接翻譯成 : 解答 不行嗎 哈哈

**Comment by Kyliewang** [comment]
为了与其他课程内容保持一致，此处暂时不做修改。
