### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 17. Python 中的 JSON 文件

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#310]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 收集数据 > [17. Python 中的 JSON 文件](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/8a632dde-1139-4936-8f4e-486d7ea7ae14)

## 截图
<img width="821" alt="image" src="https://user-images.githubusercontent.com/1688209/43678574-675396e8-9848-11e8-9409-d0828467e25a.png">

## 具体描述
视频4s处字幕 评估，需改为 访问

**Comment by Kyliewang** [comment]
@sylviasun916 麻烦圆圆修改~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
