### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 21. 关系数据库结构

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#311]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 收集数据 > [21. 关系数据库结构](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/0a0addb5-3c19-42db-93eb-b7e7d256d69c)

## 截图
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1688209/43678669-32483132-984a-11e8-8500-695b41298063.png">

## 具体描述
视频1min06s处字幕 整体，建议改为 实体

**Comment by Kyliewang** [comment]
@sylviasun916 麻烦修改一下~谢谢！

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
