### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 8. 练习：分面 [文本翻译]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#312]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [8. 练习：分面](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8099892470923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43682221-a870f212-98a0-11e8-96cf-e4d5722a48c5.png)

## 具体描述
facet_wrap()是一个函数，个人建议不用翻译为中文；翻译成中文反而会有点难以理解。

**Comment by sccds** [comment]
同发现这个问题。
另外在这节课的标题，分面，也是比较 confuse 的。根据文档（http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/）更好的翻译可以是，`图面分割`，或者直接写 `Facets (ggplot2)`

**Comment by sccds** [comment]
课程中所有的翻译，基本都是琢面。另有一处：

课程3：探索单一变量 > 24. 练习，频率多边形
![image](https://user-images.githubusercontent.com/6340346/43682728-a2530ac8-98af-11e8-8c5d-b6598f3e8731.png)


https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986400923

**Comment by ZenRay** [comment]
翻译是存在问题，对方法来说还是建议不翻译。另外比较常用的翻译是分面（`Facet`) @Kyliewang

**Comment by Kyliewang** [comment]
@sylviasun916 函数facet_wrap建议不翻译，如果是facet一个单词的话建议翻译为“分面”.

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
