### ISSUE TITLE
数据分析进阶>课程3探索单一变量>3.伪Facebook用户数据 【数据无法下载下载】

### ISSUE THREAD

**Issue by sccds** [udacity/DAND-CN-feedback#314]
## 课程导航+地址
数据分析进阶>课程3探索单一变量>3.伪Facebook用户数据

#### 课程页面链接
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140985970923

#### 数据下载link
https://s3.amazonaws.com/udacity-hosted-downloads/ud651/pseudo_facebook.tsv

## 截图
![image](https://user-images.githubusercontent.com/6340346/43682381-bf2f705a-98a5-11e8-968c-b5c59b190d79.png)

## 具体描述
国内，不用VPN，文件无法下载

**Comment by Kyliewang** [comment]
可支持下载，墙内无问题。
