### ISSUE TITLE
数据分析进阶>课程3探索单一变量>9.异常值和异态 【翻译】

### ISSUE THREAD

**Issue by sccds** [udacity/DAND-CN-feedback#315]
## 课程导航+地址
数据分析进阶>课程3探索单一变量>9.异常值和异态
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986090923

## 截图
课程文字解释链接的翻译：
![image](https://user-images.githubusercontent.com/6340346/43682459-692e0eca-98a8-11e8-8a2c-2e3d5528c8f6.png)

视频课程中的翻译 （这里top-coded翻译为 非常敏感）
![image](https://user-images.githubusercontent.com/6340346/43682476-c1c6db3e-98a8-11e8-8c15-d5ef3b842dd0.png)

## 具体描述
top-coded 根据 wiki 的资料，两处翻译都有问题，但是目前我也不清楚这个该如何翻译。

**Comment by ZenRay** [comment]
目前尚未看见对应的专业术语，建议保留原英文。其他的参考信息是顶端编码，最高化处理。[Top-coded_百度百科](https://baike.baidu.com/item/Top-coded/20154991?noadapt=1)

**Comment by Kyliewang** [comment]
@sylviasun916 Top-coded数据不太容易解释，已经将下方的“居前值经编码”链接修改，建议字幕中也修改为“top-coded”.

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
