### ISSUE TITLE
入门>统计学>[选修] 正态分布理论 8.最大值

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#317]
## 入门>统计学>[选修] 正态分布理论 8.最大值
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/8d483859-93a6-41b7-8011-87ba038faf9e/concepts/487005930923

## 截图
![image](https://user-images.githubusercontent.com/22834601/43682624-d17f65d8-98ac-11e8-9b70-fa57081c6a00.png)

## 具体描述
视频8″公式中的字母写错

**Comment by Kyliewang** [comment]
@sylviasun916 翻译后的符号错误，麻烦圆圆修改~

**Comment by sylviasun916** [comment]
@Kyliewang 
![image](https://user-images.githubusercontent.com/31837843/43988630-742662d2-9d6c-11e8-9f82-d7b778f2eb1e.png)
字幕显示无误，初步判断是播放器显示问题哦 需要工程支持
