### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 评估数据 > 14. 编程评估

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#319]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 评估数据 > [14. 编程评估](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/1165caef-24c9-4a2f-8030-4d6420c0c30a/lessons/243eeaed-5cd8-4e3c-91fa-9131d430138e/concepts/4d4ea0f8-db06-4f6e-9873-3391fb4a0dc4)

## 截图
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1688209/43682660-267dd992-98ae-11e8-9079-577d8b8e360c.png">

## 具体描述
视频1min09s处字幕 样本法，需改为 抽样法

**Comment by ZenRay** [comment]
建议不翻译，这里是 `dataframe` 的 `sample` 方法即`df.sample()`

**Comment by Kyliewang** [comment]
@sylviasun916 翻译优化，建议修改为“Pandas 的一个便捷方法是 DataFrame中的 sample 方法”

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
