### ISSUE TITLE
入门>统计学>[选修] 正态分布理论 10 最小值

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#320]
##入门>统计学>[选修] 正态分布理论 10 最小值
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/8d483859-93a6-41b7-8011-87ba038faf9e/concepts/487511110923

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/22834601/43682662-33fff230-98ae-11e8-8818-3acea7bf2552.png)

![image](https://user-images.githubusercontent.com/22834601/43682666-44fc020e-98ae-11e8-879b-80c3764d7905.png)

## 具体描述
练习题答案我觉得错了，应该是0；练习答案2s中中文字幕重复。

**Comment by Kyliewang** [comment]
@sylviasun916 中文字幕中多次重复，麻烦修改一下哦~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
