### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 评估数据 > 15. 质量：编程评估 1

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#321]
## 课程导航+地址
数据分析（进阶） > 数据清洗 > 评估数据 > [15. 质量：编程评估 1](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/1165caef-24c9-4a2f-8030-4d6420c0c30a/lessons/243eeaed-5cd8-4e3c-91fa-9131d430138e/concepts/49cdc5ad-2f72-4806-9b07-4139c0dea738)

## 截图
<img width="793" alt="image" src="https://user-images.githubusercontent.com/1688209/43682674-7436d0bc-98ae-11e8-8518-b145dd2274e3.png">

## 具体描述
视频20s处字幕 文件，需改为 文档

**Comment by Kyliewang** [comment]
@sylviasun916 这里应该是“文档”并非“文件”，麻烦圆圆修改一下~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
