### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 16. 练习：按性别“划分”的统计学 [错别字]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#323]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [16. 练习：按性别“划分”的统计学](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986240923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43682753-3b542cca-98b0-11e8-9a38-ecfe7a57b9df.png)

## 具体描述
原文为"So as long as we trust half of our values..."，此处应为“一半”。

**Comment by sylviasun916** [comment]
错别字已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
