### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 17. 练习：使用时长 [译名错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#324]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [17. 练习：使用时长](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986270923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43682998-dc22b450-98b5-11e8-9cf9-17de919ba851.png)

## 具体描述
此处应该是对应“theme”的“主题”，而非“模因”（可能是"meme"?)。

**Comment by Kyliewang** [comment]
@sylviasun916 字幕翻译错误，麻烦圆圆修改~

**Comment by sylviasun916** [comment]
错别字已修改！感谢反馈！ （脚本需要一点时间部署 才显示在教室中）
