### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 20. 模因的传播 [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#325]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [20. 模因的传播](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986340923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43683424-07182070-98be-11e8-8c69-7cc8ccf36c51.png)

## 具体描述
原文英文字幕是'names'，中文字幕直接翻译为“姓名”，但讲师应该是在说'meme'，结合下一个视频也确实在讲'meme'。

**Comment by sylviasun916** [comment]
错别字已修改！感谢反馈！ （需要一点时间部署显示在教室中）
