### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 什么是EDA> 1 练习 数据无处不在 > 文本翻译

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#327]
## 课程导航+地址：

https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785460923

## 具体描述【此篇翻译的具体问题主要在断句（部分原断句不符合中文阅读习惯），重复词义和通顺度上，修改句子已括号注明原因】

1
00:00:00,410 --> 00:00:04,150
大家好 欢迎来到探索性数据分析 简称 EDA

2
00:00:04,150 --> 00:00:07,610
过去几个月 在Facebook 就职的朋友帮助下 （已修改，改进通顺度，删除繁复重复词义）

3
00:00:07,610 --> 00:00:10,420
我学习了 R 编程语言以及 EDA 

4
00:00:10,420 --> 00:00:14,410
在本课里 我将讲授如何使用 R 来开展探索性数据分析

5
00:00:14,410 --> 00:00:15,810
EDA是更大的

6
00:00:15,810 --> 00:00:19,010
数据收集、学习及操作流程中的一部分

7
00:00:19,010 --> 00:00:21,350
在本课中 我将分享（已修改，改进通顺度）

8
00:00:21,350 --> 00:00:24,730
我对数据和数据可视化的建议

9
00:00:24,730 --> 00:00:25,640
课程结束时（已修改，改进通顺度）

10
00:00:25,640 --> 00:00:27,930
你会能自信地探索新的数据集

11
00:00:27,930 --> 00:00:31,250
揭示有意义的模式 在最后一课中

12
00:00:31,250 --> 00:00:33,190
我将通过带你完成钻石市场分析（已修改，改进通顺度）

13
00:00:33,190 --> 00:00:36,600
来（学习）建立预测模型（已修改，改进通顺度）

14
00:00:36,600 --> 00:00:38,880
我们非常高兴能教授本课程 （已修改，改进通顺度）

15
00:00:38,880 --> 00:00:42,460
同时向你们展示 如何使用 EDA 回答数据问题（已修改，断句）

16
00:00:42,460 --> 00:00:45,620
在深入学习 EDA 之前 让我们先谈论一下数据 （已修改，改进通顺度）

17
00:00:45,620 --> 00:00:47,900
数据无处不在

18
00:00:47,900 --> 00:00:50,990
你可以在data.gov网站 我们工作的社交网站Facebook上（已修改，改进通顺度、原文信息遗漏）

19
00:00:50,990 --> 00:00:54,650
找到飓风、森林火灾以及国家财政等的相关信息（已修改，修改语序）

20
00:00:54,650 --> 00:00:58,400
比如在Facebook  我们每天收集数千兆字节的数据（已修改，原文未准确翻译千兆）

21
00:00:58,400 --> 00:01:00,780
有些人已经开始使用日历、手机应用以及身体活动跟踪器（已修改，改进通顺度）

22
00:01:00,780 --> 00:01:04,540
来追踪个人数据（已修改，改进通顺度）

23
00:01:05,810 --> 00:01:07,290
这个世界充满了大量数据

24
00:01:07,290 --> 00:01:10,530
而我们已探知的数据犹如沧海一粟（已修改，改进通顺度）

25
00:01:10,530 --> 00:01:12,970
比如 有一天我在 Google 趋势上闲逛

26
00:01:12,970 --> 00:01:16,080
有了一个发现（已修改，改进通顺度）

27
00:01:16,080 --> 00:01:17,940
我搜索了鸡肉这个词  因为（已修改，断句）

28
00:01:17,940 --> 00:01:21,580
当天早上 我读了一则关于鸡肉中毒和沙门氏菌的文章（已修改，改进通顺度，断句）

29
00:01:21,580 --> 00:01:24,050
当我搜索这个词时 Google 趋势显示了这幅图（已修改，改进通顺度）

30
00:01:24,050 --> 00:01:27,710
这张图显示出搜索鸡肉一词的兴趣（已修改，改进通顺度）

31
00:01:27,710 --> 00:01:30,650
随时间的变化 实际上它计算了（已修改，改进通顺度）

32
00:01:30,650 --> 00:01:33,280
给定月份下 所有报纸标题中 出现鸡肉的次数 （已修改，改进通顺度）

33
00:01:33,280 --> 00:01:38,380
所以 从2005到2013年 （已修改，改进通顺度）

34
00:01:38,380 --> 00:01:42,070
我们看到鸡肉出现的次数在增加 （已修改，transcript文档误翻译为减少, 视频中中文字幕为增加）

35
00:01:42,070 --> 00:01:44,480
我不想就此停止搜索 （已修改，改进通顺度）

36
00:01:44,480 --> 00:01:48,290
我决定再输入两个普通词语 看看结果 （已修改，断句改进通顺度）

37
00:01:48,290 --> 00:01:51,620
我添加了 音乐 和 电影 （已修改，改进通顺度）

38
00:01:51,620 --> 00:01:54,170
然后得到这张图 现请你来看这幅图 （已修改，改进通顺度）

39
00:01:54,170 --> 00:01:57,840
告诉我你注意到什么

40
00:01:57,840 --> 00:02:01,120
你可以讨论任何有趣的发现 （已修改，改进通顺度）

41
00:02:01,120 --> 00:02:04,150
也可以与第一幅图对比 记下你的发现

42
00:02:04,150 --> 00:02:07,134
请记住 此题答案没有对错 （已修改，改进通顺度）

43
00:02:07,134 --> 00:02:09,460
我只是想让你开始思考数据

**Comment by sylviasun916** [comment]
感谢优化建议！ 部分已采纳并修改，需要一点时间部署显示在教室中
