### ISSUE TITLE
数据分析进阶 > 探索性数据分析  >  什么是EDA> 1 练习 数据无处不在 习题解答  翻译改进

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#328]
## 课程导航+地址
数据分析进阶 > 探索性数据分析  >  什么是EDA> 1 练习 数据无处不在 习题解答 [https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785460923](url)

## 具体描述
具体描述【此篇翻译的具体问题主要在断句（部分原断句不符合中文阅读习惯），重复词义和通顺度上，修改句子已括号注明原因】

1
00:00:00,780 --> 00:00:03,400
对于此图 你可以做出无数个观察结论

2
00:00:03,400 --> 00:00:06,460
你可能讲出图形中的某个特别的点 （已修改，提高准确度，英文没有提及峰值）

3
00:00:06,460 --> 00:00:10,450
或者讲出它的大概趋势（已修改，改进通顺度，提高准确度）

4
00:00:10,450 --> 00:00:13,890
我注意到的是 垂直刻度发生的变化 （已修改，改进通顺度，删除重复语义）

5
00:00:13,890 --> 00:00:17,370
因为蓝线一直向下到达底部

6
00:00:17,370 --> 00:00:19,810
这意味着 我们在报纸标题中看到音乐和电影的次数 （已修改，改进通顺度，准确度）

7
00:00:19,810 --> 00:00:22,770
远大于我们看到鸡肉一词的次数

8
00:00:22,770 --> 00:00:25,860
我还注意到 过去 音乐一词在标题中的使用非常普遍 （已修改，改进通顺度，准确度）

9
00:00:25,860 --> 00:00:28,300
但最近几年有所下降（已修改，改进通顺度）

10
00:00:28,300 --> 00:00:32,034
事实上 电影一词在标题中的使用次数 （已修改，改进通顺度，语序）

11
00:00:32,034 --> 00:00:36,110
大概在2010年6月 就超过了音乐 （已修改，改进通顺度）

12
00:00:36,110 --> 00:00:38,290
在静态图像上 这也许不明显 （已修改，改进通顺度）

13
00:00:38,290 --> 00:00:40,500
但如果使用交互可视化方法 （已修改，改进通顺度，准确度）

14
00:00:40,500 --> 00:00:43,160
你也许会发现日期和其它有趣的方面 （已修改，改进通顺度）

15
00:00:43,160 --> 00:00:45,090
在本解答视频中 如果你发现了答案没有覆盖的方面 （已修改，改进通顺度）

16
00:00:45,090 --> 00:00:47,100
请在论坛中分享你的问题 （已修改，改进通顺度）

**Comment by sylviasun916** [comment]
感谢优化建议！ 针对准确性部分已部分采纳并作修改，需要给脚本一点时间部署显示在教室中
