### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 什么是EDA> 3 练习 为何要学习EDA 翻译

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#329]
数据分析进阶 > 探索性数据分析 > 什么是EDA> 3 练习 为何要学习EDA [https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785490923](url)

## 截图
具体描述【此篇翻译的具体问题主要在断句（部分原断句不符合中文阅读习惯），重复词义和通顺度上，修改句子已括号注明原因】

1
00:00:00,820 --> 00:00:02,130
你可能会疑惑 （已修改，改进通顺度）

2
00:00:02,130 --> 00:00:04,780
为什么要在一开始学习探索性数据分析  （已修改，改进通顺度）

3
00:00:04,780 --> 00:00:07,910
Hal Varian 是 Google 的“廉价”经济学家

4
00:00:07,910 --> 00:00:11,940
他说 什么东西正变得无处不在而且廉价？

5
00:00:11,940 --> 00:00:14,890
-- 数据 那么什么是数据的补充？ （已修改，改进通顺度）

6
00:00:14,890 --> 00:00:19,010
-- 分析 一般而言 探索性数据分析或者EDA  （已修改，改进通顺度，断句）

7
00:00:19,010 --> 00:00:22,660
是通过数字的和图形方法 （已修改，改进通顺度，符合中文语序）

8
00:00:22,660 --> 00:00:27,330
对数据以及变量间关系的研究 （已修改，改进通顺度，符合中文语序）

9
00:00:27,330 --> 00:00:30,000
通常发生在更正式 （已修改，改进通顺度）

10
00:00:30,000 --> 00:00:33,720
和更严格的统计分析之前 （已修改，改进通顺度）

11
00:00:33,720 --> 00:00:36,200
EDA 通常是更大的分析过程中的第一步 （已修改，改进通顺度）

12
00:00:36,200 --> 00:00:39,460
可以让你 提出见解 发现新问题 （已修改，改进通顺度 断句）

13
00:00:39,460 --> 00:00:42,690
甚至为构建预测模型打下基础 

14
00:00:42,690 --> 00:00:45,300
EDA 也是防御不良数据的重要一关 （已修改，改进通顺度）

15
00:00:45,300 --> 00:00:48,020
它还让你有机会检验你对数据集的 （已修改，改进通顺度）

16
00:00:48,020 --> 00:00:50,720
一些假设和直觉 （已修改，改进通顺度）

17
00:00:52,150 --> 00:00:55,570
很多时候 商业决策的得出 使用的是未经加工的 （已修改，改进通顺度）

18
00:00:55,570 --> 00:00:59,270
来自探索性数据分析的可视图 （已修改，改进通顺度）

19
00:00:59,270 --> 00:01:01,910
有时候 你也可以打磨加工这些可视图和结论后 （已修改，改进通顺度）

20
00:01:01,910 --> 00:01:03,850
再呈现给更多受众 （已修改，改进通顺度）

21
00:01:03,850 --> 00:01:08,500
让我们听听 Chris 的一个示例 （已修改，改进通顺度）

22
00:01:08,500 --> 00:01:11,050
看看 EDA 能如何融入 （已修改，改进通顺度）

23
00:01:11,050 --> 00:01:14,780
更庞大的预测模型构建的流程

24
00:01:14,780 --> 00:01:18,660
 Netflix 大奖赛是一个很好的 EDA 示例 （已修改，改进通顺度，符合中文语序）

25
00:01:18,660 --> 00:01:21,480
竞争团队 要将 Netflix 影片推荐系统 至少提高10% （已修改，改进通顺度，符合中文语序）

26
00:01:21,480 --> 00:01:25,130
以争夺百万美金大奖 （已修改，改进通顺度，符合中文语序）

27
00:01:25,130 --> 00:01:28,100
若想了解竞赛详情及结果 （已修改，改进通顺度）

28
00:01:28,100 --> 00:01:29,910
请点击讲师注释中的链接 （已修改，改进通顺度）

29
00:01:31,200 --> 00:01:33,820
这个可视化由 Todd Holloway 创建 

30
00:01:33,820 --> 00:01:37,310
它根据电影评分 显示电影集群 （已修改，改进通顺度）

31
00:01:37,310 --> 00:01:41,200
彼此接近的电影 获得的电影评分相近  （已修改，改进通顺度）

32
00:01:41,200 --> 00:01:43,780
不论评分高低 （已修改，改进通顺度）

33
00:01:43,780 --> 00:01:46,180
正是这类可视化 让我们可以感受数据 （已修改，改进通顺度）

34
00:01:46,180 --> 00:01:48,210
确定哪些可以包含其中 

35
00:01:48,210 --> 00:01:50,660
哪些还可以更深入地研究

36
00:01:50,660 --> 00:01:53,800
所以 即使在对数据进行复杂数据分析之前 （已修改，改进通顺度）

37
00:01:53,800 --> 00:01:57,800
我们也可以通过可视化  了解数据的很多方面 （已修改，改进通顺度）

38
00:01:57,800 --> 00:02:02,540
Nathan Yau 一位知名的统计学家和可视化权威 （已修改，guru此处应该翻译成权威 专家）

39
00:02:02,540 --> 00:02:05,780
介绍了他对这幅可视图的思考 你也可以从讲师注释中

40
00:02:05,780 --> 00:02:08,560
阅读他的观点 查看了解交互式可视化 （已修改，改进通顺度）

41
00:02:09,570 --> 00:02:11,940
所以 无论你是想学习一种急缺技能 （已修改，in-demand 此处翻译成急缺更贴切）

42
00:02:11,940 --> 00:02:15,560
还是想参加百万美金竞赛 EDA 都能使你受益 （已修改，改进通顺度）

43
00:02:15,560 --> 00:02:18,770
至少 学习 EDA 将

44
00:02:18,770 --> 00:02:22,030
提升你的数据推理能力 提高沟通技能 （已修改，改进通顺度）

45
00:02:22,030 --> 00:02:26,330
并扩展你的职业机会

46
00:02:26,330 --> 00:02:27,980
现在 我希望大家花几分钟时间回忆一下

47
00:02:27,980 --> 00:02:32,260
你以前的工作经验 及教育经历 （已修改，改进通顺度）

48
00:02:32,260 --> 00:02:34,930
写下几条你想学习 EDA 的原因

49
00:02:34,930 --> 00:02:36,670
写下来以后

50
00:02:36,670 --> 00:02:39,540
在论坛中分享你的想法和经验

51
00:02:39,540 --> 00:02:41,090
记住 答案无所谓对错

52
00:02:41,090 --> 00:02:43,050
这个问题只是让你自己思考

**Comment by sylviasun916** [comment]
感谢优化的建议！ 已部分采纳并在字幕库中修改。（需要一点时间部署显示在教室中）
