### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > R基础 > 9. 练习：揭秘R

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#330]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 > R基础 > [9. 练习：揭秘R](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293140923)

## 截图
<img width="931" alt="image" src="https://user-images.githubusercontent.com/1688209/43685147-012634aa-98e0-11e8-872e-d7cd84d2638c.png">

## 具体描述
视频49s处字幕 备注，需改为 注释

**Comment by ZenRay** [comment]
注释和备注两个都可以
