### ISSUE TITLE
数据分析进阶>课程3探索单一变量>27.练习箱线图四分位和友谊 【翻译】

### ISSUE THREAD

**Issue by sccds** [udacity/DAND-CN-feedback#331]
## 课程导航+地址
数据分析进阶>课程3探索单一变量>27.练习箱线图四分位和友谊

https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986500923

## 截图
![image](https://user-images.githubusercontent.com/6340346/43685290-d9202cec-98e2-11e8-9303-33e3cabe5180.png)

## 具体描述
课程的题目，“友谊”在这里不妥，可能课程中想说数据中分析友谊情况，应该说明

**Comment by Kyliewang** [comment]
修改为“好友分析中的箱线图、四分位数”。
