### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > R基础 > 16. 数据加工

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#332]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 > R基础 > [16. 数据加工](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293290923)

## 截图
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1688209/43685303-f692188a-98e2-11e8-9fe9-6e8d172b7054.png">

## 具体描述
视频44s处字幕 缠斗，需改为 整理

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （需要一点时间部署显示在教室中）
