### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 什么是EDA> 4 Aude对数据的兴趣 翻译 英语字幕疑似错误

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#333]
数据分析进阶 > 探索性数据分析 > 什么是EDA> 4 Aude对数据的兴趣https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/9030385460923

具体描述【此篇翻译的具体问题主要在断句（部分原断句不符合中文阅读习惯），重复词义和通顺度上，修改句子已括号注明原因】

1
00:00:00,360 --> 00:00:02,060
在编写本课时

2
00:00:02,060 --> 00:00:04,380
我和 Dean Warren Solomon 一起访问了 Facebook

3
00:00:04,380 --> 00:00:08,310
并与很多数据科学家交谈 我们了解很多关于 EDA 的内容

4
00:00:08,310 --> 00:00:11,680
我很高兴在课程中与大家分享这些故事 首先你将听到

5
00:00:11,680 --> 00:00:15,780
Aude 谈论 她作为数据科学家 发现的最有趣的事情  （已修改，语序 改进通顺度）

6
00:00:15,780 --> 00:00:21,408
我真正喜欢的是 能够从现实世界中 （已修改，英语字幕错误？？这里的英语是Rita wrote, 但是上下文章都没有提到Rita而且听起来像real world）

7
00:00:21,408 --> 00:00:26,400
收集数十亿和数万亿行的数据 你不知道对哪些感兴趣 （已修改，语序 改进通顺度）

8
00:00:26,400 --> 00:00:29,024
好似庞然大物 你需要也必须

9
00:00:29,024 --> 00:00:32,058
钻研 理清可能感兴趣的数据

10
00:00:32,058 --> 00:00:35,174
然后尝试 （已修改，语序 改进通顺度）

11
00:00:35,174 --> 00:00:39,372
以多种不同的方法来研究 （已修改，语序 改进通顺度）

12
00:00:39,372 --> 00:00:42,063
有时用图表 有时使用地图 （已修改，删减  改进通顺度）

13
00:00:42,063 --> 00:00:46,065
碰到感兴趣的内容 （已修改，删减  改进通顺度）

14
00:00:46,065 --> 00:00:51,480
就想更深入一点地挖掘 （已修改，删减  改进通顺度）

15
00:00:51,480 --> 00:00:53,970
最终 找到有意思的内容 （已修改，漏翻  改进通顺度）

16
00:00:53,970 --> 00:00:58,340
我们就会开发出相应的算法 （已修改， 改进通顺度）

17
00:00:58,340 --> 00:01:03,000
为的是 可以更了解我们的世界 （已修改，漏翻  改进通顺度）

18
00:01:03,000 --> 00:01:06,070
或者改进 Facebook 产品 （已修改 语序  改进通顺度）

19
00:01:06,070 --> 00:01:09,730
从面对数据无从下手  到 （已修改 语义 语序  改进通顺度）

20
00:01:09,730 --> 00:01:13,290
（ 利用数据 ） 更加了解移动性 （已修改 语义  改进通顺度）

21
00:01:13,290 --> 00:01:17,010
或者改进 Facebook （已修改 语义  断句 符合中文阅读习惯）

22
00:01:17,010 --> 00:01:18,010
这真是一个非常棒的工作流程 （更改断句 符合中文阅读习惯）

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
