### ISSUE TITLE
数据入门>课程3>11页面问题

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#334]
## 课程导航+地址
入门>课程3>[11](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/5a16ac08-fec2-475e-98d2-510611301aaf)

## 截图
![3](https://user-images.githubusercontent.com/7417557/43686049-cf86dd7a-98f1-11e8-9856-6403689d23ad.png)

## 具体描述
建议10和11的页面合并，11单独这个页面太突兀了
同样适用于之后的练习

**Comment by ZenRay** [comment]
这个是整个课程排布，可以看有必要调整吗 @Kyliewang
