### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 什么是EDA> 5 EDA [的目标] 术语 词义翻译错误

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#335]
数据分析进阶 > 探索性数据分析 > 什么是EDA> 5 EDA [的目标](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785540923)

1
00:00:00,750 --> 00:00:04,230
那么 到底什么是探索性数据分析呢？（已修改，语义）

2
00:00:04,230 --> 00:00:06,670
你可以在讲师注释中查看维基百科的定义

3
00:00:06,670 --> 00:00:09,750
但简而言之 探索性数据分析就是 （已修改，语义，改进通顺度）

4
00:00:09,750 --> 00:00:14,710
使用可视化和统计工具 来理解数据的一种方法 （已修改，语序 改进通顺度）

5
00:00:14,710 --> 00:00:18,050
采用 EDA  来与你的数据初次互动 （已修改，语义 改进通顺度）

6
00:00:18,050 --> 00:00:19,670
例如 我们想研究汽车 （已修改，改进通顺度）

7
00:00:19,670 --> 00:00:22,080
研究数据来自 MT 汽车数据集 （已修改，断句 改进通顺度）

8
00:00:22,080 --> 00:00:24,480
此数据在R studio 可得 （已修改，视频字幕中写的是R STUDIO 下载的文字字幕显示our studio）

9
00:00:25,550 --> 00:00:27,970
目前 单凭通读此表格 我们无法得出任何形式的结论 （已修改，语序，断句改进通顺度）

10
00:00:27,970 --> 00:00:31,020
这非常难 （已修改，语序，断句改进通顺度）

11
00:00:31,020 --> 00:00:32,740
所以 我们想做的是 （已修改，改进通顺度）

12
00:00:32,740 --> 00:00:36,070
了解一些变量的分布 （已修改，改进通顺度）

13
00:00:36,070 --> 00:00:40,580
比如 每加仑英里数 气缸数 可能还有马力 （已修改，改进通顺度）

14
00:00:40,580 --> 00:00:43,440
我们可以创建直方图 在后面的第三课会看到 （已修改，改进通顺度）

15
00:00:43,440 --> 00:00:45,890
这个直方图显示了所有汽车的重量分布 （已修改，词义，weight在此应该是指汽车重量不是权重）

16
00:00:45,890 --> 00:00:51,330
或者 我们可以研究变量之间的相关性 （已修改，术语 correlation: 相关性）

17
00:00:51,330 --> 00:00:54,000
比如 每加仑英里数和马力的关系 （已修改，改进通顺度）

18
00:00:54,000 --> 00:00:56,740
在这种情况下 我们可能会创建一个散点图 （已修改 改进通顺度）

19
00:00:56,740 --> 00:01:00,100
这些将在第四课内探讨 我们的第二个目标是 (已修改 改进通顺度）

20
00:01:00,100 --> 00:01:04,099
评估和验证假设 未来推断也将基于此假设验证  (已修改 语序 改进通顺度）

21
00:01:04,099 --> 00:01:07,030
因此 我们也许会问 哪些变量 (已修改 改进通顺度）

22
00:01:07,030 --> 00:01:10,590
是呈正态分布的 或者我们想知道 (已修改 改进通顺度）

23
00:01:10,590 --> 00:01:13,600
某变量是否偏向一个特殊值 (已修改 改进通顺度）

24
00:01:13,600 --> 00:01:16,408
我们的汽车数据集可能不是这种情况 (已修改 改进通顺度）

25
00:01:16,408 --> 00:01:19,683
但在其它案例中 比如网络社交行为或者用户互动等 (已修改 改进通顺度）

26
00:01:19,683 --> 00:01:22,560
你会发现这一点

27
00:01:22,560 --> 00:01:24,550
第三 你可能需要先了解数据 

28
00:01:24,550 --> 00:01:27,560
再提出合理的假说 (已修改 改进通顺度）

29
00:01:27,560 --> 00:01:30,140
那么 EDA 也许是你试验想法的来源  (已修改 语义 改进通顺度）

30
00:01:30,140 --> 00:01:32,160
它不是一个假说测试和预测建模的正式流程  (已修改 语义 改进通顺度）

31
00:01:32,160 --> 00:01:35,190
最终 我们会对数据集 形成直觉   (已修改 语义 改进通顺度）

32
00:01:35,190 --> 00:01:37,570
并且知道这直觉是怎么产生的 (已修改 改进通顺度）

33
00:01:37,570 --> 00:01:41,560
通过探索数据 我们可以提出更好的假说 (已修改 语义 改进通顺度）

34
00:01:41,560 --> 00:01:45,560
确定哪些变量有最大的预测能力 (已修改 改进通顺度）

35
00:01:45,560 --> 00:01:48,870
然后选择合适的统计工具 来建立我们的预测模型 (已修改 语义 改进通顺度）

**Comment by Kyliewang** [comment]
@agnesyan 同学你好，感谢您对字幕进行校正。能够麻烦提供一下“术语 词义翻译错误”的具体位置吗？

在今后提交issue的时候，建议不要直接提供修改后的字幕文本。我们更希望能够看到修改前后的对比版本（最好能够附上修改原因）。感谢配合~

**Comment by agnesyan** [comment]
Hello

术语是在这个时间段
00:00:45,890 --> 00:00:51,330
45秒 - 51秒
或者 我们可以研究变量之间的相关性 （已修改，术语 correlation: 相关性）

群里一个同学推荐的文本对比软件很好用 -- Beyond Compare  导入原文本 修改文本 它就会会自动对齐时间轴
再对比文本，我传的文本时间轴都没动过。

这个翻译是基于每一节课下载的transcript 改的， 但是我发现网页版本的内嵌字幕 与下载版本的字幕并不完全一样，不知道什么原因

只要修改过 每一句的原文修改原因 都标注在括号里了（通顺度 语序 词义 删减重复词义 符合中文表达习惯等），没改过的后面没有括号。

**Comment by Kyliewang** [comment]
@sylviasun916 
43秒处“权重”改为“重量”
50秒处“关联度”改为“相关性”
感谢~

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （需要一点时间部署显示在教室中）
