### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 15. 资料来源：API(应用程序编程接口)

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#336]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/dd0877f5-f3e7-4fab-869a-126e89ce944b

## 截图
![udacity_2](https://user-images.githubusercontent.com/85287/43686383-6bd2d68e-98f7-11e8-9239-e758fe73c51a.png)

## 具体描述
红方框中的翻译不够准确，**important takeaway** 建议翻译成 **重要的经验**

**Comment by ZenRay** [comment]
[API:首页 - MediaWiki](https://www.mediawiki.org/wiki/API:Main_page/zh) 建议调整一下这一块的翻译，这个网站提供了中文版本

**Comment by Kyliewang** [comment]
已经修改~
