### ISSUE TITLE
[数据分析入门] 课程12 假设检验 13 在两种假设中如何选择？

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#337]
## 课程导航+地址
例子：入门 > 课程12 假设检验 > [13. 在两种假设中如何选择？](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/ad8aca80-f444-4479-8848-5b07bafaf66c/concepts/f7c0b643-82b1-44ca-ab0d-a2907fd5a4ff)

## 截图

![image](https://user-images.githubusercontent.com/24636410/43686363-24352804-98f7-11e8-894b-953693b05181.png)

## 具体描述
根据假设来看，这里是一个单尾检验。按照 alpha 为 0.5 的情况下，这里的百分位数计算上下界的时候是否应该用 `low, upper = np.percentile(means, 5), np.percentile(means, 95) `

**Comment by agnesyan** [comment]
刚好看到你贴的这个，学过 有点印象， 这是个双尾检验，置信度95%，左右两边各是a/2 = 0.25, 所以视频里应该是对的 low, upper = np.percentile(means, 2.5), np.percentile(means, 97.5)

**Comment by ZenRay** [comment]
@agnesyan 双尾检验的时候，假设是 H0: mu = 70

**Comment by agnesyan** [comment]
@ZenRay 嗯嗯 按题目来开是单尾验证 氮素他好像说这里是用置信区间的方法先做一遍 后面再做模拟0假设 ？是这样吗？

**Comment by LeeSkyX** [comment]
@Kyliewang

**Comment by Kyliewang** [comment]
此处我认为没有问题，因为这里没有说明alpha的取值，这样计算ok。
