### ISSUE TITLE
入门 > 控制流 > 练习：条件布尔表达式 练习无法提交答案

### ISSUE THREAD

**Issue by dedlous** [udacity/DAND-CN-feedback#339]
## 课程导航+地址
入门 > 控制流 > 练习：条件布尔表达式 
(https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/69bfbde2-3f63-41ed-8793-aabf0f6a4bab)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/10630180/43685921-1d15eab6-98ef-11e8-9a18-b2962d588273.png">

## 具体描述
这道题目怎么提交答案？没有办法输入true 或者 false

**Comment by ZenRay** [comment]
这里是需要拖拽的，不需要输入
