### ISSUE TITLE
課程2:數據類型和運算 12. 練習:字符串 

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#34]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/a9fa5602-6d7c-4e8a-b3e3-58b481798ab0

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
 按下第一題的測試答案，整個頁面會往下跑

**Comment by ChengGoooo** [comment]
这是一个中文版教室的 bug，还有一个 bug 是，点开一页含有多个视频的页面，会自动跳到最底下一个视频。
