### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 什么是EDA> 9 课程概述 翻译问题

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#340]
## 课程导航+地址
数据分析进阶 > 探索性数据分析 > 什么是EDA>[ 9 课程概述](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569241/concepts/8245785590923)

具体描述【此篇翻译的具体问题主要在断句（部分原断句不符合中文阅读习惯），重复词义和通顺度上，修改句子已括号注明原因】

1
00:00:00,250 --> 00:00:03,750
这样的可视化 是探索性数据分析的核心部分 （已修改，词义 改进通顺度）

2
00:00:03,750 --> 00:00:06,840
我们将使用 R 编程语言 

3
00:00:06,840 --> 00:00:09,756
来创建这些类型的可视化 （已修改，改进通顺度）

4
00:00:09,756 --> 00:00:12,340
用于整个课程中的数据探索  （已修改，改进通顺度）

5
00:00:12,340 --> 00:00:15,510
想要详细了解 R 编程语言及其开发 （已修改，语序 符合中文表达 改进通顺度）

6
00:00:15,510 --> 00:00:18,773
只需点击讲师注释中的链接即可  （已修改，语序 符合中文表达 改进通顺度）

7
00:00:18,773 --> 00:00:22,380
我们还将学习 RStudio  就是这个程序 这是一个 （已修改，改进通顺度）

8
00:00:22,380 --> 00:00:25,410
R 语言下的图形用户界面 下一课中 你会全面学习 RStudio （已修改，改进通顺度）

9
00:00:25,410 --> 00:00:29,010
未来的课程 将涵盖用于数据探索的可视化和统计方法 （已修改，改进通顺度）

10
00:00:29,010 --> 00:00:33,040
首先 我们会一次研究数据集中的一个变量 （已修改，语义 改进通顺度）

11
00:00:33,040 --> 00:00:35,600
这样 我们就了解了（已修改，语义 改进通顺度）

12
00:00:35,600 --> 00:00:38,660
数据集变量的基础分布以及变量呈现的值的类型（已修改，语义 改进通顺度）

13
00:00:38,660 --> 00:00:42,040
最后 我们的可视化将更加复杂（已修改，语义 改进通顺度）

14
00:00:42,040 --> 00:00:45,390
我们将一次考察成对的变量（已修改，语义 改进通顺度）

15
00:00:45,390 --> 00:00:47,880
以及多个变量

16
00:00:47,880 --> 00:00:50,460
课程结束时 你将有机会开展自己的（已修改  改进通顺度）

17
00:00:50,460 --> 00:00:53,880
探索性数据分析 我希望你能乐于

18
00:00:53,880 --> 00:00:56,020
探索数据 下节课再见 （已修改，改进通顺度）

**Comment by sylviasun916** [comment]
已修改！感谢反馈优化建议！ （需要一点时间部署显示在教室中）
