### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 收集数据 > 23. 其他文件格式

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#345]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/aef902cd-59a3-4cd2-af74-2d39b4b03b80/lessons/96402d84-c99d-4982-9edf-2430ef30d222/concepts/6759e3cf-a7c4-4d9a-ac58-9aed785bd67b

## 截图
![udacity_6](https://user-images.githubusercontent.com/85287/43687164-49fca696-9903-11e8-9af8-f306c6e267ba.png)

## 具体描述
HDF5 文件的链接是无效的 （英文版也存在同样的问题）

打开链接：

![udacity_7](https://user-images.githubusercontent.com/85287/43687193-c6cd0e04-9903-11e8-9999-0f8257debf61.png)

**Comment by Kyliewang** [comment]
链接已替换
