### ISSUE TITLE
数据分析进阶 评估数据 6.评估：类型与步骤【翻译有误】

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#347]
## 课程导航+地址
数据分析进阶 评估数据 6.评估：类型与步骤https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/1165caef-24c9-4a2f-8030-4d6420c0c30a/lessons/243eeaed-5cd8-4e3c-91fa-9131d430138e/concepts/353d5119-9662-4a68-b791-b1a9ad32c0c2

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
46s处的中文翻译里面"df.inf"应该是"df.info"

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （需要一点时间部署显示在教室中哦）
