### ISSUE TITLE
数据分析（进阶）> 探索性数据分析 > 课程3：探索单一变量 >3.伪 Facebook 用户数据>翻译缺少标点符号

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#348]
## 课程导航+地址
例子：数据分析（进阶）> 探索性数据分析 > 课程3：探索单一变量 >3.伪 Facebook 用户数据>翻译缺少标点符号

## 截图
![image](https://user-images.githubusercontent.com/41669267/43698854-ae671726-997e-11e8-8cd2-019057d1a4ea.png)

## 具体描述
视频1分26处字幕‘friend_counts www_likes和’，前两个之间缺少逗号，需改为‘friend_counts，www_likes和’

**Comment by sylviasun916** [comment]
建议已采纳 中间添加一个顿号方便理解！感谢反馈！ （需要一点时间部署显示在教室中）
