### ISSUE TITLE
課程2:數據類型和運算符 13. 練習:類型和類行轉換 

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#35]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/c0fc67d1-178b-4162-8c79-e4c834d1d5d3

## 截图
![wechat _20180318231602](https://user-images.githubusercontent.com/27717979/37567466-5e754570-2b02-11e8-9312-3d1364fb48b7.png)

## 具体描述
影片無中文字幕

**Comment by Kyliewang** [comment]
已经修复。
