### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 24. 练习：频率多边形 [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#350]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [24. 练习：频率多边形](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986400923)

## 截图

![image](https://user-images.githubusercontent.com/19308564/43701244-0aa3fcf8-9988-11e8-8f96-759f371083ac.png)

## 具体描述
在34秒处，结合视频后面的内容，讲师应该是说“remove any values for gender that are **NA**"而不是"in a"，此处中英文都应修改。

**Comment by ZenRay** [comment]
@wszhan 位置不正确，请在确认一下位置

![image](https://user-images.githubusercontent.com/24636410/43847187-99233d96-9b62-11e8-8d56-0741d678019a.png)

**Comment by wszhan** [comment]
@ZenRay 不好意思，错误实在“查看答案”视频中，位置为34s处。

**Comment by sylviasun916** [comment]
英文字幕已修改！感谢反馈！ （需要一点时间部署显示在教室中）
