### ISSUE TITLE
数据分析进阶 > 课程3：探索单一变量 > 27. 练习：箱线图、四分位数和友谊 [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#351]
## 课程导航+地址
数据分析进阶 > 课程3：探索单一变量 > [27. 练习：箱线图、四分位数和友谊](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986500923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43703020-212e8b36-998e-11e8-9aed-af7c47211497.png)

## 具体描述
视频29s处，应为“I'll need to tell **qplot** that..."，此处中英文都要修改。

**Comment by ZenRay** [comment]
@wszhan 位置不正确，需要再次确认一下
![image](https://user-images.githubusercontent.com/24636410/43847401-1be247ae-9b63-11e8-87b0-3b41608b31f4.png)

**Comment by Kyliewang** [comment]
@sylviasun916 英文字幕错误，错误出现在练习题后“查看答案”的视频中。

**Comment by sylviasun916** [comment]
中英文字幕已修改！感谢反馈！ （需要一点时间部署显示在教室中）
