### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > 探索两个变量 > 10. 练习：将摘要与原始数据叠加

### ISSUE THREAD

**Issue by xfzhu2003** [udacity/DAND-CN-feedback#353]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 > 探索两个变量 > [10. 练习：将摘要与原始数据叠加](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687450923)

## 截图
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1688209/43703869-ad053c52-9990-11e8-8f57-5d679fc41c2d.png">

## 具体描述
视频2min17s处字幕  0.9更改为0.1，需改为  0.1更改为0.9

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （需要一点时间部署显示在教室中哦）
