### ISSUE TITLE
下载内容与题目描述不符合

### ISSUE THREAD

**Issue by Daisywlt** [udacity/DAND-CN-feedback#354]
## 教室链接
https://classroom.udacity.com/nanodegrees/nd100-cn/parts/b616c043-17c2-4eeb-9a84-29a56304d9e3/modules/0a58860c-f30b-4453-ac42-6c06217e36f3/lessons/f5dc6321-2a54-446b-9a25-9f9226d57138/concepts/7db72e32-a65c-4c12-bb1f-9797e511cd9f

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/38558427/43706385-c3caa858-9997-11e8-9349-a518c72e06aa.png)

## 具体描述
这一道题的内容说明似乎应该更新了。下载的数据中，goals比分就是正常比分；而且也无需重新格式化数据，直接用 tableau 绘图即可。

**Comment by ZenRay** [comment]
数据分析课程这块的数据没有出现该问题 @Kyliewang

**Comment by ZenRay** [comment]
课程安排不一致？ @Daisywlt
