### ISSUE TITLE
数据分析（进阶 ）>探索性数据分析> 课程3：探索单一变量 >4练习用户生日直方图>错别字

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#355]
## 课程导航+地址
例子：数据分析（进阶 ）>探索性数据分析> 课程3：探索单一变量 >4练习用户生日直方图>错别字

## 截图
![image](https://user-images.githubusercontent.com/41669267/43711886-ce5652e0-99a6-11e8-87f4-56f93efb78d0.png)

<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频8s处字幕‘可视化得图形程序包’，需改为‘可视化的图形程序包’

**Comment by sylviasun916** [comment]
错别字已修改！感谢反馈！ （需要一点时间部署显示在教室中）
