### ISSUE TITLE
数据分析（进阶） >探索性数据分析 > 课程3探索单一变量 > 14练习：调整组宽>facet_grid() 公式中代码有误

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#356]
## 课程导航+地址
例子：数据分析（进阶） >探索性数据分析 > 课程3探索单一变量 > 14练习：调整组宽>facet_grid() 公式中代码有误

## 截图
![image](https://user-images.githubusercontent.com/41669267/43713807-79a1defc-99ad-11e8-8f36-cb93180f5574.png)

视频截图：
![image](https://user-images.githubusercontent.com/41669267/43714009-21916c18-99ae-11e8-9f47-c18f29c1aff6.png)

## 具体描述
facet_grid(gender ~ .) ，这个代码是否等同于 facet_wrap(~gender)，因为在习题讲解视频中以及下方的等效的 ggplot 语法中均使用的facet_wrap(~gender)，并没有提及到facet_grid这个用法。

**Comment by ZenRay** [comment]
![image](https://user-images.githubusercontent.com/24636410/43988130-7458df60-9d61-11e8-9205-99b5c703c5e2.png)
