### ISSUE TITLE
数据分析（进阶 ）> 探索性分析 > 课程3：探索单一变量 >15.忽略 NA 观测值>错别字“自己”改为”子集”

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#357]
## 课程导航+地址
例子：数据分析（进阶 ）> 探索性分析 > 课程3：探索单一变量 >15.忽略 NA 观测值>错别字

## 截图
![image](https://user-images.githubusercontent.com/41669267/43714315-24b9d1ea-99af-11e8-93fa-31a8f83ee47c.png)

## 具体描述
视频30s处字幕“对数据划分自己”，需改为“对数据划分子集”

**Comment by sylviasun916** [comment]
错别字已修改，感谢反馈！ 可能需要一点时间才部署显示在教室里。
