### ISSUE TITLE
課程2:數據類型和運算符 17. 練表和成員運算符 表達不清楚

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#36]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/15635d7c-ee7f-43c7-a91c-b35ad8066a6c

## 截图
<img width="1212" alt="demo" src="图片地址"
![wechat _20180318231718](https://user-images.githubusercontent.com/27717979/37567478-92228fae-2b02-11e8-8bce-3ccbb5749fc0.png)

## 具体描述

表達得不是很清楚，因為就算len(list_of_random_things)等於3，也不能這樣用，所以IndexError: list index out of range是碰巧的錯誤，會讓學習者誤解

**Comment by Kyliewang** [comment]
课程里面的内容没有问题。
list_of_random_things[3]可以返回预期的值：
![screen shot 2018-03-21 at 7 22 20 pm](https://user-images.githubusercontent.com/35555101/37707226-5e76a5d6-2d3d-11e8-888f-a13bebdd3f64.png)
list_of_random_things的长度为4，len(list_of_random_things)=4，index为0-3，如果使用4作为index自然会返回IndexError: list index out of range。并非碰巧的错误。
