### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 评估数据 > 14. 编程评估

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#360]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/1165caef-24c9-4a2f-8030-4d6420c0c30a/lessons/243eeaed-5cd8-4e3c-91fa-9131d430138e/concepts/4d4ea0f8-db06-4f6e-9873-3391fb4a0dc4

## 截图
![udacity_8](https://user-images.githubusercontent.com/85287/43717816-443f6b68-99bb-11e8-9113-a8fa21c141b0.png)

## 具体描述
红色高亮出的链接是无效的： https://chrisalbon.com/python/pandas_indexing_selecting.html  （404错误）

**Comment by ZenRay** [comment]
链接可用，是原博客的内容丢失了 @Kyliewang

**Comment by Kyliewang** [comment]
已经替换链接
