### ISSUE TITLE
数据分析进阶 > 数据清洗 > 清理数据 > 9.练习:数据缺失

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#362]
## 课程导航+地址
数据分析进阶 > 数据清洗 > 清理数据 > 9.练习:数据缺失 https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/8e29807e-5f88-40b4-8ca9-496e3cb6e11b/lessons/ad8aad65-177d-4e20-a282-fbfd76493e40/concepts/50e02e83-f2da-429c-b055-25b38f30d709

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/37874304/43752728-ef9ad884-9a34-11e8-8052-e30319be371e.png)

![image](https://user-images.githubusercontent.com/37874304/43752734-f9a1b7ee-9a34-11e8-9384-75fce6eacba7.png)

![image](https://user-images.githubusercontent.com/37874304/43752745-0084c38a-9a35-11e8-959d-e876cbcc41a9.png)

![image](https://user-images.githubusercontent.com/37874304/43752753-06cbb938-9a35-11e8-974d-ecd7e19eca86.png)

![image](https://user-images.githubusercontent.com/37874304/43752756-0cb37d90-9a35-11e8-9b1b-d46223a7a72a.png)

![image](https://user-images.githubusercontent.com/37874304/43752761-11e6cb46-9a35-11e8-9844-b32e8c3fc14c.png)

## 具体描述
练习平台中，提示需要观看的视频名称与实际课程的视频名称不相符。

**Comment by Kyliewang** [comment]
已经修改
