### ISSUE TITLE
入门课程 >统计学 > 课程12：假设检验 > 23. 其他要考虑的事情：如果我们样本很大怎么办？

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#363]
## 课程导航+地址
入门课程 >统计学 > 课程12：假设检验 > [23. 其他要考虑的事情：如果我们样本很大怎么办？](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/ad8aca80-f444-4479-8848-5b07bafaf66c/concepts/9359bb35-975b-42b6-a8c0-de576c3267f3)

## 截图

![image](https://user-images.githubusercontent.com/24636410/43760117-c41bee36-9a53-11e8-8414-a26aa32937b1.png)

## 具体描述
这里建议翻译为“应答偏差”更好一些

**Comment by LeeSkyX** [comment]
已解决
