### ISSUE TITLE
 入门 > 数据分析入门 > 统计学 >置信区间> 4. Notebook + 练习：构建置信区间

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#367]
## 课程导航+地址
 入门 > 数据分析入门 > 统计学 >置信区间> [4. Notebook + 练习：构建置信区间](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/e1bdfed4-1d7f-4907-9bf1-76f1b196d660/concepts/eed9138e-b216-4dc7-b6ec-05e4e3f4331e)

## 截图
![image](https://user-images.githubusercontent.com/24636410/43786003-311c7352-9a9a-11e8-8d75-4f0b1dc86059.png)

## 具体描述
建议保留原英文名称 `bootstrap`

**Comment by LeeSkyX** [comment]
已解决
