### ISSUE TITLE
入门 > 数据分析入门 > 统计学 >置信区间 > 8.视频：统计意义与现实意义

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#368]
## 课程导航+地址
入门 > 数据分析入门 > 统计学 >置信区间 > [8.视频：统计意义与现实意义](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/e1bdfed4-1d7f-4907-9bf1-76f1b196d660/concepts/80fa9d16-8d86-4725-901a-5bbf3f8f9556)

## 截图
![image](https://user-images.githubusercontent.com/24636410/43788972-5c6debce-9aa1-11e8-881a-db1b58ea81b2.png)

![image](https://user-images.githubusercontent.com/24636410/43789165-e8230a82-9aa1-11e8-96e3-6659c0b67fcc.png)

## 具体描述
应该采用之前版本的翻译：实际显著性——`Practical significance`；统计显著性——`statistical significance`。另外 **标题和字幕** 翻译也需要调整一下。 @Kyliewang

**Comment by ZenRay** [comment]
第九课也是存在该问题
![image](https://user-images.githubusercontent.com/24636410/43789722-3ddfdce2-9aa3-11e8-882b-4503ac3faa51.png)

**Comment by LeeSkyX** [comment]
@Kyliewang  文本、标题已修改，字幕翻译添加的备注。

**Comment by sylviasun916** [comment]
@Kyliewang @LeeSkyX  字幕翻译已修改 感谢反馈！ （跑脚本可能需要一点时间才会显示在教室里。）
