### ISSUE TITLE
数据分析（进阶） >课程5：探索两个变量 > 3练习：散点图 >“散点图的等效 ggplot 语法”部分重复了两次

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#369]
## 课程导航+地址
例子：数据分析（进阶） >课程5：探索两个变量 > 3练习：散点图 >“散点图的等效 ggplot 语法”部分重复了两次
## 截图
![image](https://user-images.githubusercontent.com/41669267/43826236-6e6da3c2-9b29-11e8-9397-5dd1931519fb.png)

<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频下方文字部分，“散点图的等效 ggplot 语法”部分重复了两次，建议删除下面那个。

**Comment by Kyliewang** [comment]
Done
