### ISSUE TITLE
課程2:數據類型和運算符 22.練習:元組  元組不是有順序的嗎?

### ISSUE THREAD

**Issue by YuXiuChen** [udacity/DAND-CN-feedback#37]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/7e05f190-288e-476d-b114-5dab6eeabca0

## 截图
![wechat _20180318231906](https://user-images.githubusercontent.com/27717979/37567491-d0a062f6-2b02-11e8-914c-235c2a86b2bb.png)
![wechat _20180318231911](https://user-images.githubusercontent.com/27717979/37567493-d2b07fb8-2b02-11e8-81bc-6ba1aeae692d.png)

## 具体描述

元組不是有順序的嗎? 答案是否有誤

**Comment by Kyliewang** [comment]
已经修改。元组和列表都是有顺序的，感谢反馈！
