### ISSUE TITLE
数据分析（进阶） > 课程5：探索两个变量 > 13练习：平均价格 - 净度 > 文字部分“”dplyr包“突然出现有点不太理解，前后文不太通顺”

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#372]
## 课程导航+地址
例子：数据分析（进阶） > 课程6习题集：探索两个变量 > 13练习：平均价格 - 净度 > 文字部分“”dplyr包“突然出现有点不太理解，前后文不太通顺”

## 截图
![image](https://user-images.githubusercontent.com/41669267/43897417-7a4975aa-9c0e-11e8-9c92-9a14e0559468.png)

## 具体描述
文字部分，上面讲的卸载 plyr 包，突然出现了”dplyr包“有点不太理解，是不是多余了？

**Comment by ZenRay** [comment]
这里应该是翻译没有完全。
![image](https://user-images.githubusercontent.com/24636410/43988518-12926f86-9d6a-11e8-9493-3a3005621964.png)
另外根据 @wendypsy  的建议，可以考虑空行来处理，或者放到 `note` 最后部分。

另外还有建议这里修改为解绑定而非卸载

![image](https://user-images.githubusercontent.com/24636410/43988533-558ba546-9d6a-11e8-8fe0-7c361e39ad35.png)

**Comment by sylviasun916** [comment]
fixed and thanks
