### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > R基础 > 10. 获得帮助 翻译建议

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#373]
数据分析（进阶） > 探索性数据分析 > R基础 > 10. [获得帮助](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293170923)
## 截图
![002](https://user-images.githubusercontent.com/37401131/43903241-915eac28-9c1e-11e8-9246-55df94967a86.JPG)

## 具体描述   翻译【词义褒贬误导】

此处英文expecting没有贬义，希望，期盼之意，
但是中文翻译 “我们不指望你了解一切”，指望一词含有贬义，建议改为
“我们不期望你了解一切”

**Comment by sylviasun916** [comment]
已修改！感谢反馈！ （脚本需要一点时间部署显示在教室中）
