### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 > R基础 > 11.阅读并将数据集子集化 翻译建议 译文不通顺

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#375]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 > R基础 > 11.阅读并将数据集子集化 [](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293180923)

## 截图
![003](https://user-images.githubusercontent.com/37401131/43903620-70b470a6-9c1f-11e8-8da0-35c7ccbfad11.JPG)
![004](https://user-images.githubusercontent.com/37401131/43903622-71a9254c-9c1f-11e8-8cf9-ee6cec6426e0.JPG)

## 具体描述 【译文不通顺，无意义重复，不符合中文表达习惯】

此处，前后文不通顺， 
“美国50个州的数据 大多数数据来自于 
“大约1970年 在我们读取该数据前”

译文不符合中文表达习惯，无意义重复，建议修改为

”美国50个州的数据 大多数来自 “
”1970年前后 在我们读取数据前 “

**Comment by sylviasun916** [comment]
感谢反馈！有做一些优化 （脚本需要一点时间部署显示在教室中）
