### ISSUE TITLE
数据分析进阶 > 课程4：探索两个变量 > 6. 练习：coord_trans() [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#376]
## 课程导航+地址
数据分析进阶 > 课程4：探索两个变量 > [6. 练习：coord_trans()](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687350923)

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/19308564/43904505-6122f26e-9c21-11e8-90c4-3479cef844bd.png)

## 具体描述
视频13s处，英文原文字幕“core trans”应为“coord_trans"。

**Comment by sylviasun916** [comment]
中英文字幕错别字已修改！感谢反馈！ （需要一点时间部署显示在教室中）
