### ISSUE TITLE
入门>项目准备：SQL 和移动平均值>29 第一个练习提示会有除以零，但是实际练习2出现除以零

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#377]
## 课程导航+地址
入门>项目准备：SQL 和移动平均值>[29](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/07dc6709-953d-41c2-98d2-f630044c0767)

## 截图

![6](https://user-images.githubusercontent.com/7417557/43905869-8b6a96d2-9c24-11e8-8fc4-9935a2635b1e.png)

##具体描述
 第一个练习提示会有除以零，但是实际练习2出现除以零

**Comment by ZenRay** [comment]
需要调整位置，另外建议重新调整一下这个翻译 
![image](https://user-images.githubusercontent.com/24636410/43988745-843b23c2-9d6e-11e8-9c4c-d300a1e08bd5.png)

**Comment by sylviasun916** [comment]
@Kyliewang  麻烦 Kylie 看一下这道题翻译上有无问题哦？ 感谢！ （后半句我已修改过啦。 只是前面不太理解除以零是怎么回事。）

**Comment by Kyliewang** [comment]
已经修改
