### ISSUE TITLE
数据分析（进阶）> 数据清洗 > 清理数据 > 课程 4: 清理数据 > 解决方案: 质量

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#378]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/b88e1e04-44df-4c44-a436-f10a42f39309/modules/8e29807e-5f88-40b4-8ca9-496e3cb6e11b/lessons/ad8aad65-177d-4e20-a282-fbfd76493e40/concepts/9d3c80f7-3b67-42bc-8513-7fe0c71ef83e#

## 截图

<img width="753" alt="udacity_1" src="https://user-images.githubusercontent.com/85287/43935800-3162e270-9c88-11e8-9079-ed6b42ef625a.png">

## 具体描述
翻译不当

红框处原文为：
*Import the cut treatments into a DataFrame and concatenate it with the original treatments DataFrame.*

建议译文中的treatments保持英文不要翻。建议译文：  

**把切割过的treatments数据导入到DataFrame中，并将它和原始的treatments DataFrame拼接到一起。**

**Comment by ZenRay** [comment]
建议直接用 “treatment_cut 数据集”，因为这个 “cut” 可能具有实际的试验意义，不应该直接翻译为切割。或者考虑确认该处理的具体方式 @Kyliewang

**Comment by sylviasun916** [comment]
@Kyliewang  需要 Kylie 的学科专业看一下这里应该怎么修改比较好？ 谢谢！
