### ISSUE TITLE
数据分析入门> 3.数据分析入门 >  课程 5 基本SQL > 4.练习：ERD 基础知识

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#379]
## 课程导航+地址
入门 > 3.数据分析入门  >课程 5 基本SQL > [ 4.练习：ERD 基础知识](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/614cf95a-13bf-406c-b092-e757178e633b/concepts/f0bda721-9e47-4d8a-a795-53cb24890b83)

## 截图
![101](https://user-images.githubusercontent.com/31531236/43950976-77c51350-9cc4-11e8-8607-ed1a6b11a955.png)

## 具体描述
1.  “使用上图和你对 ERD 的新知识”，语句不通顺的，可以改为：使用上图和你对 ERD 新知识的掌握

**Comment by ZenRay** [comment]
可以优化一下 “你的 ERD新知识”，

**Comment by sylviasun916** [comment]
fixed and thanks!
