### ISSUE TITLE
入门>课程1为何要学习python编程>1 维基链接需要翻墙，建议使用国内资源

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#380]
## 课程导航+地址
入门>课程1为何要学习python编程> [1](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/410ddff6-0f40-4d69-a63d-22094c21350a/concepts/285fb88b-39c5-4c6b-8b43-0081e83ef1e3)

## 截图
![7](https://user-images.githubusercontent.com/7417557/43957870-fb3fcfec-9cdb-11e8-89ee-6e1f8a4efaa0.png)

## 具体描述
维基链接需要翻墙，建议使用国内资源

**Comment by Kyliewang** [comment]
英文维基百科链接无需翻墙~
