### ISSUE TITLE
数据分析进阶 > 探索单一变量 > 3 - 伪 Facebook 用户数据  > 翻译建议

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#381]
## 课程导航+地址
数据分析进阶 > 探索单一变量 >3 - 伪 Facebook 用户数据  > 

## 截图
![default](https://user-images.githubusercontent.com/37401131/43965404-b23149f0-9cf1-11e8-82d3-35627ec0a95d.JPG)

## 具体描述
此处 
“ 我们将人们指向最近几周发出的一个帖子 ” 
“ 问他们认为多少人看到这个贴子 ”

point to 翻译为指向 语义不通，此处建议修改为

“我们让人们看最近几周发过的一个帖子”
“问他们觉得有多少人会看 ”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
