### ISSUE TITLE
数据分析进阶 > 探索单一变量 > 9 分面 翻译建议

### ISSUE THREAD

**Issue by agnesyan** [udacity/DAND-CN-feedback#382]
## 课程导航+地址
数据分析进阶 > 探索单一变量 > 9 分面

## 截图

![facet](https://user-images.githubusercontent.com/37401131/43967115-42e935bc-9cf6-11e8-97fa-0ab35c7f6133.JPG)

## 具体描述
这一节的facet wrap 翻译成琢面包裹实在不好理解，也无法反应出原文的词义，而且后面也多次用到此词
建议修改为， 缠绕分面 

为了对应此处 后面的facet grid 可翻译成 网格分面

**Comment by ZenRay** [comment]
前面已提交过了。另外这里翻译不能直接看这字幕文档来翻译，这里是针对具体的方法的
