### ISSUE TITLE
数据分析进阶 > 课程5：探索两个变量 > 6. coord_trans()

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#383]
## 课程导航+地址
数据分析进阶 > 课程5：探索两个变量 > [6. coord_trans()](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687350923)

## 截图

![image](https://user-images.githubusercontent.com/19308564/43987204-db7ad066-9d4f-11e8-9aae-6fab921476a8.png)

## 具体描述
在“查看答案“视频5s处，字幕"the cord translayer"应为"the coord_trans() layer"。

**Comment by ZenRay** [comment]
这里指的是坐标轴转换了，但是翻译还是需要另外方式， @Kyliewang

**Comment by wszhan** [comment]
若是用更加直白的方式，或者可以说“添加一个**转换坐标轴的新层**”。 @ZenRay
