### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 5 基本SQL > 20.解决方案：解决方案：ORDER BY

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#385]
## 课程导航+地址
入门 > 3.数据分析入门  > 课程 5 基本SQL> [ 20.解决方案：解决方案：ORDER BY](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/614cf95a-13bf-406c-b092-e757178e633b/concepts/e3fb05c3-e396-4905-b863-4aabee62b933)

## 截图
![102](https://user-images.githubusercontent.com/31531236/43987640-4d4dd5f2-9d56-11e8-9893-8a8941ec279f.png)

## 具体描述
1.  “以前” ，翻译不准确，我看后面的翻译为：此前。再后面的有的直接去掉这个”此前“或者”以前“。直接去掉，没翻译，也是可以的。要不都统一去掉算了。

**Comment by sylviasun916** [comment]
fixed and thanks!
