### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 5 基本SQL > 21.视频：ORDER BY（第二部分）

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#386]
## 课程导航+地址
入门 > 3.数据分析入门 > 课程 5 基本SQL > [21.视频：ORDER BY（第二部分）](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/614cf95a-13bf-406c-b092-e757178e633b/concepts/6e9b4fc1-8c5b-40e5-936d-8428a1c516d9)

## 截图
![103](https://user-images.githubusercontent.com/31531236/43987691-7e1c09f0-9d57-11e8-867f-b7346fbfe7b8.png)

## 具体描述
1. 翻译不是很明确

**Comment by ZenRay** [comment]
可以考虑使用 “也可以使用 DESC 来翻转顺序”

**Comment by Kyliewang** [comment]
已经修改，谢谢反馈！
