### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 5 基本SQL > 43.视频: AND 和 BETWEEN

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#387]
## 课程导航+地址
入门 > 3.数据分析入门 > 课程 5 基本SQL > [43.视频: AND 和 BETWEEN](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/614cf95a-13bf-406c-b092-e757178e633b/concepts/32dabf6d-7b56-4f7a-bb7e-9572aec9d45b)

## 截图
![104](https://user-images.githubusercontent.com/31531236/43987911-df42bd1a-9d5b-11e8-8178-5a89bdcbae61.png)
![105](https://user-images.githubusercontent.com/31531236/43987912-f36f1ebe-9d5b-11e8-918e-ca624792e6c5.png)
![106](https://user-images.githubusercontent.com/31531236/43987915-faf09834-9d5b-11e8-8a81-9e36db1a6b06.png)

## 具体描述
1. 01：23，01：25，01：28，共 3处没有中文翻译，第一处可能因为技术原因，但是后面2处却也没有中文翻译了

**Comment by ZenRay** [comment]
应该调整一下时间格式，秒数太详细来不方便看。需要直接用课程页面的显示时间。

注释是就是说明了这两处位置的内容 @shuiyuejihua

**Comment by Kyliewang** [comment]
@sylviasun916 麻烦圆圆看下这里是什么原因哦~

**Comment by sylviasun916** [comment]
已修改 是时间轴有细微差异 已部署修改 感谢反馈！
