### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 9. 视频：模型诊断+性能指标【字幕翻译错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#388]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43988897-d6b4b6c4-9d71-11e8-8821-cc02f1a184c0.png)

## 具体描述
“充分自由机器学习”应译为“免费的机器学习课程”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
