### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 17. 练习：有多少Schroeder预测值 【英文字幕错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#389]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43988990-534b9f98-9d74-11e8-99f2-7332f98e3bd6.png)

## 具体描述

此处英文字幕存在错误，语音中的内容应该是“correspond to misclassification”。并且对照视频内容，矩阵中的非对角线是被错误分类的情况。

**Comment by ZenRay** [comment]
确实是语音和字幕内容不匹配 @Kyliewang

**Comment by sylviasun916** [comment]
已修改 感谢反馈
