### ISSUE TITLE
数据分析进阶 > 课程5：探索两个变量 > 14. 相关分析法 [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#390]
## 课程导航+地址
数据分析进阶 > 课程5：探索两个变量 > [14. 相关分析法](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687550923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43989194-a6d9b61a-9d77-11e8-8229-54cb37f70aa5.png)

## 具体描述
视频24s处，这里发音为“row”的应该是希腊字母`ρ`，如同instructor notes里所示。英文标注一般为`Rho`而非`row`。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
