### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 29. 录屏视频：在Python里进行模型诊断——第一部分 【翻译不够准确】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#391]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43989229-63ec811a-9d78-11e8-9c11-1134e0083887.png)

## 具体描述
这里的“更好地预测反应”应该修改为“更好地预测反应变量”

**Comment by ZenRay** [comment]
更好的方式来说可以考虑翻译为“更好地预测反应变量”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
