### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 29. 录屏视频：在Python里进行模型诊断——第一部分 【翻译不够准确】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#392]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43989247-d0a8822c-9d78-11e8-8cf0-28098de10fde.png)

## 具体描述

此处字幕应该翻译为“所以先填入训练集的X，在填入训练集的Y”，或者也可以直接用变量名代替，修改为“所以先填入X_train，然后填入y”

**Comment by ZenRay** [comment]
建议不修改

**Comment by sylviasun916** [comment]
暂时不修改 感谢反馈
