### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 30. Notebook+练习：模型诊断 【翻译错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#394]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43989326-501cda3e-9d7a-11e8-98c2-bc90e1580a8a.png)

## 具体描述
此处的“回应”英文应该是response，所以应该译为“反应变量”

**Comment by Kyliewang** [comment]
已经修改。
