### ISSUE TITLE
入门 > 统计学 > 逻辑回归 > 32. 文本：复习 【翻译错误】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#395]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43989362-1ca89bba-9d7b-11e8-952e-d0ffef9e219c.png)

## 具体描述

此处的“二进制”原文应该是binary，但是此处的意思应该是“二元分类”

**Comment by ZenRay** [comment]
这里虽然是 “binary”，建议还是考虑翻译为“二元分类” @Kyliewang

**Comment by sylviasun916** [comment]
fixed and thanks!
