### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 >课程7：探索多个变量 >10练习：切割一个变量>“加入年料斗”翻译不太好理解

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#397]
## 课程导航+地址
例子：数据分析（进阶） > 探索性数据分析 >课程7：探索多个变量 >10练习：切割一个变量>“加入年料斗”翻译不太好理解

## 截图
![1](https://user-images.githubusercontent.com/41669267/43990543-1a721006-9d8f-11e8-9c06-a9e6edb4c1bf.jpg)

## 具体描述
视频6s处year_joined.bucket字幕“加入年料斗”，需改为“加入**年份**斗”

**Comment by ZenRay** [comment]
建议不翻译

**Comment by sylviasun916** [comment]
已修改 感谢反馈
