### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 >课程7：探索多个变量 >28练习：分析三个或更多变量>字幕” 结束了第5课的学习“有误，应为第7课

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#399]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 >课程7：探索多个变量 >28练习：分析三个或更多变量>字幕” 结束了第5课的学习“有误，应为第7课

## 截图
![2](https://user-images.githubusercontent.com/41669267/43991121-671e4e20-9d98-11e8-9eb1-174bf4eda670.jpg)

## 具体描述
视频4s处字幕” 结束了第5课的学习“有误，需改为“第7课 ”
后面的总结视频第3s处也是该问题。

**Comment by ZenRay** [comment]
根据导师发音是没有错误的，可以考虑添加注释 @Kyliewang

**Comment by Kyliewang** [comment]
与美国课程顺序调整有关。done
