### ISSUE TITLE
数据分析进阶 > 课程5：探索两个变量 > 18. 练习：相关系数的更多注意事项 [中英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#400]
## 课程导航+地址
数据分析进阶 > 课程5：探索两个变量 > [18. 练习：相关系数的更多注意事项](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687630923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43991119-602ae538-9d98-11e8-8651-357b3fc2df59.png)

## 具体描述
在**答案视频**的14s处，字幕的“GM point”应为方程**geom_point**。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
