### ISSUE TITLE
数据分析（进阶） > 探索性数据分析 >课程8习题集：探索多个变量 >3练习：典型表值>“至”有点多余建议删除

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#401]
## 课程导航+地址
数据分析（进阶） > 探索性数据分析 >课程8习题集：探索多个变量  >3练习：典型表值>“至”有点多余建议删除

## 截图
![3](https://user-images.githubusercontent.com/41669267/43991183-efd43b0c-9d99-11e8-988b-7060bc2d1a09.jpg)

## 具体描述
文字部分“至”有点多余建议删除

**Comment by Kyliewang** [comment]
已修改~
