### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 6 SQL JOIN > 20. 解决方案：最后的检测

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#403]
## 课程导航+地址
入门 > 3.数据分析入门 >课程 6 SQL JOIN  > [ 20. 解决方案：最后的检测](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/e12ccca0-1634-44a4-b34a-0344c07f3652)

## 截图
![201](https://user-images.githubusercontent.com/31531236/43991501-a79de426-9da0-11e8-865f-407afb0e0279.png)
![202](https://user-images.githubusercontent.com/31531236/43991503-b85b8c0a-9da0-11e8-8c3a-8abab6646548.png)

## 具体描述
1. 同一个页面，一共有3处，【分子】改为【分母】，最右边【少了个右括号】：  
>可以在分子上加上 0.01(total_amt_usd/(total+0.01)。    

改为：    

>可以在分母上加上 0.01，即：(total_amt_usd/(total+0.01))。

**Comment by sylviasun916** [comment]
fixed and thanks!
