### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 6 SQL JOIN > 19. 练习：最后的检测

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#404]
## 课程导航+地址
入门 > 3.数据分析入门 > 课程 6 SQL JOIN > [19. 练习：最后的检测](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/2a249dad-12c9-45ea-87c2-70a7dd4a35b1)

## 截图
![203](https://user-images.githubusercontent.com/31531236/43991544-bf4f4c94-9da1-11e8-9abd-ab88b8623657.png)

## 具体描述
1.  描述错误，"分子" 改为 "分母"，公式少个右括号。
>可以在分子上加上 0.01(total_amt_usd/(total+0.01)。

改为：
>可以在分母上加上 0.01，即：(total_amt_usd/(total+0.01))。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
