### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 6 SQL JOIN > 21.文本：总结和后续内容

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#405]
## 课程导航+地址
入门 > 3.数据分析入门> 课程 6 SQL JOIN > [21.文本：总结和后续内容](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/8f23fc69-7c88-4a94-97a4-d5f6ef51cf7b/concepts/f0e65adc-db97-4a50-937d-0d393828f2c8)

## 截图
![o62 kk 9w a ul 4hqjpn](https://user-images.githubusercontent.com/31531236/43991750-01f326b6-9da6-11e8-9b14-b64d44df0ae3.png)

## 具体描述
1. UNION 和 UNION ALL、 SELF JOIN链接打不开

**Comment by Kyliewang** [comment]
已经替换墙内链接，感谢反馈！
