### ISSUE TITLE
数据分析进阶 > 课程4：探索两个变量 > 22. 练习：了解噪声：年龄到月龄 [练习直接给出答案]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#406]
## 课程导航+地址
数据分析进阶 > 课程4：探索两个变量 > [22. 练习：了解噪声：年龄到月龄](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687710923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43992853-5e25c8ec-9db7-11e8-8c71-2faf355cb9d8.png)

## 具体描述
练习页面在还未提交的时候，能直接看到答案。最好能够改为提交并答案正确之后，才能看到。

**Comment by Kyliewang** [comment]
感谢~
