### ISSUE TITLE
数据分析进阶 > 课程4：探索两个变量 > 22. 练习：了解噪声：年龄到月龄 [中文字幕]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#407]
## 课程导航+地址
数据分析进阶 > 课程4：探索两个变量 > [22. 练习：了解噪声：年龄到月龄](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687710923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43992884-bbc5724a-9db7-11e8-856d-0159cfa97ec3.png)

## 具体描述
视频48s处字幕如图所示，但讲师意思应该是在公式`(12 - dob_month)`处，没有明确DataFrame名，所以此处需改为“**忘记在出生月份中注明（或包含）DataFrame名（此处为pf）**”。

**Comment by wszhan** [comment]
@ZenRay 对的，只是中文字幕部分需要调整

**Comment by sylviasun916** [comment]
已修改 感谢反馈
