### ISSUE TITLE
数据分析进阶 > 课程4：探索两个变量 > 23. 练习：带有月均值的年龄[中英文字幕]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#408]
## 课程导航+地址
数据分析进阶 > 课程4：探索两个变量 > [23. 练习：带有月均值的年龄](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687740923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/43992933-85a7093e-9db8-11e8-90de-a7fbccffef24.png)

## 具体描述
视频18s处，"d apply r"应为“**dplyr()**".

**Comment by ZenRay** [comment]
这里是使用的包为 `dplyr`，使用了其中的函数。建议翻译为 “dpylr 函数” @Kyliewang

**Comment by sylviasun916** [comment]
已修改 感谢反馈
