### ISSUE TITLE
入门 > （可选）Anaconda和Jupyter Notebook > 配置Anaconda > 2. Anaconda是什么？【翻译不通顺】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#409]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43993120-67ac2e52-9dbb-11e8-9e8a-d7cc521609ab.png)

## 具体描述

此处的翻译不通顺，应该译为“然后在项目对应的环境中工作”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
