### ISSUE TITLE
入门 > 数据分析入门 > 欢迎加入数据分析 > 欢迎来到纳米学位 > 5.诚信和决心 > 翻译建议

### ISSUE THREAD

**Issue by sweetorange123** [udacity/DAND-CN-feedback#411]
## 入门 > 数据分析入门 > 欢迎加入数据分析 > 欢迎来到纳米学位 > [5.诚信和决心] > 翻译建议
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/4c399c8e-6d19-48c1-88c8-af3ee3f6d541/lessons/0e3408d5-b6dc-466e-af1f-c4349935d1cb/concepts/592f478e-11db-41e9-9925-e68edfd270b6

## 截图
图1<img width="1212" alt="demo" src="图片地址">
![default](https://user-images.githubusercontent.com/28428954/43995630-11486ba6-9de4-11e8-8818-b4733f99073a.png)
图2
![default](https://user-images.githubusercontent.com/28428954/43995683-410203e2-9de5-11e8-9733-303cd4c4d165.png)

## 具体描述
这一课的视屏讲解中：
图1位置  00:07  处，建议翻译为：“你在这里解决困难的问题过程中”
图2位置  00:08  处，建议翻译为：‘’你的脑力极限将得到挑战‘’

**Comment by sylviasun916** [comment]
已修改 感谢反馈
