### ISSUE TITLE
入门 > 脚本编写 > 在脚本中接受原始输入 字幕错误

### ISSUE THREAD

**Issue by dedlous** [udacity/DAND-CN-feedback#414]
## 课程导航+地址
入门 > 脚本编写 > 在脚本中接受原始输入 > https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/09be9405-95aa-4a89-b800-9b60ccde5476/concepts/622bcf85-e02b-4ed1-a6b1-bc6629c8fcf7

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/10630180/43997576-d6842202-9e11-11e8-87a8-4cfaf63d9015.png">

## 具体描述
视频01：43处字幕为there are also loads of other........应该是 there are also lots of other....

**Comment by ZenRay** [comment]
表达没有错误，可以使用
