### ISSUE TITLE
入门 > （可选）Anaconda和Jupyter Notebook > 配置Jupyter notebook > 10. 创建幻灯片 【翻译不通顺】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#416]
## 截图
![image](https://user-images.githubusercontent.com/7297350/43998767-152ba26e-9e30-11e8-8816-4ee64bd483bf.png)

## 具体描述

此处的翻译不太通顺，建议译为“选择Skip（忽略）会在幻灯片中忽略该单元格”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈
