### ISSUE TITLE
入门 > 4. 统计学 > 分析A/B测试结果 > 5. 测试4：概率 【翻译不通顺】

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/DAND-CN-feedback#417]
## 截图

![image](https://user-images.githubusercontent.com/7297350/43998888-485db160-9e33-11e8-9bd1-d2d95d044727.png)

## 具体描述

此处的两句话翻译不通顺，建议译为“某个人收到控件(control)页面后的转换概率”和“某个人收到处置(treatment)页面后的转换概率”

**Comment by ZenRay** [comment]
建议按照假设检验的原则进行合理调整翻译：

1. 假定收到 **控制组** 页面的个人的转化率
2.  假定收到 **试验组** 页面的个人的转化率

@Kyliewang

**Comment by sylviasun916** [comment]
fixed and thanks
