### ISSUE TITLE
数据分析（进阶）> 探索性数据分析 >  探索单一变量 > 25. 练习： 网页端上的“点赞”数

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#419]
## 课程地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755618712/concepts/8140986430923

## 截图
![udacity_2](https://user-images.githubusercontent.com/85287/44034158-044751ea-9f3f-11e8-893c-f66e9ae3d7c2.png)

## 具体描述
视频42s处字幕**different subgroups**，建议改为**不同的子分组**

**Comment by ZenRay** [comment]
可以考虑使用 “自分组”，它比较常用

**Comment by sylviasun916** [comment]
已修改 感谢反馈
