### ISSUE TITLE
数据分析（进阶） > 课程7 ：探索多个变量 > 9.练习： 第三个定量变量[英文字幕错误]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#420]
## 课程导航+地址
数据分析（进阶） >探索性数据分析> 课程7 ：探索多个变量 > [9.练习： 第三个定量变量](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/701610057/concepts/8737286370923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/44036363-2fec86ee-9f44-11e8-9611-600c0219209f.png)

## 具体描述
答案视频的39s处开始，英文字幕"we need to run group one more time..."，需改为"we need to **ungroup** one more time..."。同样的，中文字幕也要做相应修改，参考翻译为“我们要再取消一次分组”。

**Comment by ZenRay** [comment]
按照表达的意思上来看，确实是使用了 `ungroup`

**Comment by sylviasun916** [comment]
已修改 感谢反馈
