### ISSUE TITLE
入门>python入门>数据类型与运算符>课程4 字幕错误

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#422]
## 课程导航+地址
入门>python入门>数据类型与运算符>[课程4](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/c27e5e9b-c7e8-45fd-927b-46d8ae2d13ba/modules/0a9fc020-b2c4-40b0-baba-33d020878f16/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/cf20e9f1-9b19-4bea-b2e1-d5c591e20877)

## 截图
![8](https://user-images.githubusercontent.com/7417557/44094509-f5b43560-a008-11e8-9096-7f0a84ac594c.png)

## 具体描述
视频40s处英文字幕X,y,z需改为x,y,z

**Comment by sylviasun916** [comment]
已修改 感谢反馈
