### ISSUE TITLE
数据分析（进阶 ）> 探索性数据分析 > 项目 > 进阶项目2：研究和总结数据>文字不通顺

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#423]
## 课程导航+地址
例子：数据分析（进阶 ）> 探索性数据分析 > 项目 > 进阶项目2：研究和总结数据>文字不通顺

## 截图
![image](https://user-images.githubusercontent.com/41669267/44095302-0dafed92-a00b-11e8-983f-fd8b3044b11c.png)

## 具体描述
文字最后，“什么是为数据提供稀缺且附带额外价值的服务？”，不太通顺，应该是“什么**可以**为数据提供稀缺且附带额外价值的服务”

**Comment by ZenRay** [comment]
这里的内容存在中英文内容差异，是翻译问题还是故意这样调整，需要确认一下 @Kyliewang
