### ISSUE TITLE
数据分析进阶> 探索性数据分析 >R基础 >8.练习:RStudio布局-字幕错误

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#425]
## 课程导航+地址
数据分析进阶> 探索性数据分析 >R基础 >8.练习:RStudio布局-字幕错误https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8041293110923

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/37874304/44202678-3bbd9980-a17f-11e8-924d-2064ad537063.png)

## 具体描述
视频1s处字幕“它是一个ID”，需改为“它是一个IDE”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
