### ISSUE TITLE
数据分析（进阶） > 数据清洗 > 课程1：数据整理简介 > 3.定义和类比>不通顺，改成“整理的意思是”

### ISSUE THREAD

**Issue by wendypsy** [udacity/DAND-CN-feedback#426]
## 课程导航+地址
例子：数据分析（进阶） > 数据清洗 > 课程1：数据整理简介 > 3.定义和类比>不通顺，改成“整理的意思是”

## 截图
![image](https://user-images.githubusercontent.com/41669267/44251393-c0b1bd00-a22a-11e8-9b84-f16d52ea6585.png)

## 具体描述
图片下方字幕“”因此，整理**是**意思是*围拢、饲养“”，需改为“整理**的**意思是”

**Comment by Kyliewang** [comment]
已订正。谢谢~
