### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 7 SQL 聚合 > 23.练习：练习：HAVING

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#428]
## 课程导航+地址
入门 > 3.数据分析入门 >课程 7 SQL 聚合 > [23.练习：练习：HAVING](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/76a484da-1f2e-4886-ba2c-684bb30e267d/concepts/626dbb04-14f8-4215-ac69-81d323e4bf59)

## 截图
![201](https://user-images.githubusercontent.com/31531236/44270212-6257ff00-a269-11e8-8eb6-0b0c4eeace28.png)

## 具体描述
1. markdown语法错误：【**ORDERY BY】

**Comment by Kyliewang** [comment]
已解决。
