### ISSUE TITLE
数据分析进阶> 探索性数据分析> R基础 >5.在windows上安装Rstudio

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#429]
## 课程导航+地址
数据分析进阶> 探索性数据分析> R基础 >5.在windows上安装Rstudiohttps://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/729069797/concepts/8628710190923

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/37874304/44270740-f37ba580-a26a-11e8-8e9b-4081a557cf84.png)

## 具体描述
下方R的官网网址http://cran.rstudio.com无法打开，
实际可打开的官网网址为https://www.r-project.org/

**Comment by ZenRay** [comment]
链接是正确的，可以打开
