### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 9 SQL数据清理 > 3.练习：LEFT 与 RIGHT

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#430]
## 课程导航+地址
入门 > 3.数据分析入门 > 课程 9 SQL数据清理 > [3.练习：LEFT 与 RIGHT](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/03f64082-fa4d-4aff-80be-d48597867e07/concepts/1f7e117b-0bd8-4a98-a3fb-2449e0b77d90)

## 截图
![301](https://user-images.githubusercontent.com/31531236/44272126-8d911d00-a26e-11e8-9b2d-ef9f26c59bc9.png)

## 具体描述
1.  quora链接打不开，封禁了  
2.  链接格式有问题，将后面的【请从】也包含进去了

**Comment by ZenRay** [comment]
链接因为 markdown 语句村务而存在错误，需要修改。 @Kyliewang

**Comment by Kyliewang** [comment]
已经修正，感谢。
