### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 课程 9 SQL数据清理 > 14.视频: COALESCE

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#431]
## 课程导航+地址
入门 > 3.数据分析入门 >  课程 9 SQL数据清理> [14.视频: COALESCE](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/db87e1f5-5127-460b-b0bd-a7ef5d54adcf/modules/26c5f626-8b6a-4c62-884b-7b2d73cd0706/lessons/03f64082-fa4d-4aff-80be-d48597867e07/concepts/697bd996-0764-4e5f-9406-daefa67d266b)

## 截图
![401](https://user-images.githubusercontent.com/31531236/44272775-5885ca00-a270-11e8-9109-8677c6771a8d.png)

## 具体描述
1. 第一个【此处】，w3school，链接打不开

**Comment by Kyliewang** [comment]
已经更换替代链接。感谢~
