### ISSUE TITLE
入门>统计学>[选修]描述统计学-第一部分>19 英文维基链接需要翻墙

### ISSUE THREAD

**Issue by eruerua** [udacity/DAND-CN-feedback#432]
## 课程导航+地址
入门>统计学>[选修]描述统计学-第一部分> [19](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/2e4f9313-11d5-4ecd-9af7-b4b6680d075a/concepts/25b5e8b7-17f7-428e-a55b-a6a53fc11cf4)

## 截图
![1](https://user-images.githubusercontent.com/7417557/44309510-649d9300-a3fa-11e8-8e2c-6ae4fab5b41e.png)

## 具体描述
维基链接需要翻墙访问，最好使用替代资源

**Comment by Kyliewang** [comment]
英文维基链接确认过无需翻墙，所以并未修改~
