### ISSUE TITLE
数据分析入门> 3.数据分析入门 > 项目：探索数据集 > github里数据集打不开下载不了

### ISSUE THREAD

**Issue by shuiyuejihua** [udacity/DAND-CN-feedback#434]
## 课程导航+地址
入门 > 3.数据分析入门 > 项目：探索数据集 > [github项目数据下载不了](https://github.com/udacity/new-dand-basic-china/blob/master/%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%85%A5%E9%97%A8/%E9%A1%B9%E7%9B%AE-%E6%8E%A2%E7%B4%A2%E6%95%B0%E6%8D%AE%E9%9B%86/%E6%8E%A2%E7%B4%A2%E6%95%B0%E6%8D%AE%E9%9B%86%20-%20%E5%A4%87%E9%80%89%E6%95%B0%E6%8D%AE%E9%9B%86.md)

## 截图
![601](https://user-images.githubusercontent.com/31531236/44344593-ab0af480-a4c3-11e8-91a6-003cf291351d.png)

## 具体描述
1.  除了Gapminder World，可以打开看看，其它的数据集都打不开，可能防火墙吧GFW吧

**Comment by ZenRay** [comment]
这个需要进入文件里面，这个是没有问题的。只是 GitHub 偶尔不稳定
