### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 习题集：探索单一变量 > 1. 这节课有些不同

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#437]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569242/concepts/29086686120923

## 截图
<img width="856" alt="udacity1" src="https://user-images.githubusercontent.com/85287/44375555-e094f980-a526-11e8-9186-98cf611a98ef.png">

## 具体描述
红框处有**英文原文**和**中文译文**，建议去掉英文原文，因为译文清晰，没有放原文的必要。

**Comment by Kyliewang** [comment]
Done. Thanks!
