### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 习题集：探索单一变量 >  各项练习内的英文注释都没有翻译

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#438]
## 课程导航+地址
其中之一：
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/685569242/concepts/7468187210923
基本所有的练习内的英文注释都没有翻译

## 截图
例如：
<img width="717" alt="udacity2" src="https://user-images.githubusercontent.com/85287/44376175-d1fc1180-a529-11e8-9ad7-04669729ba21.png">

## 具体描述
练习中的英文注释是有意没有翻译吗？ 请核实！

**Comment by ZenRay** [comment]
这些都是类似注释的作用，一般情况下还是用英文好些。 可以请 @Kyliewang 确认一下

**Comment by Kyliewang** [comment]
赞同。
