### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索两个变量 > Alpha和Jitter

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#439]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687380923

## 截图
<img width="1032" alt="udacity3" src="https://user-images.githubusercontent.com/85287/44378464-0674cb00-a534-11e8-918c-d3519b098039.png">

## 具体描述
视频12s处字幕**put those in the aesthetic wrapper**的翻译很奇怪（**将其放入美学包裹内**），建议改成：**将其放入包装函数aes中** 更容易理解。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
