### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索两个变量 > Alpha和Jitter

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#440]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687380923

## 截图
<img width="1011" alt="udacity4" src="https://user-images.githubusercontent.com/85287/44378693-248efb00-a535-11e8-969e-560b7e6b5d4d.png">

## 具体描述
视频01:00s处字幕**use a cord transformation**应该是**use a coord transformation**，所以相应的防疫需改为**使用坐标转换**

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
