### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 8. 练习：对钻石的需求[英文字幕]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#441]
## 课程导航+地址
数据分析（进阶） > 课程9 ：钻石与价格预测 > [8. 练习：对钻石的需求](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8675788300923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/44396683-4194ef80-a570-11e8-9841-a6f71426615c.png)

## 具体描述
视频12s处字幕"diamond. Diamond..."，按讲师所述，应该是"diamonds, were (it) not for the social norm..."（it应该是因口语化而被省略），对应中文参考为“...，**若非因**求婚时要奉上礼物的社会惯例“。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
