### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 13. 练习：价格与克拉和净度[中文字幕]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#442]
## 课程导航+地址
数据分析（进阶） > 课程9 ：钻石与价格预测 > [13. 练习：价格与克拉和净度](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8624987450923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/44408000-04415980-a592-11e8-8130-1455cb3fcc0d.png)

## 具体描述
“查看答案”视频01-02s处中文字幕“美丽的wrapper”，对应英文为“aesthetic wrapper”，建议用英文原文，若一定要翻译，个人建议参考“图形属性”。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
