### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 20. 练习：构建线性模型[中文字幕]

### ISSUE THREAD

**Issue by wszhan** [udacity/DAND-CN-feedback#443]
## 课程导航+地址
数据分析（进阶） > 课程9 ：钻石与价格预测 > [20. 练习：构建线性模型](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8624987660923)

## 截图
![image](https://user-images.githubusercontent.com/19308564/44409766-9565ff80-a595-11e8-8f86-de6bdb84f9b5.png)

## 具体描述
视频13s处中文字幕“我就保持这样”对应英文字幕为“The *I* stands for *as is*”，此处应该是对R语言内`I` wrapper的解释，但中文字幕似乎将`I`翻译为了代词*I*，即”我“。中文可能要稍作修改。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
