### ISSUE TITLE
数据分析进阶 > 探索性数据分析>  探索两个变量>  6.练习

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#444]
## 课程导航+地址
数据分析进阶 > 探索性数据分析>  探索两个变量>  6.练习https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8651687350923

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/37874304/44441114-9468b880-a5fd-11e8-8b62-333f009f10cc.png)

## 具体描述
答案的视频的11秒处“平方很”，实际上应该是“平方根”

**Comment by sylviasun916** [comment]
fixed and thanks!
