### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索两个变量 > 17. Moira 对于相关的研究

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#449]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755298985/concepts/8644089260923

## 截图
<img width="1061" alt="udacity5" src="https://user-images.githubusercontent.com/85287/44508201-03b6d900-a6e0-11e8-8bc9-c5a2231371ed.png">

## 具体描述
视频56s处字幕**regression**，应译为**回归**
同样01:00处的 **regression**，应译为**回归**

**Comment by sylviasun916** [comment]
fixed and thanks
