### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索多个变量 > 设想的受众规模 - 年龄

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#450]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/701610057/concepts/8936186320923

## 截图
<img width="934" alt="udacity6" src="https://user-images.githubusercontent.com/85287/44510014-03214100-a6e6-11e8-8fee-13f6a56a61ca.png">

## 具体描述
视频31s处字幕**I don't see any pattern in the color**，目前翻译成了：**我没看到任何颜色的图案**
此处的pattern意为**模式**，
建议改为**我没有通过颜色看到任何模式**

**Comment by sylviasun916** [comment]
fixed and thanks
