### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索多个变量 > 设想的受众规模 - 年龄

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#451]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/701610057/concepts/8936186320923

## 截图
<img width="852" alt="udacity7" src="https://user-images.githubusercontent.com/85287/44510532-842d0800-a6e7-11e8-80d4-db411ca17983.png">

## 具体描述
视频43s处字幕 ...**and color really does't add much**， （目前翻成*并且真的没有增加多少颜色*）译文不通。

根据上下文建议译为 ...**并且颜色实际上没有提供多少帮助**

**Comment by sylviasun916** [comment]
fixed and thanks
