### ISSUE TITLE
数据分析进阶 > 探索性数据分析 > 探索多个变量 > 第三个定量变量

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#454]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/701610057/concepts/8737286480923

## 截图

<img width="1014" alt="udacity9" src="https://user-images.githubusercontent.com/85287/44512090-091a2080-a6ec-11e8-8f24-ad9f32e2bc46.png">

## 具体描述
1. 视频1:20s处字幕**variable tenure**, tenure在这里作为一个变量名，建议不译， 直接用**变量tenure** 
2. **reference year** 建议翻译成**参考年份**

**Comment by ChengGoooo** [comment]
“你需要用到 tenure 变量，并且以 2014 年作为参考年份。”

**Comment by sylviasun916** [comment]
fixed and thanks
