### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 7. 练习：ggpairs 函数

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#465]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8624987350923

## 截图

<img width="921" alt="udacity10" src="https://user-images.githubusercontent.com/85287/44649077-793ee400-aa15-11e8-9186-d9ad4e3c84ef.png">

## 具体描述
有**四段英文没有译文**

**Comment by sylviasun916** [comment]
收到！

**Comment by sylviasun916** [comment]
已修改更新 感谢反馈！
