### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 11. 练习：复习过度绘制

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#466]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8624987420923

## 截图
<img width="1037" alt="udacity11" src="https://user-images.githubusercontent.com/85287/44649162-b1462700-aa15-11e8-8c80-6422f707de99.png">

## 具体描述
文本格式问题：提示之间的行间距过大

**Comment by ChengGoooo** [comment]
可能是故意的。如果屏幕看起来像 
1280x800 或者 1366x768 的分辨率（比如 MBP13 默认状态），正好提示都是藏在视频下面了，而且需要持续滚动才能看到更多提示。但是在看起来像 1920x1080 或者更高的分辨率，以及浏览器的比例远离了 16:9 16:10，就没有意义了。

我决定还是去掉这些空行。
