### ISSUE TITLE
数据分析入门>统计学>抽样分布与中心极限定理>11符号法简介

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#467]
## 数据分析入门>统计学>抽样分布与中心极限定理>11符号法简介
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/4757541f-77eb-4df6-9ebf-9485a3383dd3/concepts/e2163bda-491f-43e4-be7e-eb6acbfc388f

## 截图
![image](https://user-images.githubusercontent.com/22834601/44649604-f28b0680-aa16-11e8-9c12-d85619924ea7.png)

## 具体描述
视频13s处字幕加是汉字，需改为 加是符号

**Comment by ZenRay** [comment]
从课程中的背景来看，建议将 “加” 翻译为“符号”。 @Kyliewang 
此外，课程中字幕 `notation` 范围为了 “注释”，在这里应该是“符号”，时间位置为 1s, 4s 。

**Comment by ChengGoooo** [comment]
13" 我理解他这句话说是  5 加 3 中的“加”是一个汉字，但是“+”是一个符号，表示“加”的意思，无论你在什么语言下，都是通用的。

后面赞同上面的说法，notation 在这里和 symbol 是同一个意思，都表示符号。

我比较建议翻译成：

> “加”只是一个汉字，但是“+”是一个符号，它是通用的。

一定要找近义词的话，就用记号和符号吧。

**Comment by sylviasun916** [comment]
fixed, thanks!
