### ISSUE TITLE
数据分析入门>统计学>抽样分布与中心极限定理>22 自展法

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#468]
## 数据分析入门>统计学>抽样分布与中心极限定理>22 自展法
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/4757541f-77eb-4df6-9ebf-9485a3383dd3/concepts/146870bc-129c-49c2-9cb7-635e6a6af8ea

## 截图

![image](https://user-images.githubusercontent.com/22834601/44650088-421e0200-aa18-11e8-9aea-10789ada28b6.png)

## 具体描述
视频中字幕显示自助法 bootstrapping，下面的字幕显示自展法 (bootstrap) ，在之后文字中自助法都写成了自展法，视频中都显示的自助法；应统一。

**Comment by ChengGoooo** [comment]
@Kyliewang 确定一个说法

**Comment by ZenRay** [comment]
@ChengGoooo 目前翻译和其他地方的链接，例如维基百科也是用的是自助法

**Comment by ChengGoooo** [comment]
@ZenRay thanks

@sylviasun916 统一为“自助法”吧。

**Comment by sylviasun916** [comment]
fixed, thanks
