### ISSUE TITLE
数据分析（进阶） > 课程9 ：钻石与价格预测 > 20. 构建线性模型

### ISSUE THREAD

**Issue by seawaywen** [udacity/DAND-CN-feedback#469]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/755209509/concepts/8624987660923

## 截图

<img width="969" alt="udacity12" src="https://user-images.githubusercontent.com/85287/44650611-a1c8dd00-aa19-11e8-8457-29bb23fc3f4e.png">

<img width="1041" alt="udacity13" src="https://user-images.githubusercontent.com/85287/44650634-b0af8f80-aa19-11e8-9606-859f86490bb4.png">

## 具体描述
视频12s处字幕**I stand for as is**，根据上下文这里的**I**是指函数I，不用翻译
 
视频21s处字幕中的regression翻译成了**递归**是错的，应该译为**回归**

**Comment by ZenRay** [comment]
之前已经提交了，尚未修改 @Kyliewang

**Comment by Kyliewang** [comment]
按上面mentor说的 @ChengGoooo

**Comment by Kyliewang** [comment]
辛苦圆圆将 递归 修改为 回归 @sylviasun916

**Comment by sylviasun916** [comment]
fixed and thanks！
