### ISSUE TITLE
【翻译问题】【Python 入门】数据类型和运算符 - rounds down 不是四舍五入

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#47]
## 课程导航+地址
数据分析入门 > Python 入门> 数据类型和运算符 > [2. 算数运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/861222b2-49d8-40c5-8e6c-9880f0044504)

## 截图
![tim 20180319204921](https://user-images.githubusercontent.com/11519486/37596570-96495526-2bb7-11e8-9ed4-b30a6ba00733.png)
![tim 20180319204906](https://user-images.githubusercontent.com/11519486/37596573-98e6d146-2bb7-11e8-936b-c783b6369335.png)
![image](https://user-images.githubusercontent.com/11519486/37597851-83dcf128-2bbb-11e8-80d3-4c005461d00c.png)
![image](https://user-images.githubusercontent.com/11519486/37597829-7526acc8-2bbb-11e8-83a3-61bd035b34cb.png)

## 具体描述
rounds down 是**向下取整**，而不是**四舍五入**。比如 3.5 不会四舍五入为 4，而是向下取整为 3

**Comment by sylviasun916** [comment]
感谢反馈！已采纳修改 在部署中
