### ISSUE TITLE
数据分析入门>统计学>A/B测试>7 指标 —— 点击率

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#472]
##数据分析入门>统计学>A/B测试>7 指标 —— 点击率
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/f3088061-6562-445e-b1a7-a86c9389c2b5/concepts/0fc48912-c4a4-498a-9217-b44330857e52

## 截图

![image](https://user-images.githubusercontent.com/22834601/44653767-32a3b680-aa22-11e8-8a6e-64a0ba4015bb.png)

## 具体描述
视频2s处中英文字幕 Udacity，需改为Audacity

**Comment by sylviasun916** [comment]
中英文已修改，感谢反馈！

**Comment by sylviasun916** [comment]
中英文已修改，感谢反馈！

**Comment by ZenRay** [comment]
> @sylviasun916 Audacity 为课程中虚拟出来的案例，此处应为 Audacity，并非 Udacity。辛苦圆圆修改~

从读音上来听的话，是 `Udacity`  @Kyliewang @sylviasun916
