### ISSUE TITLE
数据分析入门>统计学>A/B测试>11 指标——平均浏览时长

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#474]
## 课程导航+地址
数据分析入门>统计学>A/B测试>11 指标——平均浏览时长

https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/f3088061-6562-445e-b1a7-a86c9389c2b5/concepts/ae5b889a-b73e-4637-a63e-475d45636958

## 截图
![image](https://user-images.githubusercontent.com/22834601/44654279-b90cc800-aa23-11e8-8065-2c1ec0dff504.png)

## 具体描述
视频1‘’9s处字幕拔靴，需改为自助

**Comment by sylviasun916** [comment]
fixed and thanks
