### ISSUE TITLE
数据分析入门>统计学>回归>2 视频：机器学习简介

### ISSUE THREAD

**Issue by Majinglong** [udacity/DAND-CN-feedback#475]
## 课程导航+地址
数据分析入门>统计学>回归>2 视频：机器学习简介

https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/d780a3b0-a08e-4282-858e-6a28e8d524aa/concepts/c61e279c-c1de-4145-87ce-f42da62ba6c0

## 截图
![image](https://user-images.githubusercontent.com/22834601/44654602-d4c49e00-aa24-11e8-9b9a-e02403c824ed.png)

## 具体描述
链接打开显示404

**Comment by ChengGoooo** [comment]
我觉得这种不那么重要的链接最好还是少放～
