### ISSUE TITLE
数据分析进阶 >探索性数据分析 >探索多个变量 >10.练习：切割一个变量

### ISSUE THREAD

**Issue by JuniYao** [udacity/DAND-CN-feedback#477]
## 课程导航+地址
数据分析进阶 >探索性数据分析 >探索多个变量 >10.练习：切割一个变量 https://classroom.udacity.com/nanodegrees/nd002-cn-advanced/parts/62aab6e7-0d2b-4622-9937-77fe035aef31/modules/316518875375460/lessons/701610057/concepts/8737286510923

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/37874304/44665377-54179900-aa48-11e8-9fd6-6de730f81dc3.png)

## 具体描述
练习答案视频4s中，中文字幕“加入年料斗”翻译不恰当，且在这个视频中出现料斗，在下一个学习视频中翻译为bucket，上下文不统一。

**Comment by sylviasun916** [comment]
已修改，在部署中，谢谢反馈！
