### ISSUE TITLE
数据分析（入门） > 欢迎加入数据分析（入门） > 项目准备：SQL和移动平均值 > 43. 解决方案

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#482]
## 课程导航+地址
例子：数据分析（入门） > 欢迎加入数据分析（入门） > 项目准备：SQL和移动平均值 > [43. 解决方案: AND 和 BETWEEN](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/20a82dbe-5a80-4829-b9c8-198f518ed20e/modules/188c878c-5365-4bf3-9fa8-08cf57336fc4/lessons/eb0e4ed3-e04a-4328-aece-da8cf6fc2607/concepts/3ee697bd-b908-44c8-9f7e-69c1b6324ad6)

## 截图
![_20180902201344](https://user-images.githubusercontent.com/11519486/44955875-39806c80-aeed-11e8-8ae0-1d2cea57346d.png)

## 具体描述
英文原文：You will notice that using BETWEEN is tricky for dates! While BETWEEN is generally inclusive of endpoints, it assumes the time is at 00:00:00 (i.e. midnight) for dates. This is the reason why we set the right-side endpoint of the period at '2017-01-01'.

这段话直译的话，反而不好理解，我尝试结合课程的内容修改了一下中文的表述：

你可能会觉得对日期数据使用 BETWEEN 不太好理解。对于单纯的日期数据而言（只包含年月日不包含时间的数据，比如 '2017-01-01'），其默认时间为日期当天的 00:00:00（也就是午夜时分），而 BETWEEN 通常是不包含端点在内的，这也是为什么将右边的时间点设置为 '2017-01-01' 的原因。

@Kyliewang 看看这样改行不行？

**Comment by ZenRay** [comment]
@ivylee0919  翻译效果要好很多，另外提议将括号内的时间修改为 '2016-12-31' 这样更好一些——你可能会觉得对日期数据使用 BETWEEN 不太好理解。对于单纯的日期数据而言（只包含年月日不包含时间的数据，比如 '2016-12-31'），其默认时间为日期当天的 00:00:00（也就是午夜时分），而 BETWEEN 通常是不包含端点在内的，这也是为什么将右边的时间点设置为 '2017-01-01' 的原因。 @ChengGoooo @Kyliewang

**Comment by Kyliewang** [comment]
Done. 谢谢~
