### ISSUE TITLE
入门 > 项目 > 探索没过共享单车数据> 如何测试你的代码[图片未显示]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#483]
## 课程导航+地址
入门 > 项目 > 探索没过共享单车数据> [如何测试你的代码
](https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/0ad43cea-8e74-4486-911c-d1fae2f03c97/modules/134150b9-81b0-40d1-9c2c-bb288bb49d55/lessons/e5bef1dd-5031-45c3-aaf7-8536f6f3cf8a/concepts/0f6c8e5e-53d8-45e8-b961-82619b1e0f51)

## 截图
![image](https://user-images.githubusercontent.com/24636410/45141336-2ec52080-b1e8-11e8-9a66-153f01c52a4e.png)

## 具体描述
页面没有显示出图片

**Comment by ivylee0919** [comment]
@Kyliewang

**Comment by Kyliewang** [comment]
收到，感觉像是产品问题，html语法插入的文件显示不出来了。我跟进一下。

**Comment by ZenRay** [comment]
这个是一个动态的 Gif 图，会不会是因为这个原因 @Kyliewang

**Comment by Kyliewang** [comment]
不会，后台上仍然显示正常，应该是产品的前台显示问题。

**Comment by Kyliewang** [comment]
已经手动修复。
