### ISSUE TITLE
入门 > 数据分析过程>翻译 > [16. 视频: GROUP BY（第二部分）]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#487]
## 课程导航+地址
入门 > 数据分析过程 > 翻译 > [16. 视频: GROUP BY（第二部分）](https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/f1a8739b-f3eb-40c5-b280-e820b404e73f/modules/cb3d1757-f1e2-46dd-9089-6b70c0984938/lessons/76a484da-1f2e-4886-ba2c-684bb30e267d/concepts/4fa22b85-f179-48b1-99f1-de24c2d7e92b)

## 截图
![image](https://user-images.githubusercontent.com/24636410/45614066-d40aaf00-ba9a-11e8-9490-777eaf1e1f19.png)

## 具体描述
翻译的意思反了，这里应该是“任何出现在 GROUP BY 语句中的列，不能出现在聚合函数中“ @Kyliewang  @sylviasun916

**Comment by Kyliewang** [comment]
“任何不在聚合函数中的列，必须出现在 GROUP BY 语句中“

已经修改~

**Comment by ZenRay** [comment]
后面部分用 “必须出现在” 不太合适吧，这样的话意思就是其他没有进行聚合计算的列就都必须进行"GROUP BY" 了。建议用：“任何出现在 GROUP BY 语句中的列，不能出现在聚合函数中“——这样才是表示不能使用 "GROUP BY" 的列来进行计算的意思吧。 @Kyliewang
