### ISSUE TITLE
入门 > 数据分析过程 > 练习 > [11. 使用可视化探索数据]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#488]
## 课程导航+地址
入门 > 数据分析过程 > 练习 > [11. 使用可视化探索数据](https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/f1a8739b-f3eb-40c5-b280-e820b404e73f/modules/67ffb9a3-f120-4883-addd-db037e99c466/lessons/77286f5a-b206-4807-aaa0-7ecfc690268e/concepts/31103bc1-f873-42b9-bec7-bb48c2f3b091)

## 截图
![image](https://user-images.githubusercontent.com/24636410/46120364-ed052400-c241-11e8-9a22-8690d38f2dd4.png)

![image](https://user-images.githubusercontent.com/24636410/46120385-f8f0e600-c241-11e8-93c8-78b16c1a5a9d.png)

## 具体描述
第二个问题是需要根据等级来绘制散点图，但是酒等级被当作分类数据来绘制可视化结果不是很好，建议更换为柱状图（bar)，且将问题放在 `groupby` 部分。

**Comment by Kyliewang** [comment]
使用散点图虽然不是最佳可视化方式，但可以回答此问题。暂时无需处理。
