### ISSUE TITLE
入门 > 数据分析过程 > 练习 > [6. Notebook + 练习：均数差]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#490]
## 课程导航+地址
入门 > 数据分析过程 > 练习 > [6. Notebook + 练习：均数差](https://classroom.udacity.com/nanodegrees/nd002-cn-basic-vip/parts/4e7e2f82-e05e-4fbe-b29c-fe3169c6dd77/modules/0596b9e8-4a3a-41c3-a929-6c72c0c93925/lessons/e1bdfed4-1d7f-4907-9bf1-76f1b196d660/concepts/24837cb6-f3cc-4455-aed0-523331ca979d)

## 截图
![image](https://user-images.githubusercontent.com/24636410/47088988-6648d300-d252-11e8-99e0-bb564556d2f3.png)

## 具体描述
练习部分存在疑问，这里的第二个练习不正确，这里的答案应该是正确的

**Comment by Kyliewang** [comment]
已修改~
