### ISSUE TITLE
入门 > 统计学 > 假设检验 > [13.在两种假设中如何选择？]视频1s处字幕多了一个“一旦”

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#491]
## 课程导航+地址
例子：入门 > 统计学 > 假设检验 > [13.在两种假设中如何选择？](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a3aadb08-9613-4d77-b007-e55b21c3b72d/modules/060a25e4-da9a-40f5-8ccf-3c503c67654d/lessons/ad8aca80-f444-4479-8848-5b07bafaf66c/concepts/f7c0b643-82b1-44ca-ab0d-a2907fd5a4ff)

## 截图

![image](https://user-images.githubusercontent.com/38323732/48350410-095e0280-e6c2-11e8-87ed-2fb3199e0924.png)

## 具体描述
视频1s处字幕多了一个“一旦”

**Comment by yifangwang08** [comment]
感谢反馈！已修改~
