### ISSUE TITLE
入门 > 统计学 > 练习文档和练习题目错误 > python 概率练习

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#492]
## 课程导航+地址
入门 > 统计学 > 练习文档和练习题目错误 > [python 概率练习](https://classroom.udacity.com/nanodegrees/nd002-cn-svip/parts/aa43a8dd-58c2-497d-87b6-97a8abe1d379/modules/3ae93030-ae09-4304-9af8-f62c8dd38666/lessons/33860189-96c0-40cf-8f12-5772c8b8c790/concepts/2c87518c-73ec-4b5f-bf1d-4f7af4e73b97)

## 截图

![image](https://user-images.githubusercontent.com/24636410/48465001-5fdf5400-e81c-11e8-9991-803986d1264a.png)

## 具体描述
前面要求的是 `P(H) = 0.15 时十次不均衡掷硬币得到三次正面`，而后面要求计算的是 `P(H) = 0.15 时十次不均衡掷硬币得到三次及三次以上正面`  @Kyliewang

**Comment by Kyliewang** [comment]
已经修改
