### ISSUE TITLE
进阶 > EDA > 链接不可用 > [为何要学习 EDA？]

### ISSUE THREAD

**Issue by ZenRay** [udacity/DAND-CN-feedback#497]
## 课程导航+地址
例子：进阶 > EDA > 链接不可用 > [为何要学习 EDA？](https://classroom.udacity.com/nanodegrees/nd002-cn-advanced-vip/parts/7af8e761-54e5-4c80-a284-e402c30a791b/modules/6d4d3e12-5a35-46e8-a597-60258900acae/lessons/685569241/concepts/8762786480923)

## 截图
![image](https://user-images.githubusercontent.com/24636410/50066675-2b363200-01f8-11e9-9c7d-74188afaf9b5.png)

## 具体描述
最后一个链接报 404 错误，链接失效

**Comment by yifangwang08** [comment]
感谢反馈！
