### ISSUE TITLE
文档翻译错误

### ISSUE THREAD

**Issue by ketra21** [udacity/DAND-CN-feedback#499]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

## 截图
<img width="1212" alt="demo" src="图片地址">

## 具体描述
视频44s处字幕XXXX，需改为XXXX

**Comment by ZenRay** [comment]
这个是 Issue 提交错误吗？ @ketra21
