### ISSUE TITLE
数据分析（入门）纳米学位汉化校正 - Sebastian统计学 - 项目四

### ISSUE THREAD

**Issue by kexinlin** [udacity/DAND-CN-feedback#5]
**项目四**
问题 5：假设检验
习题的前两个问题描述“在条件为空的情况下 p_new”和“在条件为空的情况下 p_old ”，还有最后一个问题描述“在条件为空的情况下 p_new - p_old”，应当翻译为“在零假设下的p_new”，“在零假设下的p_old”，以及“在零假设下的p_new - p_old”。

问题选项中的145273应当为145274。

提交习题答案后弹出的窗口“没错，这个很棘手。但是这里我们看到一个空值，页面上转换没有影响，意味着在每个页面的转换都相同”中的“但是这里我们看到一个空值，页面上转换没有影响”存在歧义，原文为“But here we are looking at a null where there is no difference in conversion based on the page…”，null指的是null hypothesis，应当翻译为”这里我们看的是零假设，在页面转换率上不存在差别……”。

项目Jupyter Notebook
先前提过的小建议，把问题分别放在不同的Markdown单元格内可能会对完成项目方便一些。

最后一个单元格，收集提交材料部分的第三行，“注：在模块名称中，不要包含 "<" or ">" 或任何带有期限的词汇”，其中“带有期限的词汇”原文为“any words following a period”，这里的“period”指的是句号。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
