### ISSUE TITLE
【字幕typo】【Python 入门】数据类型和运算符

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#50]
## 课程导航+地址
数据分析入门 > Python 入门> 数据类型和运算符 > [4. 变量和赋值运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/cf20e9f1-9b19-4bea-b2e1-d5c591e20877) > 变量和赋值运算符第一个视频文件，**ID：7pxpUot4x0w**

## 截图
![tim 20180319212509](https://user-images.githubusercontent.com/11519486/37599340-794864f0-2bbf-11e8-95c5-c1e3ae9ccdd5.png)
![tim 20180319212809](https://user-images.githubusercontent.com/11519486/37599415-a5d84378-2bbf-11e8-9770-5cfab2374043.png)

## 具体描述
- 视频46s处字幕“其中 **y=x** 和 y=x 表示相同的概念”，需改为“其中 **x=y** 和 y=x 表示相同的概念”
- 视频1:25处字幕“在这行 我们只需变量名称 x 将 y 定义为其值 2”，建议改为“在这行 我们只需变量 x 的名称就可以将 y 定义为 x 的值 2”

**Comment by sylviasun916** [comment]
已采纳修改 在部署中 感谢反馈！
