### ISSUE TITLE
【课程内容格式】数据类型和运算符 - 5. 练习

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#54]
## 课程导航+地址
数据分析入门 > Python 入门> 数据类型和运算符 > [5. 练习：变量和赋值运算符
](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/0edf3cc8-5c35-43a9-bd6e-d410f0ad2978)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37600148-6d0ac8c0-2bc1-11e8-96cf-9adabb7463f2.png)

## 具体描述
这里的 \n \t 都没有识别出来，按照格式显示

**Comment by sylviasun916** [comment]
已修改页面，感谢反馈！
