### ISSUE TITLE
【翻译问题】【Python 入门】数据类型和运算符

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#57]
## 课程导航+地址
数据分析入门 > Python 入门> 数据类型和运算符 > [6. 解决方案：变量和赋值运算符](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/861222b2-49d8-40c5-8e6c-9880f0044504)

## 截图
![image](https://user-images.githubusercontent.com/11519486/37600529-8c2fbd4a-2bc2-11e8-978d-ee279f465b7c.png)

## 具体描述
最后一段比较难理解，尝试理解了一下，不是按字面翻译的，不知道对不对：
```markdown
考虑到 `mv_population` 的变化，为了更新 `mv_density` 的值，我们需要再次运行下面这行：

……
这是人们来到山景城和离开山景城之后的新人口密度。所有变量都已更新为 `mv_population`  变化后的对应结果。
```

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
