### ISSUE TITLE
【共享单车】【项目详情】下载出错

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#59]
## 课程导航+地址
数据分析入门 > Python 入门> 探索美国单车共享数据 > [2. 项目详情](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/d233dd24-607b-4bb1-a17d-dfa94768104b)

![image](https://user-images.githubusercontent.com/11519486/37601539-39744514-2bc5-11e8-9414-ce4fcd497274.png)

![tim 20180319222357](https://user-images.githubusercontent.com/11519486/37601524-2f96375a-2bc5-11e8-9f00-dd7d5a4838c0.png)
![tim 20180319222429](https://user-images.githubusercontent.com/11519486/37601528-3195cafc-2bc5-11e8-9360-67993285af87.png)

## 具体描述
最后两个代码文件的下载报错，资源选项卡的文件下载超级慢。。

**Comment by Kyliewang** [comment]
已经修复。

**Comment by Kyliewang** [comment]
资源选项卡的文件下载超级慢  这个问题没有办法，因为数据很大。。
