### ISSUE TITLE
【翻译问题】【Python 入门】为何要学习 Python 编程

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#6]
## 课程导航+地址
数据分析入门 > Python 入门 > 为什么要学习 python 编程> [1. 课程概述](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/410ddff6-0f40-4d69-a63d-22094c21350a/concepts/285fb88b-39c5-4c6b-8b43-0081e83ef1e3)

## 截图
![tim 20180316212717](https://user-images.githubusercontent.com/11519486/37523084-d8684eb6-2960-11e8-93b0-42a71d28e19a.png)

## 具体描述
使用 youtube 播放：视频33s处字幕“编程做法”，需改为“编程实践”
使用墙内视频播放：没有中文字幕

**Comment by Kyliewang** [comment]
字幕已添加。
