### ISSUE TITLE
课程2：数据类型和运算符-解决方案 变量和赋值运算符【文字错误】

### ISSUE THREAD

**Issue by DylanYangSH** [udacity/DAND-CN-feedback#66]
## 课程导航+地址
1.新Python入门 > 课程2：数据类型和运算符 > 6. 解决方案：变量和赋值运算符  > https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/ebd93cf2-9329-4415-9bc2-7281e2aa9e13/concepts/e968300b-6d70-4898-b1e6-fd39952cb186

## 截图
<img width="553" alt="issues 002-6-1" src="https://user-images.githubusercontent.com/37236103/37610019-8a1b1af6-2bd9-11e8-9b2e-d51abcf5c114.png">

## 具体描述
文字错误。
应将“以考虑这一变化因素”改为“已考虑这一变化因素”，这里的表述别扭。

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
