### ISSUE TITLE
lesson6 Numpy & Pandas 第1部分 > [4.NumPy 和 Pandas 中的一维数据] - francis

### ISSUE THREAD

**Issue by mengfanchun2017** [udacity/DAND-CN-feedback#78]
## 课程导航+地址
lesson6 Numpy & Pandas 第1部分 > [4.NumPy 和 Pandas 中的一维数据](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490070923)

## 截图
NA

## 具体描述
课堂内容 - 课程代码 - daily_engagement_full.csv 无此文件，不能本地跑代码（记得好像是数据分析再之前的课中有，需要增加下载，连接或者在资源列表中）

**Comment by Kyliewang** [comment]
数据下载链接已经补充。
