### ISSUE TITLE
列表推导式

### ISSUE THREAD

**Issue by lixianyu** [udacity/DAND-CN-feedback#8]
## 课程导航+地址
课程3：控制流 > [列表推导式](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/41c9267a-c9bd-42c8-9897-78e49b376471)

## 具体描述
原文：如果你要添加 you would like to add else，则需要将条件语句移到列表推导式的开头，直接放在表达式后面，如下所示。
建议改为：如果你要添加else，则需要将条件语句移到列表推导式的开头，直接放在表达式后面，如下所示。

**Comment by Kyliewang** [comment]
@lixianyu 
![screen shot 2018-03-19 at 11 32 47 am](https://user-images.githubusercontent.com/35555101/37576845-51c41470-2b69-11e8-8968-3d07292768b3.png)
字幕中没有发现此问题，请确认。
