### ISSUE TITLE
esson6 Numpy & Pandas 第1部分 > [14.练习：Series 索引] - francis

### ISSUE THREAD

**Issue by mengfanchun2017** [udacity/DAND-CN-feedback#81]
## 课程导航+地址
esson6 Numpy & Pandas 第1部分 > [14.练习：Series 索引](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490350923)

## 截图
NA

## 具体描述
课堂内容 - 练习题答案 - 提交答案时候，无论什么都能通过。

**Comment by sylviasun916** [comment]
@Kyliewang

**Comment by Kyliewang** [comment]
经过确认并没有出现这种情况。麻烦再确认一下 @mengfanchun2017
