### ISSUE TITLE
lesson6 Numpy & Pandas 第1部分 > [17.练习：Pandas Series apply()] - francis

### ISSUE THREAD

**Issue by mengfanchun2017** [udacity/DAND-CN-feedback#83]
## 课程导航+地址
lesson6 Numpy & Pandas 第1部分 > [17.练习：Pandas Series apply()](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490440923)

## 截图
NA

## 具体描述

	1. 课堂内容 - 课程代码 - 课程视频中的示例文件是不能运行的，而且解决方案的话可以不用list和Series转化这一步。两种解决代码 详见ipynb代码。
	2. 课堂内容 - 练习题答案 - 答案中两个函数def reverse_names, def reverse_name容易让人混乱，解决使用1个就行了。写了两个代码，本地和测试答案都没问题，但是提交答案通不过。详见ipynb代码。

文件传输了几次不行，请参见francis lesseon6 的ipynb，内容都是一样的。

**Comment by sylviasun916** [comment]
@Kyliewang

**Comment by Kyliewang** [comment]
经过确认答案没有问题。使用reverse_name和reverse_names是为了应用apply()，不可以删除掉。
