### ISSUE TITLE
lesson6 Numpy & Pandas 第1部分 > [18.练习：在 Pandas 中绘图] - francis

### ISSUE THREAD

**Issue by mengfanchun2017** [udacity/DAND-CN-feedback#84]
## 课程导航+地址
lesson6 Numpy & Pandas 第1部分 > [18.练习：在 Pandas 中绘图](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/18337233-0c82-48d8-8654-fbaf72e37c65/concepts/54301490470923)

## 截图
NA

## 具体描述

	1. 课堂内容 - 文字部分

		1. 原文 - Pandas 还有在后台使用 matplotlib 的内置绘图函数，因此如果 data 是一个 Series，你可以使用 data.hist() 创建直方图。- 此处并没有明确表示出使用pandas的话不用import matplotlib，因为pandas已经包含了matplotlib的意思。
		2. 修改 - Pandas库实际上已经内置了matplotlib库的绘图函数。也就是说如果对Pandas库中的Series数据绘图，不用import matplotlib就能完成绘图。另外，例子中的seaborn也是一种绘图样式库。

[intropy3_lesson6_v3.zip](https://github.com/udacity/DAND-CN-feedback/files/1835979/intropy3_lesson6_v3.zip)

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
