### ISSUE TITLE
问题概述# Numpy & Pandas-第二部分-1

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#88]
入门 > 新Python入门 > Numpy & Pandas-第二部分> [21. 结论](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/12cedc4a-517f-44f8-9b73-de46ae994a0c/concepts/54422618120923)

<img width="215" alt="_20180322172753" src="https://user-images.githubusercontent.com/33887956/37762685-07dd518c-2df8-11e8-82b2-63e0bda869cd.png">
<img width="163" alt="_20180322174034" src="https://user-images.githubusercontent.com/33887956/37762749-2dcfda36-2df8-11e8-8b65-fd0c8492fb91.png">

在雪中玩耍的红色熊猫  - 需要VPN
在滑梯上玩耍的熊猫 - 需要VPN
这些熊猫视频不需要VPN - 建议修改为"这些熊猫视频需要VPN"，另建议拿掉"这些熊猫"的hyper link

**Comment by sylviasun916** [comment]
@Kyliewang  外链修改问题，麻烦看一下

**Comment by Kyliewang** [comment]
已经重新进行了说明。请确认！
