### ISSUE TITLE
问题概述-单词错误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#89]
入门 > 新Python入门 > Numpy & Pandas - 第二部分> [20. 三维数据](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/12cedc4a-517f-44f8-9b73-de46ae994a0c/concepts/54067602430923)

<img width="264" alt="_20180322175522" src="https://user-images.githubusercontent.com/33887956/37763510-3b69fae4-2dfa-11e8-91f8-75b46a95f982.png">

 Panels 建议修改为 Panel，没有s

**Comment by Kyliewang** [comment]
已经修改，感谢反馈！
