### ISSUE TITLE
3的倍数

### ISSUE THREAD

**Issue by lixianyu** [udacity/DAND-CN-feedback#9]
## 课程导航+地址
控制流 > 21.练习：列表推导式 > [3的倍数](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/be839dbf-f02a-4a51-b708-8e54f4b4f7e6)

## 具体描述
原文：使用列表推导式创建一个列表 multiples_3，其中包含前 20 个 3 的倍数。
建议改为： 使用列表推导式创建一个列表 multiples_3，其中包含1~ 20整数的3的倍数。

**Comment by Kyliewang** [comment]
@sylviasun916 

已经在coco里面修改过了，文本翻译不容易理解。
