### ISSUE TITLE
问题概述-代码块的样式颜色

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#90]
入门 > 新Python入门 > Numpy & Pandas - 第二部分 > [20. 三维数据](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/12cedc4a-517f-44f8-9b73-de46ae994a0c/concepts/54067602430923)

<img width="295" alt="_20180322180056" src="https://user-images.githubusercontent.com/33887956/37763904-481cd314-2dfb-11e8-8752-b7f34fa6a26c.png">

建议代码块的样式颜色统一，可能会影响到用户体验

**Comment by Kyliewang** [comment]
此处为代码块的自动显示，无法调整。先暂时搁置，后续反馈给产品。
