### ISSUE TITLE
问题概述-排版

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#91]
入门 > 新Python入门 > Numpy & Pandas - 第二部分 > [19. 练习:使用DataFrame绘制图形](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/12cedc4a-517f-44f8-9b73-de46ae994a0c/concepts/54422618100923)

<img width="591" alt="_20180322180909" src="https://user-images.githubusercontent.com/33887956/37764418-9e2c5698-2dfc-11e8-98b0-0d633ae954fd.png">

建议改善该区块的缩进，并删除第一行的*号。

**Comment by Kyliewang** [comment]
![image](https://user-images.githubusercontent.com/35555101/37865144-4f73a7dc-2fb3-11e8-8efe-eafae542b267.png)
@sylviasun916 麻烦圆圆看下这里怎么修改，似乎我没有修改权限。将如果之前*前面的空格去掉即可。

**Comment by sylviasun916** [comment]
@Kyliewang  已修改 和en-us 保持一致的显示格式
