### ISSUE TITLE
问题概述-字幕

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#92]
入门 > 新Python入门 > Numpy & Pandas - 第二部分 > [2.练习:地铁数据 ](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/12cedc4a-517f-44f8-9b73-de46ae994a0c/concepts/54422617660923)

<img width="636" alt="_20180322183827" src="https://user-images.githubusercontent.com/33887956/37765989-a8c06096-2e00-11e8-805e-88484c0c8fa4.png">

视频11s处字幕Panda，需改为Pandas

**Comment by Kyliewang** [comment]
@sylviasun916 麻烦修改下哦~
