### ISSUE TITLE
问题概述-无中英字幕

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#93]
入门 > 新Python入门 > 控制流 > [17. Zip和Enumerate](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/a95d285d-fd94-4a29-ad95-68bf3d13b253)

<img width="683" alt="_20180322185657" src="https://user-images.githubusercontent.com/33887956/37766748-d4bd3a1e-2e02-11e8-8361-c9e0c3ec69f9.png">

整个视频都没有中/英字幕

**Comment by Kyliewang** [comment]
已经添加。
