### ISSUE TITLE
问题概述-字幕相关

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#94]
入门 > 新Python入门 > 控制流 > [14. Break,Continue](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/27cafe73-8971-45d2-a950-48ed8e2c8d38)

<img width="662" alt="_20180322190347" src="https://user-images.githubusercontent.com/33887956/37767117-f10a9cd8-2e03-11e8-8b3e-26a6f1941943.png">

该视频缺少中/英字幕

**Comment by Kyliewang** [comment]
已经修改。
