### ISSUE TITLE
问题概述-课程页面内容的代码

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#95]
入门 > 新Python入门 > 控制流 > [11. While循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/dd92659f-e3d1-4997-b865-d61416a30f9c)

<img width="346" alt="_20180322191053" src="https://user-images.githubusercontent.com/33887956/37767402-fea8b108-2e04-11e8-85dd-8edbae67d2b8.png">

第2点，在此示例中，将sum(hand) <= 21 修改为 sum(hand) <= 17

**Comment by sylviasun916** [comment]
@Kyliewang  中英文文本一致，需要你介入查一下，是不是源文本出错。修改后即可 close 掉

**Comment by Kyliewang** [comment]
已经修改。感谢反馈！
