### ISSUE TITLE
问题概述-while循环-视频内的代码有误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#96]
入门 > 新Python入门 > 控制流 > [11. While循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/dd92659f-e3d1-4997-b865-d61416a30f9c)

<img width="652" alt="_20180322192939" src="https://user-images.githubusercontent.com/33887956/37768093-62d57682-2e07-11e8-9b58-dcfeaee2b331.png">
<img width="221" alt="_20180322192351" src="https://user-images.githubusercontent.com/33887956/37768021-18c48f7e-2e07-11e8-8133-284191927b0a.png">
<img width="66" alt="_20180322192404" src="https://user-images.githubusercontent.com/33887956/37768025-1e04e506-2e07-11e8-97c7-625ea03b5583.png">

视频02:07s处里的代码，print(sum)应为print(sum(hand))

**Comment by sylviasun916** [comment]
@Kyliewang

**Comment by sylviasun916** [comment]
@Kyliewang  我在视频下方备注了 
![image](https://user-images.githubusercontent.com/31837843/37885291-f81aad84-30e6-11e8-8472-e2d2541b1b8d.png) 你觉得OK么？ OK的话就 close 这个ticket 吧，谢谢

**Comment by Kyliewang** [comment]
感谢Sylvia!
