### ISSUE TITLE
问题概述:# 字幕翻译有错误

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#97]
入门 > 新Python入门 > 控制流 > [8. For循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/5c057e68-4556-4f47-885b-1c964003df27)

<img width="680" alt="_20180322195354" src="https://user-images.githubusercontent.com/33887956/37769184-25bbe69c-2e0b-11e8-8bf1-c515bd63e9c6.png">

视频04:03s处字幕"方程range()"，需改为"函数range()"

**Comment by Kyliewang** [comment]
@sylviasun916 
字幕翻译的问题，麻烦圆圆修改。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
