### ISSUE TITLE
【共享单车项目】【实战项目概览】说明需要有英文

### ISSUE THREAD

**Issue by ivylee0919** [udacity/DAND-CN-feedback#98]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/69d58a7b-a6d3-457e-8ac4-83176aa37eae/lessons/c7100960-9fd3-4d73-b8c0-f57c8bd9de9b/concepts/e32ff3f7-8031-400c-a3d2-0fbb05b061ef

### 课程页面说明
![image](https://user-images.githubusercontent.com/11519486/37769057-c13ce374-2e0a-11e8-9438-22e5716901e3.png)

### 项目文件指导
![image](https://user-images.githubusercontent.com/11519486/37769157-0ca5a53a-2e0b-11e8-9a83-fd6141a8c42d.png)

## 具体描述
因为涉及到具体的项目指导，并且项目都使用的是英文，建议这里的说明保留原英文，尤其是后面的输入值 @Kyliewang

**Comment by sylviasun916** [comment]
已添加 谢谢反馈
