### ISSUE TITLE
问题概述# 课程页面内容部份，语意不通

### ISSUE THREAD

**Issue by wjl77** [udacity/DAND-CN-feedback#99]
入门 > 新Python入门 > 控制流 > [8. For循环](https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/affb505b-aa98-4bf7-bb14-a883751a4d05/modules/5da3c610-841e-4a7d-b424-4005ffe70588/lessons/e91dc8c3-aed0-4c0c-9a43-438c36df7b0f/concepts/5c057e68-4556-4f47-885b-1c964003df27)

<img width="601" alt="_20180322201052" src="https://user-images.githubusercontent.com/33887956/37769921-abf6d710-2e0d-11e8-994f-ad5006a1d7c8.png">

1，上图的第二点中，部分内容语意不通，建议将“被遍历是什么可迭代对象”改为"被遍历的是可迭代的对象"

2，接上一行，"用什么名称"，建议修改为"用迭代变量"

**Comment by Kyliewang** [comment]
@sylviasun916  已经修改，翻译质量问题，请确认。
